- src/components/ApeToggle/ApeToggle.tsx
- src/forms/AdminUserForm.tsx
- src/hooks/useAdminApi.ts
- src/pages/AdminPage/AdminEpochModal.tsx
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AdminPage/AdminUserModal.tsx
Require: https://github.com/coordinape/coordinape-backend/pull/46
After seeing Moonshot use the admin user epoch, I reordered the fields and switched the polarity of non_giver.
Also, `const { deleteUser, deleteEpoch } = useAdminApi()` had been kept in the action renderer and would be called with stale values.
> Fix past repeat epoch and cleanup user admin

- src/components/ConnectWalletModal/ConnectWalletModal.tsx
Portis and Fortmatic have never been setup - remove them as wallet connect options.
The UI looks a little empty...
@levity @exrhizo
> Remove broken Portis and Fortmatic Wallet connections

- src/pages/VouchingPage/NewNominationModal.tsx
https://linear.app/coordinape/issue/DEV-314/copy-mistake-in-vouching-nomination-form-placeholder-text
I thought about this for about 15 seconds, and couldn't come up with any significantly better text...
@AlexDistill did you have more concrete suggestions for changing this? For now, I'm removing the placeholder comment part of it.
Review: @exrhizo @levity
> Remove placeholder text

- src/hooks/index.ts
- src/hooks/useAllocation.ts
- src/hooks/useDeepChangeEffect.ts
- src/pages/AllocationPage/AllocationGive.tsx
- src/recoilState/allocationState.ts
- src/recoilState/appState.ts
- src/services/api.ts
https://linear.app/coordinape/issue/DEV-286/allocation-buttons-not-working-buttons-are-disabled
The `useAllocation` hooks were not easily readable,
so I rewrote them to be more simple and organized.
Now the give page shows cards for teammates that are in the local state's `pendingGive` that way there can't be a discrepancy between what there are controls for and the underlying state.
when the teammate selector is disabled, there is still a teammates data structure, it is just set to be all available teammates and the hook throws an error if you try to change them.
> Clean up useAllocation to fix allocation not working

- src/components/CircleSelectModal/CircleSelectModal.tsx
- src/components/MyProfileCard/MyProfileCard.tsx
- src/hooks/index.ts
- src/hooks/useAllocation.ts
- src/hooks/useApi.ts
- src/hooks/useAsyncLoadCatch.ts
- src/hooks/useMe.ts
- src/hooks/useProfile.ts
- src/pages/AdminPage/AdminCircleModal.tsx
- src/pages/AdminPage/AdminEpochModal.tsx
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AdminPage/AdminUserModal.tsx
- src/pages/AllocationPage/AllocationPage.tsx
- src/pages/CreateCirclePage/CreateCirclePage.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/pages/VouchingPage/NewNominationModal.tsx
- src/pages/VouchingPage/NomineeCard.tsx
- src/services/api.ts
- src/utils/provider.ts
- Move towards separating state from mutations
- `useMe`: `updateProfile`, `updateAvatar`, `updateBackground`
- Provider types included
- When signature fails, fail immediately with the error message
- If allocating give, mention the smaller transaction size there
- wrap all `useAsyncLoadCatch.ts` usages with `try{}catch(e){}` or `.catch()`
- just show a info alert if the user rejects the signature
> Improve error handling and move api hooks

- .env.example
- README.md
Add more detailed guide to setting up the `.env` file in setup instructions.
Why: Open source contributors were getting stuck on the the .env setup step.
Cleanup .env.example file.
> Add .env setup instructions

- src/forms/AdminUserForm.tsx
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AdminPage/AdminUserModal.tsx
- src/routes/routes.tsx
Fix admin role checks
These admin role checks broke with the addition of another user role (2 - coordinape donation user), and I think
it makes a lot more sense to check if they are role admin, rather than if they are not role normal user.
I did a search for the role, but if there's anywhere else I may need to change this too, let me know.
> Fix admin role checks

- src/components/ApeInfoTooltip/ApeInfoTooltip.tsx
- src/components/ProfileCard/ProfileCard.tsx
- src/config/constants.ts
- src/pages/AdminPage/AdminPage.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/routes/paths.ts
- src/theme/colors.ts
- src/types/material-ui.d.ts
Summary: Add Coordinape User to all Circles
This PR joins the backend PR for implementing this feature: https://github.com/coordinape/coordinape-backend/pull/50
On the frontend we change the following:
- On Admin Page, hide the edit button by for the CoordinapeUser (allow deletes)
- Add tooltip with coordinape user info to display this user differently
> Add Coordinape User to all Circles

- src/components/ApeAvatar/ApeAvatar.tsx
Uses https://ui-avatars.com/ to generate initial icons. It's a free API that does >800mm reqs/mo and I've used it for a few projects. It'll handle splitting a name into initials when given names with a segment, otherwise it uses the first two letters of a single name.
We can also customize the API output as desired.
Before:
After:
Closes #272
> Change ApeAvatar component to default to user's initials

- src/components/ApeAvatar/ApeAvatar.tsx
- src/pages/AssetMapPage/AMForceGraph.tsx
- src/recoilState/mapState.ts
- src/utils/domain.ts
Closes #272 
This extracts placeholder logic from `ApeAvatar` in `util/domains` and uses the new logic in both `ApeAvatar` and `AMForceGraph`.
Builds on work from https://github.com/coordinape/coordinape/pull/278
> Extract getAvatarPathWithInitialsFallback, use in ApeAvatar and AMForceGraph

- .github/workflows/CI.yml
- src/forms/createForm.tsx
- src/forms/formHelpers.ts
Allows inputting ENS names anywhere we take an ETH address in a form. Closes #279 
Some screenshots of it in action:
1. Error states still work
2. ENS names now work
3. ENS gets translated to bare address before it ends up in the database
> Support ENS resolution in zEthAddress form helper

- src/pages/AdminPage/AdminCircleModal.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/utils/domain.ts
- Added fallback initials avatar image to `ProfilePage` and `AdminCircleModal`.
I didn't find other pages that use `circle.logo` or `.logo` for this purpose, but let me know if there are others.
> add fallback initials avatar to Circle in ProfilePage

- src/components/ActionDialog/ActionDialog.tsx
- src/components/index.ts
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AllocationPage/AllocationEpoch.tsx
- add warning on opt out
- Remove TODO: rename DialogNotice to ActionDialog
Looks like this, the 0 GIVE value is there just for demo purpose, it will check for > 0 GIVE received.
> add warning on opt out, rename DialogNotice to ActionDialog

- src/config/networks.ts
This PR rounds out the fixes for vault creation. You can now mint a vault with any given token. I used a zero address for eth to allow use of same data structure.
> added zero address to allow for eth vault creation

- .github/workflows/delete-hasura-preview.yml
- .github/workflows/hasura-preview.yml
- api/hasura/auth.ts
- src/config/env.ts
closes #400 
This enables [Preview Apps](https://hasura.io/docs/latest/graphql/cloud/preview-apps.html) for PRs made to this repo that modify the Hasura state. It will create an ephemeral database in the staging Postgres server and try applying any new metadata / migrations to it in order to verify correctness before merging the PR.
Since a PR may also make frontend changes that depend on changes to the Hasura instance, the Github action will also trigger a Vercel deployment that has the ephemeral Hasura instance configured as the GraphQL endpoint using the `REACT_APP_HASURA_URL` env var.
Once the PR is merged, the `delete-hasura-preview.yml` action will cleanup the ephemeral database and Hasura instance since it's no longer needed.
> Setup Hasura Cloud Preview with Github Actions

- src/components/FormFileUpload/FormFileUpload.tsx
Fixes bug #389 where choosing the same background image twice in a row doesn't work. This also fixes same for avatar and other future usages of `FormFileUpload`
> Fixing bug #389 - choosing the same background image twice in a row

- craco.config.js
- package.json
- yarn.lock
Along with enabling integrations in GitHub and Vercel, this change
allows for commits to be associated with deploys in sentry.io.
In local environments, including `vercel dev`, the webpack plugin
defaults to "dry run" mode and doesn't attempt to create a release or
associate commits in Sentry. Commits are only tied to a release in
the specified config when vercel deploys from the "production" branch
in this configuration.
Additional configuration is below.
Closes #413 
test plan:
The "production" branch head in https://github.com/topocount/coordinape
is currently throwing an error on pageload. That error is associated
with the tagged release (represented by the commit SHA) which is
associated with recent commits.
[These instructions](https://docs.sentry.io/product/integrations/deployment/v …
> Configure Webpack to create Sentry release and tag it in the Frontend

- src/components/ApeAvatar/ApeAvatar.tsx
- src/recoilState/app.ts
- src/recoilState/map.ts
fixes #417 
the `profile.avatar` is for some reason an empty string that's the reason why the map page is not loading the pfp.
A non-empty string validation for the avatar value.
```
const p = profile ?? user?.profile;
let avatar = p?.avatar;
if (avatar === '') avatar = user?.profile?.avatar;
```
PS. @zashton address the `profile.updated_at` is not updated like the `user.updated_at` 
@exrhizo it could be something about the recoil state profile object request here?
> Fixes pfp issue on map page

- src/forms/AdminEpochForm.tsx
fixes #473 
@reeserj reported a bug in Epoch Admin modal describing in the #473
`nextRepeat` date wasn't use zone `utc`, I reproduce locally changing my timezone to Tokyo 
@reeserj please try to reproduce with the vercel build
> adds utc zone to nextRepeat date on AdminEpochForm

- README.md
After doing a little research I found that Git for Windows converts LF to CRLF (and does the opposite when you push), so when you try to run the server locally the issue appears since the Docker is running WSL and the file has the line ending CRLF, I believe the way to solve the issue on windows is manually changing line endings for that file (coordinape/laravel/services/start.sh) from CRLF to LF. I solved the second problem just opening the localhost:3000/ instead of interacting with the one that pops up when you run vercel dev. Now my local environment is working 🎉
> Add msg to Troubleshooting

- src/components/ClaimCard/ClaimCard.tsx
This was an undesired change, that changes the color of the icon that originally is green
coming soon, a `svg` component styled with stitches to control `size` `color` through variants
> remove color of Arrow icon on ClaimCard

- src/lib/zod/index.ts
Sometimes, you don't want to automatically parse or validate admin
requests in a Hasura Action.
I tried to implement this case in the existing body parser factor but
ZodUnions don't easily compose statically at the parameter level. I
have a feeling discriminated unions will play much nicer.
> Create a body factory that accepts user session variables

- .github/workflows/hasura-preview.yml
This will stand up an ephemeral environment that works end to end with Hasura talking to the action handlers in the Vercel preview for a given PR, making it easy to test new frontend + backend functionality in a live environment before merging to main.
Effectively creates a temporary staging instance, allowing us to confidently deploy changes straight to prod as they are merged into main.
> Setup Hasura preview to point to Vercel preview for Action Handlers

- .env.example
- src/config/env.ts
- src/hooks/useApiWithProfile.ts
- src/services/api.ts
Follow the test plan from #547 to verify this works with laravel, but realy this needs to be tested in prod, which does not have hasura configured properly.
> restoring non-graphql endpoints and adding a HASURA_ENABLED env var to re-enable

- hasura/metadata/actions.graphql
- hasura/metadata/databases/default/tables/public_circle_integrations.yaml
- hasura/metadata/databases/default/tables/public_circles.yaml
- hasura/metadata/databases/default/tables/tables.yaml
- hasura/migrations/default/1644709890772_create_table_public_circle_integrations/down.sql
- hasura/migrations/default/1644709890772_create_table_public_circle_integrations/up.sql
Short demo of what a v1 of a Dework integration that uses circle integrations could look like: https://www.loom.com/share/b1bf242508f647a983c5a8b4c7d7c74e
This PR adds a new table `circle_integrations`. Circle admins can insert and delete integrations. Everyone can read circle integrations.
In a future PR I will make the frontend use this table to create integrations and read/show epoch contributions using integrations
> Circle Integrations: database table, migrations and permissions

- src/lib/zod/index.ts
Hasura doesn't always include request_query in the Action payload, setting to optional so it doesn't error when parsing the payload.
> Set request-query field to be optional

- api/hasura/actions/adminUpdateUser.ts
- api/hasura/event_triggers/refundPendingGift.ts
- hasura/metadata/databases/default/tables/public_pending_token_gifts.yaml
- hasura/metadata/databases/default/tables/public_users.yaml
- src/lib/gql/GqlHasuraAdmin.ts
I was really not a fan of my initial work on this and refactored it
in preparation for the non-admin `updateUser` action.
so:
- the separation of concerns is cleaner
- all accounting updates are atomic and clean
- it's still an nice idiomatic business logic event handler
Now all changes occur in a single transaction when a user is
updated to be non_giver or non_receiver. This includes refunds to or
from counterparties who have either given or received tokens from the
modifier user.
Additionally, no pending_gift or give_token accounting logic leaks
from this event handler. Anything related to GIVE token accounting
during and user updates is handled here.
test plan:
0. purge all seeded pending gifts for a chosen epoch from the pending_token
gifts table. If you don't do this, the accounting …
> Refactor refundPendingGift Event Trigger

- src/components/ProfileCard/ProfileCard.tsx
- src/hooks/useAllocation.ts
- src/pages/AllocationPage/AllocationGive.tsx
- src/recoilState/allocation.ts
1. wrap ProfileCard in React.memo
2. prevent ProfileCard's props from changing unnecessarily
- we can't pass updateGift from the useAllocation hook to ProfileCard, because it's redefined every time any user's allocation or note is changed, causing all ProfileCards to re-render
- instead, I created a new selectorFamily in order to give each ProfileCard a setter that's scoped to its user, so it only re-renders when its own user changes
> don't re-render all ProfileCards on every allocation change

- README.md
Seeding the db with the vercel dev stateless functions causes a ton
of database events to be thrown, which eats up the processor and a ton
of memory. Typical options when this happens include either (a)
restarting the machine or (b) waiting for the everything to pass.
This is obviously not a great solution, and a more resilient solution
should/could be implemented by refactoring the db-seed scripts to yield
sql-based hasura seeds, but this requires more discussion around what a
desirable seed script would be.
Test plan:
Try out this sequence for yourself and ensure your machine doesn't go
haywire.
> Quickfix for Seeding the DB

- api-lib/HttpError.ts
- api/hasura/actions/updateUser.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- src/lib/zod/index.ts
This endpoint itself doesn't handle any GIVE token accounting when `non_receiver` is
set from `false` to `true`. This is handled by the already-tested `PendingGiftRefund`
event trigger.
fixes #564
1. grab a token from the browser interface and add it in the hasura graphiql explorer
2. disable the `x-hasura-admin-secret` and enable your user-level `Authorization` header with the token as the payload.
3. Execute the following command and observe that all changes are set in the database:
```gql
mutation UpdateOwnUserTest {
Me: updateUser(payload: {
circle_id: 3
non_receiver: false
bio: "Yo wassup"
name: "Bob"
}) {
id
UserResponse {
address
non_receiver
bio
name
}
}
}
```
4. Observe the following return
```json
{
"data": {
"Me": {
"id": 603,
"UserResponse": {
"address": …
```
> Update own user

- api-lib/Gql.ts
- api-lib/HttpError.ts
- api-lib/event_triggers/refundPendingGift.ts
- api-lib/event_triggers/utils/handleVouchMsg.ts
- api-lib/event_triggers/vouchDiscord.ts
- api-lib/event_triggers/vouchTelegram.ts
- api-lib/findUser.ts
- api-lib/ts4.5shim.ts
- api/hasura/actions/adminUpdateUser.ts
- api/hasura/actions/createNominee.ts
- api/hasura/actions/updateUser.ts
- api/hasura/actions/uploadCircleLogo.ts
- api/hasura/actions/uploadProfileAvatar.ts
- api/hasura/actions/uploadProfileBackground.ts
- api/hasura/actions/vouch.ts
- api/hasura/event_triggers/eventManager.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/metadata/databases/default/tables/public_vouches.yaml
- src/lib/gql/__generated__/zeusAdmin/const.ts
- src/lib/gql/__generated__/zeusAdmin/index.ts
- src/lib/gql/__generated__/zeusUser/const.ts
- src/lib/gql/__generated__/zeusUser/index.ts
- src/lib/zod/index.ts
Fixes #519 by porting vouching to hasura. 
To test: 
1. have a bearer token set up in hasura console for a user in circle_id 6
2. run mutation for a user who is nominated but needs vouching. I used this: 
```
vouch(payload: {circle_id: 6, nominee_id: 61}) {
nominee {
address
ended
}
}
}
```
should return ended false
3. run again and should get a dupe error
4. go into sql or use a mutation to fudge the user id of the vouch, i ran `update vouches set voucher_id=607;` where my real userid is 606
5. run vouch mutation again, now ended should be true and user is in the circle (i just verified in DB cuz UI is giving me hell)
> Port Vouching to Hasura

- api/hasura/actions/adminUpdateUser.ts
The logic was unnecessarily complex so I cut those pieces out.
It is functionally identical, except it now doesn't touch the
give_token_remaining column if there is no change to make.
merge plan: merge to hasura-next after #590 is merged
> Small Simplication of the adminUpdateUser mutation

- src/components/ApeTextField/ApeTextField.tsx
- src/forms/CreateCircleForm.tsx
- src/pages/CreateCirclePage/CreateCirclePage.tsx
fixes #601 
This adds the Coordinape Discord support to the Create Circle and follow up the new design described in the #601.
> Add Discord Support to Creat Circle Form

- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/pages/CreateCirclePage/CreateCirclePage.tsx
- src/routes/paths.ts
After talking with Ivy, seems it's most helpful to send folks directly to our #support channel for errors and questions with onboarding, rather than just our entire Discord.
Creating both options on the site, linking to general Discord still on footer, but linking to #support channel from our error page and the "Create new circle" page.
> Link directly to Discord #support channel

- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/pages/CreateCirclePage/CreateCirclePage.tsx
While I was working on #606, I didn't make an accurate review for form's fields alignment, the reason for that is using `</a>` tag around `<Button>` component. 
Using `</a>` tag around `<Button>` introduced two visual bugs: 
- **blue underline** for links in Discord Support Button in **Create Circle Page** & **Give Feedback** in the menu. 
- **Misalignment** among some fields in **Create Circle Page** Form.
I found a better solution that solves both issues at once by using the `href` that comes included with the [`<Button>` API](https://mui.com/api/button/). This allows MUI to decide how to include the `</a>` tag, in addition, this is more concise and encapsulated than the old way.
This PR solves two issues at once.
Blue underline is showing in couple of places: Discord button in create …
> Fix misalignment in Form after adding Discord support & blue underline bug under links

- api-lib/gql/queries.ts
- api/hasura/actions/createCircle.ts
- src/lib/zod/index.ts
Laravel currently allows both parameters in the createCircle REST
endpoint and ignores the protocol name in the case where both are
present.
Our frontend currently supplies all parameters, even if no change has
been made. This change allows for compat with frontend behavior while
behaving more soundly if the name does not match the name of the
protocol id supplied. I've also updated the error message to be more
contextually helpful in this case.
test plan:
test cases where
1. no name is suppled: the endpoint should behave as before, and create
the circle if the protocol id points to and existing protocol
2. both are supplied and the name matches the existing protocol name:
the new circle should point to the existing protocol
3. both are supplied and the protocol name does not match the …
> createCircle Allows both protocol id and name inputs

- .github/CODEOWNERS
In the prior config, zashton's assignments to the same folders overwrote my assignments
on prior lines. This allows both of us to be assigned on all changes to the applicable
folders.
> Fix: topocount reviews on api and hasura PRs

- src/pages/AdminPage/AdminEpochModal.tsx
- src/pages/AdminPage/AdminPage.tsx
closes #443 
- Added description to the create epoch modal. Includes a link to the desired documentation per spec.
- Improved styling for the modal summary to match figma
- Changed button on admin page from `Add Epoch` to `Create Epoch` per figma
> Epoch Modal Description

- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
This got lost in this commit: https://github.com/coordinape/coordinape/commit/1e78d07105a923dcf56ca7c0ffb34378e62e049a
To test:
1. create a new epoch
2. go into hasura console and sort the epochs by highest id
3. note the id and circle_id
4. go to the API tab and run (substituting proper ids:
```
mutation MyMutation2 {
deleteEpoch(payload: {circle_id: 1, id: 191}) {
success
}
}
5. refresh the web page and note that the epoch is gone
6. 
```
> restoring deleteEpoch action that got lost in a bad merge

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- src/hooks/useApiAdminCircle.ts
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/gql/mutations.ts
- src/services/api.ts
Fixes #639 by migrating to hasura. 
Test plan:
1. Visit the admin page of a circle with an active epoch. In the fresh seed data Games in Collier and Sons. 
2. click the red trash next to the epoch on the top
3. click remove epoch button the dialog
4. observe that the epoch is deleted, but you have encountered bug #659 which is that the dialog does not dismiss. 
5. refresh the page to workaround #659
> migrate deleteEpoch FE to hasura

- src/pages/AdminPage/AdminPage.tsx
fixes #673
**Summary**
use  Intl.Collator('en-u-kf-upper') to compare the contributors names strings by English locale so that only strings that differ in base letters compare as unequal.
kf-upper: to sort upper case letters first
> Compare contributors names by English locale

- api/hasura/cron/_epochs.test.ts
Epoch test mocks are borked in main currently. I'm honestly not sure why
this issue wasn't tripped in the topic branch during tests, but now jest
mock state is leaking between tests, causing call traces to show up
across multiple tests. This is fixed by clearing the mocks before each
test.
test plan:
Ensure unit tests are passing in CI and locally if you want. This was
broken locally for me, as well as in main, once i pulled these changes
down after the PR was merged.
> bugfix: epoch test mock leaks

- src/components/ProfileCard/ContributionSummary.tsx
- src/components/ProfileCard/GiftInput.tsx
- src/components/ProfileCard/ProfileCard.tsx
- src/components/ProfileSkills/ProfileSkills.tsx
- src/hooks/useContributions.ts
Problem:
Users can't see the contribution summary/Dework tasks in Coordinape profile cards
> Dework integration: tightened up ProfileCard styling

- src/hooks/useAuthToken.tsx
- src/pages/DevPortalPage/DevPortalPage.tsx
- src/pages/DevPortalPage/index.ts
- src/routes/paths.ts
- src/routes/routes.tsx
- src/stitches.config.ts
- src/ui/Button/Button.tsx
Page is not accessible to general users from the main site navigation, you can only reach it by going to the /devPortal endpoint.
Clicking the link will take the users to a live GraphQL console where they can get their auth tokens and browse the schema / build queries and mutations + comes prefilled with an example query.
> Setup Dev Portal page to document GraphQL API access

- api/hasura/cron/dailyUpdate.ts
Adding the functionality of sending telegram daily updates to organisation level telegram so its in line with how it works previously (affects Yearn circles only)
> Add sending daily updates to organisation level telegram

- hasura/migrations/default/1648096542742_alter_table_public_profiles_add_check_constraint_valid_website/down.sql
- hasura/migrations/default/1648096542742_alter_table_public_profiles_add_check_constraint_valid_website/up.sql
This fixes #441 by obviating the need for a custom validation action. 
This includes migrations that fix existing rows that don't match this pattern. One side effect is the y.at emoji urls don't work. There were only 3 of them that weren't properly URL encoded, so they are cleaned up in this change explicitly. 
I tested this by importing a facsimile of the production data and running this migration. 
To test, run some mutations in the console that play around with variations on valid and invalid websites, e.g. 
```
update_profiles_by_pk(
pk_columns: {id: 2218},
_set: {website: "http://slurp.next.mock.google.com?moo#jack"}) {
id
website
}
}
```
> check constraint on profiles.website

- src/hooks/useAllocation.ts
- src/lib/gql/mutations.ts
- src/services/api.ts
Fixes #636 
To test,
1. Visit the Allocation page for a circle with lots of members
2. open the network tab
3. add some teammates and save
4. validate that the request goes to graphql instead of laravel endpoint
5. make sure it all works ok by adding and removing members
> fixes #636 by integrating update teammates graphql into FE

- .github/workflows/CI.yml
fix for an issue where the cache gets created with files in `node_modules/@coordinape/hardhat`, but then this directory doesn't exist when the cache is unpacked in the next run (probably because it's a symlink), so there are lots of errors logged. harmless but annoying
> CI cache fix

- src/hooks/useApiAdminCircle.ts
- src/lib/gql/mutations.ts
- src/services/api.ts
Fixes #642 
Test plan:
1. Visit a circle admin page. I used Health in Conn - Friesen because it has a lot of users. 
2. Open up the ol' network tab in the develop console
3. delete a user. I deleted Diego, because they were first.
4. note the network call is graphql, not laravel
5. note that the user goes away.
> fixes #642 by integrating deleteUser graphql into FE

- api-lib/gql/__generated__/zeus/index.ts
- hasura/migrations/default/1648856418818_alter_table_public_pending_token_gifts_alter_column_epoch_id/down.sql
- hasura/migrations/default/1648856418818_alter_table_public_pending_token_gifts_alter_column_epoch_id/up.sql
- src/lib/gql/__generated__/zeus/index.ts
Checked on prod that this will be ok by running this mutation:
```
query MyQuery {
pending_token_gifts_aggregate(where: {epoch_id: {_is_null: true}}) {
aggregate {
count
}
}
}
```
and got this result:
```
{
"data": {
"pending_token_gifts_aggregate": {
"aggregate": {
"count": 0
}
}
}
}
```
> make pending_gifts.epoch_id non-nullable

- src/hooks/useApiWithSelectedCircle.ts
- src/lib/gql/mutations.ts
- src/services/api.ts
Fixes #638 
Some notes here:
* the rest api was using some local state from `useApiWithSelectedCircle` to set the name, bio, etc, before applying the params. This resulted in setting the name to `Me` which doesn't make any sense, and breaks the server side validation rules of name being >3 chars. I'm not really sure what the intent was here but everything seems to work ok with removing this this stuff. 
* I don't know why name is in the params, its not really used for anything in the UI , so I'm not sure how to test it, and what the relation to `Me` is 
Test Plan:
1. Visit the My Epoch page for a circle 
2.  flip the opt-in settings and change your bio
3.  make sure settings are saved
4. make sure network request is to /graphql instead of laravel
> fixes #638 by integrating updateUser graphql into frontend

- api-lib/dateTimeHelpers.ts
- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api-lib/gql/queries.ts
- api/hasura/actions/updateEpoch.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/zod/index.ts
fixes #566 
and some refactoring of Create Epoch
1. run `yarn hasura console`
2. create an epoch with the mutation
```gql
createEpoch(payload: {circle_id: <circle_id>, days: <days>, repeat: 0, start_date: "2022-09-27T10:00:00"}) {
epoch{
id
circle_id
days
start_date
end_date
repeat
}
}
}
```
3. With the epoch `id` use it to run the update mutation and set it to any new values
```gql
updateEpoch(payload: {circle_id: <circle_id>, days: <days>, id:<id>, repeat: 0, start_date: "2022-08-27T10:00:00"}) {
epoch {
id
start_date
ended
end_date
days
repeat
repeat_day_of_month
}
}
}
```
4. Epoch now should be updated to the new values
5. You should not be able to
- overlap an existing epoch date
- have more than 1 repeating epoch that has not ended yet
- …
> Epoch Update Hasura feature 

- api-lib/gql/__generated__/zeus/index.ts
- hasura/migrations/default/1649222699929_alter_table_public_epoches_alter_column_updated_at/down.sql
- hasura/migrations/default/1649222699929_alter_table_public_epoches_alter_column_updated_at/up.sql
- hasura/migrations/default/1649222711646_alter_table_public_epoches_alter_column_start_date/down.sql
- hasura/migrations/default/1649222711646_alter_table_public_epoches_alter_column_start_date/up.sql
- hasura/migrations/default/1649222967344_fix_null_epoch_created_at/down.sql
- hasura/migrations/default/1649222967344_fix_null_epoch_created_at/up.sql
- hasura/migrations/default/1649223006624_alter_table_public_epoches_alter_column_created_at/down.sql
- hasura/migrations/default/1649223006624_alter_table_public_epoches_alter_column_created_at/up.sql
- src/lib/gql/__generated__/zeus/index.ts
This makes the zeus typing a lot nicer in the FE. I verified this was ok in the prod data, except for 7 rows that are covered by the UPDATE in this migration.
> making updated_at and start_date non-nullable on epoch

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api-lib/nominees.ts
- api/hasura/actions/updateAllocations.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/migrations/default/1649169600501_alter_table_public_pending_token_gifts_add_unique_sender_id_recipient_id_epoch_id/down.sql
- hasura/migrations/default/1649169600501_alter_table_public_pending_token_gifts_add_unique_sender_id_recipient_id_epoch_id/up.sql
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/zod/index.ts
fixes #568 
1. run `yarn hasura console`
2. Choose a circle with multiple users. Make sure you have an active epoch or else create one. Purge all the `pending_gift_token` dummy data for the circle. (this may cause lag as event triggers may fire off)
3. Run this mutation to test, change the allocation array as desired
```gql
updateAllocations(payload: {circle_id: <circle>, allocations: 
[{note: "thank you", recipient_id: <id>, tokens: 42},
{note: "no thanks", recipient_id: <id>, tokens: 15},
{note: "", recipient_id: <id>, tokens: 43},
{note: "hmmm", recipient_id: <id>, tokens: 11},
]
}) {
user {
id
give_token_remaining
pending_sent_gifts{
recipient_id
tokens
gift_private {
note
}
}
}
}
}
``` 
4. After allocating check the `users` and `pending_token_gifts` tables to …
> Create/update token & note allocations

- src/hooks/useApiAdminCircle.ts
- src/lib/gql/queries.ts
- src/services/api.ts
Fixes #757 
To test:
1. Go to admin page for a circle
2. open the settings modal
3. open the developer console network tab of browser
4. tap Edit Discord Webhook, verify that network hit is /graphql instead of laravel
5. save and change the webhook
6. refresh the page and reload and visit the edit webhook input again
7.  see that it loads the correct value
8. try changing it and reloading and such
> moving getDiscordWebhook to use graphql instead of laravel

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- hasura/metadata/actions.graphql
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/zod/index.ts
Fixes #725 
To test:
1. restart docker after updating
2. go to the hasura console
3. Run an updateUser mutation such as this and see that you can no longer specify name
```
updateUser(payload: {circle_id: 6}) {
UserResponse {
name
id
}
}
}
```
4. test update User ("my epoch" page) in the UI and make sure it still works
> removing name from updateUser input

- src/pages/AllocationPage/AllocationEpoch.tsx
The capitalization in the AllocationEpoch component should match the data source so I removed the capitalization of the string.
fixes #747
> Remove capitalization from AllocationEpoch component

- src/hooks/useAllocation.ts
Bug #463 fix: If opted out from give members are added to allocation team they will received give if auto redistribute button is clicked and the remaining gives will be negative.
fix:
Add a condition to rebalanceGifts to check if the user is opted in for receiving or not before distributing the balance if there is no weight is assigned to the receiver
> Exclude non receivers from auto reblancer

- src/hooks/useAllocation.ts
- src/lib/gql/mutations.ts
- src/services/api.ts
Fixes #637 
To test:
1. visit the allocation page for an open epoch
2. open the network tab up
3. make some allocations and write some notes
4. /graphql should be hit but not laravel
5. stuff should work ok and update ok
Note you can't clear out a note to test deletion of the gift entirely because of #753
> migrate postTokenGifts / updateAllocations to use hasura in frontend

- api-lib/gql/queries.ts
- api/hasura/cron/epochs.ts
fixes #777
It's possible to create overlapping epoch right now if the start and end
ISO timestamps are _exactly_ equal to an existing epoch.
This change fixes the issue, by checking for equality while still
allowing for a new epoch to start at the exact same time as an epoch
ends.
test plan:
Find an existing epoch and grab the start_date and end_date.
The problem can be replicated by in GraphiQL (http://localhost:8080)
by plugging the start and end date in
here:
```gql
epochs(where: {
circle_id: { _eq: <circle_id> },
_or: [
{
start_date: { _lt: <existing end_date> },
end_date: { _gt: <existing end date> },
},
{
start_date: { _lt: <existing start_date> },
end_date: { _gt: <existing start_date> },
},
],
}) {
id
circle_id
start_date
end_date
}
```
You'll notice that no overlapping epochs are …
> Bugfix: duplicated epoch entries in db

- package.json
- scripts/disable_cron.sh
- scripts/seed_hasura.sh
This script is intended for testing and development environments. It
disables cron tasks in a local hasura docker container without modifying
the repo metadata, which makes it sort of fix-and-forget. This has pros
and cons, but I don't think most devs want to be bothered with what's
happening with cron triggers when working locally anyhow.
This script has been inserted into package.json and the seed script as a
convenience.
test plan:
`yarn db-disable-cron`
@levity please ensure this works on macs
> Implement disable_cron script

- CONTRIBUTING.md
I added a lot of low-key opinionated ideas and concepts, but they're all
for the purpose of making the review process simpler, and believe these
are all practices we should be working towards.
It's worth noting that much of this is borrowed from SourceCred's
CONTRIBUTING doc, with the language softened a bit.
> Create a Contributing Doc

- api-lib/gql/__generated__/zeus/index.ts
- hasura/metadata/databases/default/tables/public_users.yaml
- hasura/migrations/default/1650344175374_set_fk_public_users_address/down.sql
- hasura/migrations/default/1650344175374_set_fk_public_users_address/up.sql
- src/lib/gql/__generated__/zeus/index.ts
Fixes #796 
See the issue for context. This deletes some rows and adds an FK that makes `user.profile` non-optional.
> Add  fk from users.address->profile.address

- api-lib/gql/mutations.ts
Currently, vouched users who don't already have a profile are failing to
be created due to the new fk contraint on addresses between profiles and
vouches. This fixes that problem by optionally creating a profile if one
doesn't exist in the same TX the user is created in.
test plan:
Run this in your local hasura console at http://localhost:8080:
```gql
mutation testCreateUser {
insert_profiles_one(
object: {
address: "0x88dCC3A3c55DD18D09aE7572424d22763f60B241"
}
on_conflict: {
constraint: profiles_address_key
update_columns: []
}
) {
__typename
}
insert_users_one(object: {
name: "Bobby",
address: "0x88dCC3A3c55DD18D09aE7572424d22763f60B241"
circle_id: 21 # or some circle_id that is valid
}){
__typename
}
}
```
Verify that the user is created and the profile is created.
Run it again with a …
> bugfix: new users cannot be created from a vouch

- hasura/migrations/default/1650588140371_add_users_profile_exists_trigger/down.sql
- hasura/migrations/default/1650588140371_add_users_profile_exists_trigger/up.sql
to test:
1. most cases have this handled in code, but vouching does not
2. vouch for a nominee with enough vouches that it converts to a user and doesn't throw a graphql error
3. also also adding a contributor to a circle doesnt throw an error
> adding a trigger to make sure that profile exists before user is updated

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api/hasura/actions/createUsers.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/zod/index.ts
Resolves #775
related: #708 #508 
____ 
It's similar to #508 in logic but in bulk action: new users will be inserted and soft-deleted users will be restored. 
1. Prepare a list of new users you want to add. 
2. Soft delete single/some users and add them to the list. 
3. Try the following,
```gql
mutation {
createUsers(payload: {circle_id: 6, users: [
{address: "0xac0D5FD72BD52B55Fb559eee0Fb3A0638f73AdaD", name: "New User 01"},
{address: "0x7FEA962EC07B7beA2c94672C8DA7ece097a2Af0a", name: "New User 02"}
]}) {
name
id
fixed_non_receiver
circle_id
starting_tokens
}
}
```
4. verify that new users is added and existing users is restored again, also nomination is ended & 'give_token_remaining` is updated if provided.
> Implement createUsers in bulk Hasura action

- src/components/ReceiveInfo/ReceiveInfo.tsx
closes: #835
____
The received dates from the database values are ISO 8601 format
example: `2022-04-26T12:13:25.976896`.
when using `DateTime.fromSQL()` the luxon library gives this explanation: 
```
reason: 'unparsable',
explanation: `the input "2022-04-26T12:13:25.976896" can't be parsed as SQL
```
> Fix `DateTime` format in receive Info summary

- api-lib/event_triggers/refundPendingGift.ts
- api-lib/gql/queries.ts
Fixes #829 
Fixes #817 
issue was `getUserByIdAndCurrentEpoch` was not fetching deleted users
changed to `getUserByIdAndCurrentEpoch` so it would target the right user regardless if its deleted or not.
this issue is leaving quite a bit of bad data that i had to manually fix. you won't be able to access your page if the deleted user sent to you or you received gives from him.
> Fixes the refunding issue #829

- src/pages/AssetMapPage/AMForceGraph.tsx
- src/recoilState/map.ts
- src/types/graph.d.ts
fixes #733 
Make edge thickness a factor of node diameter
add `minZoom` to `ForceGraph2D`
remove unnecessary `nodeRelSize` 
Accoriding to `force-graph` `linkWidth` [docs](https://github.com/vasturiano/force-graph) : _link widths remain visually constant through various zoom levels, where as node sizes scale relatively._
so it is not possible to make the link width resisable as the nodes diameter
My suggested solution made link width a factor of 80% of the node diameter multiplied by 3 and minZoom is set to 3 so that users can't zoom out until link width is greater than circle width.
1- Active Epoch with multiple opt-in users
2- Set yourself 1000  gives
1- allocate to a user 500 and distribute the rest to the other users
Node edges width should be visible correctly and max width shouldn't …
> Make edge thickness a factor of node diameter

- api/hasura/actions/adminUpdateUser.ts
- api/hasura/actions/createUser.ts
- api/hasura/actions/createUsers.ts
- api/hasura/actions/vouch.ts
- hasura/metadata/cron_triggers.yaml
- hasura/migrations/default/1651000685281_alter_table_public_users_add_unique_address_circle_id_deleted_at/down.sql
- hasura/migrations/default/1651000685281_alter_table_public_users_add_unique_address_circle_id_deleted_at/up.sql
Fixes #833
1. Create a nominee
2. Create a user with the same address but different name (or update a user to the same address)
3. Make sure nomination has ended and you cannot vouch for the user anymore
4. Ensure `checkNominee` cron job is running
5. Check for DB conflicts run:
```sql 
SELECT address, circle_id, deleted_at
FROM public.users
group by address, circle_id, deleted_at having  count(*) > 1;
```
> Fix for duplicate address issue

- src/hooks/useContracts.ts
- src/lib/vaults/contracts.ts
- src/pages/HistoryPage/HistoryPage.tsx
- src/pages/HistoryPage/getHistoryData.ts
- src/utils/connectors.ts
The Vaults aren't on mainnet yet, so we need to support the history view without them. I also added some code to index and lookup chainIds as strings, since a supported chainId of String type would fail to resolve a successful lookup.
test plan:
set your network to mainnet and browse to http://localhost:3000/history after authenticating and seeding the database.
I also ensure my changes typecheck and unit tests pass.
> Bugfix: allow for falsy core contracts in History

- api-lib/gql/queries.ts
- api/hasura/actions/createEpoch.ts
With the update to Zeus, luxon datetimes are no longer stringified
automatically.
I combed the repo for places where datetimes aren't stringified but it
might be worth another look from @zashton
test plan:
1. `vercel dev` on a seeded DB
2. browse to http://localhost:3000/admin/circles
3. click create epoch and attempt to submit a valid, non-overlapping
epoch. It should submit successfully, without error.
> Bugfix: stringify luxon datetimes

- api-lib/gql/queries.ts
- api/hasura/actions/deleteEpoch.ts
- src/hooks/useVaultFactory.test.tsx
- src/utils/testing/mocks.ts
this is the same problem as #893
I scanned for all Date() instantiations in our code and have stringified
them to ISO times where appropriate.
test plan:
1. vercel dev on a seeded DB
2. browse to http://localhost:3000/admin/circles
3. click create epoch and attempt to submit a valid, non-overlapping
epoch.
4. delete the epoch and ensure it deletes properly
> bugfix: fix delete epoch in frontend

- api-lib/nominees.ts
CreateNominee had and invalid parameter and DateTimes were not
stringified
test plan:
attempt to create a nominee in the frontend, in the Vouching interface.
> bugfix: createNominee

- scripts/generate_zeus.sh
Some *NIX flavors don't have TMPDIR set, so I've set a fall back for the
classic Nix /tmp public dir.
test plan:
unset TMPDIR && yarn generate
> bugfix: fallback for unset TMPDIR vars

- .env.example
When I was going through the [Quick Start](https://github.com/coordinape/coordinape#quick-start) there was the following error when running `yarn db-seed-fresh`:
```
➜  coordinape git:(main) ✗ yarn db-seed-fresh
yarn run v1.22.18
$ scripts/seed_hasura.sh --clean
scripts/seed_hasura.sh: line 11: export: `token>': not a valid identifier
error Command failed with exit code 1.
```
Change the value of `TELEGRAM_BOT_TOKEN` in `.env.example` so that the script `seed_hasura.sh` can run without parsing errors.
N/A
Make the quick start smoother
Ran `yarn db-seed-fresh` after the change and it works as expected.
> fix: Value of `TELEGRAM_BOT_TOKEN` in `.env.example`

- api-lib/config.ts
- package.json
Vercel doesn't utilize the project's configured "build command" for
serverless functions, and the backend now needs access to the
deployment.json file. The postinstall script is a lightweight way to
address this. It also potentially allows us to simplify the build command
in vercel to dedup the effort of linking to the protocol repo.
test plan:
```sh
rm -rf node_modules
git submodule deinit --all
yarn --frozen-lockfile
yarn docker:start
vercel dev
```
browse to http://localhost:8080
Run the following mutation:
```gql
createVault(payload: {chain_id: 10, org_id: 10, vault_address: "0x0"}){
id
}
}
```
If you get a zod error, that means the deployment.json file resolved
correctly
> Vercel fixes for serverless

- hasura/metadata/databases/default/tables/public_circle_api_keys.yaml
- hasura/metadata/databases/default/tables/public_circles.yaml
- hasura/metadata/databases/default/tables/public_epoches.yaml
- hasura/metadata/databases/default/tables/public_nominees.yaml
- hasura/metadata/databases/default/tables/public_pending_token_gifts.yaml
- hasura/metadata/databases/default/tables/public_profiles.yaml
- hasura/metadata/databases/default/tables/public_users.yaml
- hasura/metadata/databases/default/tables/tables.yaml
- hasura/migrations/default/1652767682611_create_circle_api_keys_table/down.sql
- hasura/migrations/default/1652767682611_create_circle_api_keys_table/up.sql
- hasura/migrations/default/1653094730989_set_fk_public_circle_api_keys_circle_id/down.sql
- hasura/migrations/default/1653094730989_set_fk_public_circle_api_keys_circle_id/up.sql
- hasura/migrations/default/1653094829404_set_fk_public_circle_api_keys_created_by/down.sql
- hasura/migrations/default/1653094829404_set_fk_public_circle_api_keys_created_by/up.sql
Sets up a new `circle_api_keys` table to store circle-scoped API keys with granular permissions + sets up relationships and permissions for the new `api-user` role.
For review, should ensure the configured permissions are appropriate for each given scope and that we aren't leaking anything critical.
related: #887
> Circle API Keys and api-user role

- .github/pull_request_template.md
Add a PR template
N/A
When contributors create a PR, it would be very helpful to have a starting point when creating the PR description. It's also extremely valuable for future reviewers to have some context on the PR so that it's easier for them to review. Furthermore, the call for screenshots is nice when there are UI changes so that the reviewer can see the result of the changes without having to run the app.
In all the projects and companies that I have worked with, and it has been extremely useful.
> feat: Add PR Template

- src/forms/AdminUserForm.tsx
- src/forms/CreateCircleForm.tsx
- src/lib/zod/index.ts
- src/pages/VouchingPage/NewNominationModal.tsx
fixes #944
Trim names strings before comparing the length.
For edit circle Modal the validation is done at src/lib/zod/index.ts because there is no validation at the modal.
1- Go To Vouching Page
2- Nominate A new user
3- Enter a nominee name that has only white-spaces or white-spaces around one or two letters.
the name shouldn't be accepted 
1- Go To Admin Page
2- Add a new contributer
3- Enter a user name that has only white-spaces or white-spaces around one or two letters.
the name shouldn't be accepted 
1- Go to Admin Page
2- Edit the circle
3- Replace the circle name with empty spaces
The name shouldn't be accepted
1- Go to Admin Page
2- Create a new circle with white space names
@levity @CryptoGraffe @topocount 
#944
> trim name strings before checking the length

- api-lib/authHelpers.ts
- api/hasura/actions/generateApiKey.ts
- api/hasura/auth.ts
- hasura/metadata/actions.graphql
Allows requests with circle API keys to be authenticated by the Hasura auth handler
Assign api-user role in Hasura auth handler if an API key is passed in
1. Generate an API key by calling the generateApiKey action
2. Make a request to the `/api/hasura/auth` endpoint with the Authorization header set to `Bearer <apiKey>`
3. Ensure it returns `api-key` for the role and the correct circleId
@topocount @zashton 
#887
> Handle circle API keys in auth handler

- hasura/metadata/databases/default/tables/public_teammates.yaml
this dramatically improves the perf of the getFullCircle query for large circles
> change teammates permissions so you can only see your own teammates

- api-lib/gql/queries.ts
- api-lib/handleOptOutMsg.ts
- api-lib/handleRefundGiveMsg.ts
- api/hasura/cron/epochs.ts
- src/pages/AdminPage/AdminCircleModal.tsx
- src/pages/AdminPage/AdminEpochModal.tsx
- src/pages/AdminPage/AdminUserModal.tsx
- src/pages/AllocationPage/AllocationEpoch.tsx
- src/pages/DistributionsPage/AllocationsTable.tsx
When a user changes the GIVE token name there were a few places were we were hardcoding "GIVE", it should be dynamically set depending on the circle's token name.
Change the places where "GIVE" was hardcoded to use the token name from the circle.
Ran the app locally and saw the change for most of them, not totally sure how to test the following:
* api-lib/handleRefundGiveMsg.ts
* api-lib/handleOptOutMsg.ts
* api/hasura/cron/epochs.ts
Before
After
Before
After
After
After
After
Closes https://github.com/coordinape/coordinape/issues/924
> fix: Use circle token name instead of hardcoded GIVE

- src/ui/Button/Button.tsx
Issue: Icon for upload new org image was "missing"
Fix: adjust padding/margin that was pushing the icon off the background.
> Navbar bugfixes

- api-lib/authHelpers.ts
- api-lib/findUser.ts
- api-lib/nominees.ts
- api/hasura/actions/updateAllocations.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- src/lib/zod/index.ts
Since we use custom actions for updating user allocations, we need to adjust the auth and business logic in the action handler to account for API keys that have the `update_pending_token_gifts` permission.
Created a new action request body validator for testing if API keys have certain permissions in a standardized / explicit way.
1. Create a circle API key with the `update_pending_token_gifts` permission
2. Use the API key to call the `updateAllocations` mutation for that circle and ensure it succeeds
3. Call the same mutation but for a different circle and ensure it fails.
4. Create another circle API key without the `update_pending_token_gifts` permission
5. Use the API key to call the `updateAllocations` mutations and ensure it fails.
@topocount 
#887
> Allow Circle API keys to call updateAllocations action

- src/components/ApeAutocomplete/ApeAutocomplete.tsx
Organization Name is missing the grey background for it's text box when creating a circle, this was introduced as part of the work for https://github.com/coordinape/coordinape/pull/914 which required a new styling for the `ApeAutocomplete`
Only change the `ApeAutocomplete` styling when it's a select (in the map) 
Ran locally and saw the correct style being applied
@levity @crabsinger 
Closes https://github.com/coordinape/coordinape/issues/1019
> fix: Change styling only when is select

- src/pages/AssetMapPage/AMDrawer.tsx
Follow up on https://github.com/coordinape/coordinape/pull/1032
Add missing `isSelect` prop
> fix: Add isSelect prop to the select in map

- api-lib/ImageUpdater.ts
- src/components/OrgLogoUpload/OrgLogoUpload.tsx
fixes #990
throw an error in ImageUpater.ts if an invalid format is provided.
Add a snackbar to show the error in OrgLogoUpload.tsx
Stop the loading modal and revert to the previous image
1- create a text file and change the format to jpg or png
2- choose the file and try to upload it to hasura
Expected:
A snackbar should be displayed and the previous image should be redisplayed
> Handle bad image upload errors on OrgLogoUploader

- src/icons/ParcelIcon.tsx
- src/icons/index.ts
- src/pages/AdminPage/AdminIntegrations.tsx
Add a "Pay with Parcel" button to the site under the integrations section so users can know we support an integration with Parcel.
Added a button that links to our Docs page for the Parcel Integration.
Ran locally, observed the button and clicked on it
https://github.com/coordinape/coordinape/issues/985
> feat: Add "Pay with Parcel" Button setting under Integrations

- src/pages/AdminPage/components.tsx
Epochs's `calculatedDays` wasn't perfectly rounded, ex:  `7.000000405092592`.
> Fix Epoch's day format in Epochs Table

- api-lib/config.ts
- api-lib/contracts.ts
- api-lib/provider.ts
Using hardhat dependencies via npm link or npm imports in our backend as local dependencies doesn't work in the vercel serverless environment.
This changes those imports to a relative path, which is a bit course and inelegant, but bypasses the complexity of configuring a local npm dependency. This can be reverted if/when we publish our hardhat dep on the registry or migrate to a monorepo.
Make sure vault deployments work in staging!
> Goerli prep and Vaults endpoint bugfix

- cypress/integration/createVault.ts
- cypress/util/index.ts
We want to avoid hard-coded ethereum accounts wherever possible to
make tests more resilient and agile. This also makes it easier to
access other accounts from the seed phrase when needed.
cypress e2e tests should pass
> Move hardhat account in cypress to a variable

- src/components/MainLayout/MainHeader.tsx
- src/components/MainLayout/MainLayout.tsx
- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/components/OverviewMenu/OverviewMenu.tsx
- src/components/OverviewMenu/getOverviewMenuData.ts
- src/hooks/login.tsx
The query to fetch data for the overview menu was running before login was completed.
The key piece of state determining when a user has logged in (i.e. has submitted a valid signature & gotten an auth token) was in the RequireAuth component in MainLayout. This piece of state was hoisted into a Context and a hook was created so that it could be read in `useOverviewMenuQuery`
- Confirm that the login flow still functions by logging in and out, canceling signature, etc.
- After logging out, reload the browser. You should not see any "auth token not set" messages in the console, and after logging in, the overview menu should be populated with your circles.
> Login before overview data fetch

- src/components/ProfileCard/GiftInput.tsx
As the beginning of building feedback tooling into our product, the first
change entails a link to our Guide to Giving feedback in Web3
It's just a static tooltip that links to our blog. I've left the opener and
referrer rel setting as the default in case webflow utilizes that in its
tracking info. Glad to set rel="noopener noreferrer" if that is safer for folks.
Review the screenshot, ensure all tests pass. This is a really simple change.
@AlexDistill
> Implement Tooltip link to Feedback Guide

- src/hooks/useContributions.ts
- src/pages/IntegrationCallbackPage/IntegrationCallbackPage.tsx
Multiple DAOs, incl Aragon, have asked for only showing Dework tasks from a specific space in Coordinape. For example, some DAOs use Dework for multiple guilds but have a guild specific Coordinape circle. Then it wouldn't make sense to pull in tasks from all guilds, but rather only for the specific guild that the circle is about.
This PR adds config to save Dework `workspaceIds` as part of the Dework integration. For existing integrations, or DAOs that don't want to only sync specific spaces, the integration will keep working as it does now.
No breaking change, so should be able to just deploy. Please let us know when deployed so that we can inform DAOs that have asked for this and roll out our frontend changes related to exposing this in the Coordinape/Dework connection UI on our end
N/A …
> Dework integration: only query tasks from specific workspaces

- src/hooks/gql/useVaults.ts
- src/hooks/useVaultFactory.ts
- src/pages/DistributionsPage/DistributionsPage.tsx
- src/pages/VaultsPage/CreateForm.tsx
- src/pages/VaultsPage/VaultsPage.tsx
- src/ui/Icon/Icon.tsx
- src/ui/index.ts
Minor bug fixes around vault UX
- Changed the useVaults query to use chainID
~- Changed distribution page to show the summary page if trx_hash is set. Previously, a rejected on-chain transaction would show up as completed.~
- Changed the CreateForm to disable the loading icon if a vault is not created successfully
None are required.
> Vaults UX Improvements

- hasura/migrations/default/1656710520327_vault_tx_types/up.sql
The chosen number is a pre-app testing block on goerli In order
to accomodate existing vaults in our backends.
This schema will be fully baked on mainnet and this default should be
removed after we go live.
Test Plan
The hasura migration should apply successfully in prod and staging
> bugfix: add default number to deployment_block column

- src/pages/HistoryPage/CurrentEpochPanel.tsx
- src/pages/HistoryPage/EpochForm.tsx
- src/pages/HistoryPage/HistoryPage.tsx
implements #1138 - Fixes an issue regarding the Editing Form where the form remains open if the user switched to another circle.
1- Add Edit button to current Epoch if the user is Admin.
2- Disable editing start date and start time in EpochForm for current Epoch.
3- The validation is between current epoch and future epochs if not empty
3- Bypass comparing between start date and current time for current epoch.
1- Tested editing current epoch with and without Available upcoming epochs.
2- Retested adding new epochs and editing next epochs.
Admin
Regular user
> Allow Editing Current Epoch

- src/pages/CirclesPage/CirclesPage.tsx
resolves #1010 
Sort circles by membership (am I in the circle, and then alphanumerically.
> fixes #1010 - sort overview by [membership, alphanumeric]

- src/pages/CreateCirclePage/CreateCirclePage.tsx
When a user who is not a part of a circle tries to create a new circle, they create button is not responsive
There was an issue regarding the input field of protocol(org) name
The control props was not added to the input field in the condition of a user is not part of an org.
Use a new wallet and try to add a circle
The form should be done by react hook-form but this is a quick fix for a current issue
> Fix adding a new circle as a new user

- hasura/migrations/default/1658458629766_alter_table_public_users_alter_column_non_receiver/down.sql
- hasura/migrations/default/1658458629766_alter_table_public_users_alter_column_non_receiver/up.sql
- src/pages/AllocationPage/AllocationEpoch.tsx
These changes make it easier for users to opt in and for circle creators
to onboard a circle faster.
First, created users used to be opted out upon creation, and had to opt
in during their first epoch to begin receiving GIVE. Now they are
opted in by default in our app, and there is no longer this chicken and
egg issue of users opting in and having no one to GIVE to because others
are not opted in.
Second, the UI now has the Opt-in radio button selected on every page
load. This makes it easier to opt in, and the user is now required to
explicitly opt out before receiving give.
Test plan:
E2E tests should still pass and unit tests still pass
Related Issue:
closes #1162
> Opt In Quality of Life Improvements

- hasura/metadata/databases/default/tables/public_token_gifts.yaml
Allows API keys with read epochs + read allocations permission to read historical token gifts.
Users of the API were not able to get historical allocation data.
Adds Hasura permissions for api-user role to read from token_gifts table.
Fetch token gifts using api-user role.
> Fix api-user permissions for historical token gifts

- hardhat/deploymentInfo.json
- hardhat/dist/deploymentInfo.json
- src/lib/vaults/tokens.ts
- src/pages/VaultsPage/WithdrawModal.tsx
This initially only worked soundly for USDC (6 decimals) and now works
soundly for ERC20s of any decimal amount by rounding up by 0.0001 to
check if the total balance is meant to be withdrawn
The submit button is now disabled when input contains a zero value
This fixes the MockVault issue where they become underfunded as deposits
roll in because they aren't minting enough yv tokens to CoVaults upon
deposit, causing the deposited DAI/USDC to become unrecoverable
> Withdraw fixes

- src/pages/VaultsPage/VaultTransactions.tsx
Prior behavior: navigating away from the app in the same tab.
> Open etherscan links in new tabs from tx list

- hardhat/deploymentInfo.json
- hardhat/dist/deploymentInfo.json
This points to a fixed MockVault setup, which was deployed in an earlier commit
> Redeploy protocol to goerli

- src/components/HelpButton.tsx
Fixes #1180 by using updated link from @ivyquinzel
> fix: 1180 - fixes the calendly link for schedule a walkthrough to use the hosted page

- package.json
- src/components/HelpButton.tsx
- src/components/MainLayout/MainHeader.tsx
- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/routes/paths.ts
- yarn.lock
Fixes #1104 by moving Docs and Feedback links to help button and changing to typeform for feedback. 
Also cleans up links by using constants. 
Does not include embedding TypeForm in a modal as asked in original ticket. This should not be merged until that discussion is resolved.
> move docs/feedback to help button and link to typeform

- src/lib/vaults/tokens.ts
`getWrappedAmount` can't handle decimal amounts , which causes errors for various flows in the app.
fixes
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=50e754b48e3f45fdbf46f50888baee6c&pm=s
> Fix get wrapped amount with decimals

- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/components/OverviewMenu/OverviewMenu.tsx
- src/stitches.config.ts
- src/ui/Panel/Panel.tsx
* goodbye 12px padding/margin, long live 16px
* Remove `$2sm` implementation of 16px in favor of `$md`, which was previously 12px
Figma is basically only using 4, 8, 16, 24, 32, 40, so I'm removing the 12px option that was set for $md.  I think there were some 12px margins in Figma at one time, but not currently, it seems.
Here's our key:
```
const spaces = {
xs: '4px',
sm: '8px',
md: '16px',
lg: '24px',
xl: '32px',
'1xl': '40px',
'2xl': '48px',
'3xl': '60px',
};
```
> Padding refactor 👎12px ... 👍16px

- src/pages/DistributionsPage/DistributionForm.tsx
This any type was passing a number into an ethers utility function that
only handles strings.
Added correct typings and stringified the value where appropriate
test plan:
createVault E2E Tests should pass reliably again
> BugFix: stringify distribution number inputs

- src/pages/DistributionsPage/AllocationsTable.tsx
- src/pages/DistributionsPage/DistributionForm.tsx
- src/pages/DistributionsPage/DistributionsPage.test.tsx
- src/ui/Text/Text.tsx
1. Fixed distribution button state when toggling Fixed Payment token in Circle settings page without refreshing
2. Fixed distribution button state when changing fixed payment amounts for circle users in Admin page without refreshing.
3. Button now displays `Please input token amount` instead of `Insufficient Tokens` when the total is zero for a combined distribution or if the respective input is zero for a non combined distribution
Fixes 
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=da39ef02747f4f2e8998941d27ccc029&pm=s
> Fix edge cases for distribution page button state

- hasura/metadata/databases/default/tables/public_claims.yaml
Insert: Should only be able to create a claim of a given distribution ID if you are the owner (creator) of that distribution.
Update: you can only update your own claims.
> Update Claim perms

- src/hooks/useVaultRouter.ts
- src/lib/vaults/distributor.test.ts
- src/lib/vaults/distributor.ts
- src/pages/DistributionsPage/useSubmitDistribution.test.tsx
- src/pages/DistributionsPage/useSubmitDistribution.ts
- src/utils/testing/mint.ts
Fixes [this QA report in Notion](https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=456bcb22b03f4a148e6d1db45b01d376&pm=s)
we weren't setting tapType and tokenAddress correctly in the call to uploadEpochRoot
this fix also encapsulates that logic into lib/vaults/distributor & adds tests for simple token & yearn token distribution
those tests can serve as a nice reference for the basic JS API we've made for vault operations, sans all the React- & UX-related stuff
> fix simple token distribution

- .github/workflows/CI.yml
- cypress/e2e/allocate.cy.ts
- cypress/e2e/updateUser.cy.ts
- scripts/ci.sh
remove unnecessary step from allocation test
remove a test from updateUser.cy.ts that is not so high-value
make the Cypress tests faster
> minor cypress test speedup

- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/pages/ClaimsPage/ClaimsNavButton.tsx
- src/pages/VaultsPage/VaultRow.tsx
- Always show the claims button but change the color of the button, show green when claims are available and blue otherwise.
- Deactivate Vault deposits for non-owners
> Show Claims and Deactivate Vault Deposit for non-owners

- cypress/e2e/createUser.cy.ts
- cypress/e2e/updateUser.cy.ts
- src/components/DeprecatedFormTextField/DeprecatedFormTextField.tsx
- src/components/FormTokenField/FormTokenField.tsx
- src/pages/AdminPage/AdminUserModal.tsx
- src/pages/CircleAdminPage/CircleAdminPage.tsx
- src/pages/DistributionsPage/DistributionForm.tsx
Number form fields that use `<DeprecatedApeTextField` faced an issue where the initial input value of `0` could not easily be deleted.  
* Fix leading-zero bug
* Set some number only fields to `type="number"`
* Fix vouching input field bug
> 🪲 Bugfix for Undelete-able zero in input field

- package.json
- src/components/HelpButton.tsx
- yarn.lock
Fixes #1193  This is a cleaner workflow than adding a new tab and was requested by @ivyquinzel 
The Help button "Share Feedback" link was opening a new tab, now it opens a typeform native sort of embed thing. 
Try helpButton->Share feedback on desktop and mobile
> moving typeform to an embedded form instead of a new tab

- scripts/db_clean.ts
this was just an oversight in the db_clean script when this new table was added
> delete api key table when seeding fresh

- hasura/migrations/default/1659968853380_fix_distribution_json/up.sql
- src/pages/ClaimsPage/hooks.ts
- src/pages/ClaimsPage/useClaimAllocation.test.tsx
- src/pages/DistributionsPage/mutations.ts
- src/pages/DistributionsPage/useSubmitDistribution.test.tsx
- src/pages/DistributionsPage/useSubmitDistribution.ts
The `distributions.distribution_json` column is being stored as a giant plain-text string instead of JSON, even though the database table type is already `jsonb`.
This was a compromise when the feature was initially implemented due to lack of support from Zeus, but Zeus's support improved.
- store and read the `distribution_json` column as JSON
- add a migration to convert existing column values
----
This is based off of `recover-distributions` because that has lots of related changes; will rebase once #1232 is merged.
> store distribution_json properly

- src/pages/ClaimsPage/ClaimsPage.tsx
- src/pages/ClaimsPage/mutations.ts
- src/pages/ClaimsPage/useClaimAllocation.ts
- src/ui/Avatar/Avatar.tsx
Claims Page Improvements
- add circle logo to UI
- edgecase-fix: only update older claims:
If you load the FE, and get claims 1,2,3. And then while on that page a claim 4 is created, claiming 3 would cause claim 4 to be marked as claimed erroneously. This fixes that edge case.
> Claims Improvements

- src/components/DeprecatedApeTextField/DeprecatedApeTextField.tsx
* DeprecatedApeTextField: remove input class that is causing padding doubling `className={classes.input}`
> bugfix: input double padding removal on DeprecatedApeTextField

- api/login.ts
Resolves Issue #1242
See #1253 for issues around supporting Gnosis safes, which explicitly does not support eip 1271 right now.
Attempt to autheniticate in our frontend using Argent or some other smartphone wallet that utilizes walletconnect and supports eip 1271.
closes #1242
> bugfix: Support EIP-1271 in the SIWE api

- src/pages/ClaimsPage/ClaimsPage.tsx
- src/pages/ClaimsPage/queries.ts
- src/pages/ClaimsPage/useClaimAllocation.test.tsx
- src/pages/ClaimsPage/utils.ts
- Add tooltips with details of underlying distributions grouped into a claim
screenshots:
- Rename "Epochs" to "Distributions" in the table.
> Claims page UI Improvements (tooltip and rename)

- cypress/e2e/createVault.cy.ts
- src/components/FormTokenField/FormTokenField.test.tsx
- src/components/FormTokenField/FormTokenField.tsx
- src/pages/DistributionsPage/DistributionForm.tsx
- src/pages/DistributionsPage/DistributionsPage.test.tsx
- src/pages/DistributionsPage/DistributionsPage.tsx
- src/pages/VaultsPage/DepositModal.tsx
- src/pages/VaultsPage/WithdrawModal.tsx
- src/utils/index.test.ts
- src/utils/index.ts
FormTokenField was handling token decimals incorrectly. This fix makes
it impossible to enter a value with more decimals than a token has
available. The amount will remain at the value with the smallest
possible decimal. If a user pastes in a value with more decimals than is
can be handled, the amount is truncated to the valid decimal quantity.
Additionally, this refactor removes that annoying thing where the field
can't be empty and you need to "type around" a placeholder zero.
Validation treats empty fields correctly in my testing on deposits,
withdraws and distributions.
This change also led to an upstream refactor to move all calculations
away from Numbers and to BigNumbers in all views that consume
FormTokenField.
Test Plan: unit and E2E tests should pass.
> Fix FormTokenField Decimal Handling

- src/components/FormTokenField/FormTokenField.test.tsx
- src/components/FormTokenField/FormTokenField.tsx
This used to throw an error when the string was parsed into a BigNumber.
Now it just short-circuits and doesn't attempt to parse.
> bugfix: FormTokenField handles empty strings

- .env.example
- scripts/util/eth.ts
Allow option to read dev seed phrase from ENV
Parse out dashes as workaround for bash's handling of spaces
@topocount
> Allow option to read dev seed phrase from ENV

- src/pages/HistoryPage/HistoryPage.tsx
- src/routes/paths.ts
- src/ui/HintBanner.tsx
Implementing some help banners for new members and admins on the epoch overview page. 
New HintBanner component and helper text and buttons on the epoch overview page. 
1. Create a new circle and visit the overview page. make sure the links work on the new banner
2. Start an epoch and the help should go away 
3. join a circle as a new member
4. there should be a help banner. make sure the links work on the new banner
Fixes #1008
> Get started banners for epoch overview page for admins and non-admins

- package.json
- scripts/ci.sh
- yarn.lock
The latest versions of vercel are migrating from --confirm to --yes
and are kind of buggy, since the flag doesnt seem to bypass all prompts
like confirm used to.
This change pins us to a version that works as we've come to expect and
will get CI back to working reliably
test plan: CI tests should start working again
> Pin Vercel in our repo

- src/hooks/gql/useVaults.ts
Verifying this redundent check isn't necessary
> Remove redundant vault check

- api/hasura/actions/_handlers/createUsers.ts
- cypress/e2e/createUser.cy.ts
- cypress/e2e/updateUser.cy.ts
- src/config/features.ts
- src/lib/zod/index.ts
- src/pages/AddMembersPage/AddMembersPage.tsx
- src/pages/AddMembersPage/CopyCodeTextField.tsx
- src/pages/AddMembersPage/NewMemberEntry.tsx
- src/pages/AddMembersPage/NewMemberGridBox.tsx
- src/pages/AddMembersPage/NewMemberList.tsx
- src/pages/AddMembersPage/TabButton.tsx
- src/pages/AddMembersPage/useCircleTokens.ts
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AdminPage/AdminUserModal.tsx
- src/pages/AdminPage/components.tsx
- src/pages/DistributionsPage/DistributionsPage.tsx
- src/routes/paths.ts
- src/routes/routes.tsx
- src/stitches.config.ts
- src/ui/BackButton.tsx
- src/ui/Button/Button.tsx
- src/ui/HintButton.tsx
- src/ui/Panel/Panel.tsx
- src/ui/Text/Text.tsx
- src/ui/TextField/TextField.tsx
- yarn.lock
Breaking off a chunk of the add members work to get deployed. This just includes the add one member or add many members by eth addr/name functionality.
This is based on our hybrid onboarding pod / 1.5 add members concepts.  Figma here: https://www.figma.com/file/qSap4xHYicSvZb3xXqmBzI/Onboarding-Wireframes?node-id=323%3A20725
This also includes feature flagging for the link sharing stuff, which is off for now and is half-baked because the UI isn't done. 
* New Add members page, which will have tabs for more styles of adding, but are hidden for now. 
* Getting rid of the add contributor dialog , which means adding users is now simple, and doesn't have advanced options
* I have tested this quite well, including validation varieties, but I could use thorough testing from a reviewer.  
* Also …
> Add Members Page w/ just bulk add member by address

- api-lib/gql/__generated__/zeus/index.ts
- hasura/metadata/databases/default/tables/public_vaults.yaml
- src/hooks/gql/useVaults.ts
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/gql/mutations.ts
Most of this data is public anyway. The org_id is the only thing worth hiding, since its entirely internal.
> Refactor: expose all public vault info and conceal org id

- src/pages/VaultsPage/VaultsPage.tsx
resolves #1066 
1- Use CircleId to switch to current org on vaults page
2- The index of the org that contains the circle will be filtered if circleID is available otherwise it will be 0
1- Choose a circle from circles page or overview menu
2- Switch to covaults from overview menu and notice the selected org.
Expected:
The current org should be selected.
3- use browser address bar to navigate to app.coordinape.com/vaults
Expected:
The first org should be selected
> Choose Current Org upon switching to vaults page after selecting a circle

- src/routes/paths.ts
before:  https://docs.coordinape.com/info/documentation/coordinape-vaults
after:  https://docs.coordinape.com/get-started/organizations/vaults
> External URL for Vaults documentation link

- src/pages/VaultsPage/VaultTransactions.tsx
We were just truncating decimals. Now, we handle decimals correctly.
> Render decimals For Vault Transaction Histories

- src/pages/VaultsPage/CreateForm.tsx
now the existing vault symbols cannot contain the token symbol. This
regression occurred because Yearn vaults now have the yearn prefix
> bugfix: prevent duplicate vaults

- src/pages/DistributionsPage/DistributionForm.tsx
- src/pages/DistributionsPage/DistributionsPage.test.tsx
- src/pages/DistributionsPage/DistributionsPage.tsx
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=d04cef68e3184b2187e504398d8bbc06&pm=s
This change allows distribution page to be accessed even if epoch has no allocations, so the admin still is able to make a fixed payments distribution if desired
Added a unit test for a test case with no allocations, alternatively you can test it manually by ending an epoch and going to the distribution page after creating a vault+ deposit
> Allow access to distribution page form when there are no allocations

- src/utils/index.test.ts
- src/utils/index.ts
Decimal numbers that start with zeroes after the period will end up with an incorrect rounded result.
Pad the zeroes back after it gets converted into a number for rounding.
added more test cases in the unit test with numbers that fit this scenario.
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=52af939d7d1a4cf8aeabb777293e5908&pm=s
> Fix number with commas utils function

- src/pages/CircleAdminPage/RemoveCircleModal.tsx
- src/pages/CirclesPage/CirclesPage.tsx
- src/pages/CirclesPage/getOrgData.ts
- src/pages/CreateCirclePage/CreateCirclePage.tsx
fixes #1045
1- invalidate overview menu and orgs list after adding or deleting a circle
2- Deleting circle was working previously but change in queries required an update
1- Add a new circle and notice overview menu
2- Navigate to overview page and check the circles
> invalidate overview circles after adding or removing circles

- api/circle/landing/[token].ts
- cypress/e2e/createUser.cy.ts
- src/config/features.ts
- src/forms/formHelpers.ts
- src/lib/gql/queries.ts
- src/lib/zod/index.ts
- src/pages/AddMembersPage/AddMembersPage.tsx
- src/pages/AddMembersPage/ConstrainedBox.tsx
- src/pages/AddMembersPage/NewMemberList.tsx
- src/pages/AddMembersPage/TabButton.tsx
- src/pages/AllocationPage/AllocationGive.tsx
- src/pages/AllocationPage/AllocationPage.tsx
- src/pages/JoinCirclePage/AddressIsNotMember.tsx
- src/pages/JoinCirclePage/JoinCirclePage.tsx
- src/pages/JoinCirclePage/JoinWithMagicLink.tsx
- src/pages/JoinCirclePage/index.ts
- src/routes/paths.ts
- src/routes/routes.tsx
- src/stitches.config.ts
- src/types/api.circle.d.ts
- src/ui/Avatar/Avatar.tsx
- src/ui/CenteredBox.tsx
- src/ui/CircleWithLogo.tsx
- src/ui/Panel/Panel.tsx
Improving onboarding of new users
This adds:
* magic link on the add members page
* a landing page for a circle where you can set your name if provided a magic link
* a welcome link for sharing with users after they were invited that will take them to the circle directly
Out of scope but targeted for future work:
* These links could work without login, but the site routing is really unfriendly for that pattern for now, so you have to login to see anything, which kind of makes the welcome link redundant, but we will improve it later
* The links could probably be shorter and more brief
* Revocation  of the links requires some more UI design so we aren't including it yet. The backend is implemented.
1. Visit the add members page and copy a magic link
2. Try using it with an account that …
> link based joining

- src/pages/CircleAdminPage/AdminIntegrations.tsx
Delete Dework integration is not working
Prevent the page from submitting by declaring the button as a button type
manually delete the integration in the circle settings page
@crabsinger
> Fix for dework integration delete

- api-lib/gql/mutations.ts
- api/hasura/actions/_handlers/vouch.ts
- src/lib/zod/index.ts
User hit error vouching, broken for all in UI.
Write API changes made voucher_profile_id required but it isn't actually required for user based (non-api) workflows because it is set using the current user. 
Try to vouch for someone using the UI.
> remove requirement for voucher_profile_id in non-api call

- src/components/MainLayout/CircleNav.tsx
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AdminPage/components.tsx
resolves #1313 
1- Add Admin button in navigation bar to navigate to Admin settings
2- Remove Settings and add circle buttons from Members page
3- Members Page address should be circleId/members instead of circleID/Admin
4- fix Add members bug in Mobile mode
1- Enter a circle as admin and check the Admin and Members button in Navbar
expected:
1- Members button should navigate to Members page that should not have settings or add circle buttons
Address bar should show circles/circleId/members
2- Admin button will navigate to circle settings page
non Admin
Mobile
@wingfeatherwave
> Update nav for members and admin

- src/pages/AllocationPage/AllocationGive.tsx
simple fix: just wrap updateLocalGift in useCallback
fixes #1202
type very quickly into a notes field during allocation. the list of people you're allocating to should have lots of bio statements filled out, otherwise the slowness is not as noticeable
----
also see #597, a previous version of this fix
> fix lag when typing notes during allocation

- cypress/e2e/createVault.cy.ts
- src/lib/vaults/contracts.ts
Underlying value does not sync with the pricePerShare real time hence its not a correct representative of the actual vault value.
Switched the calculation to use sharePrice of yTokens instead.
Clicking on the Max on the Gift input in distribution page should give a value of yTokens owned * pricePershare
@levity
> update vault underlying to realtime share price

- src/pages/DistributionsPage/DistributionForm.tsx
- src/pages/DistributionsPage/DistributionsPage.test.tsx
Admin is able to have a preview of the budget allocation before committing to create a vault.
Enable the Gift amount input when there are no vaults created for the circle.
The newly created unit test should pass. Alternatively go to Baby circle to test in the distribution page manually.
@levity @topocount 
https://www.notion.so/coordinape/CoVaults-7014c5fa5fca473aafd26d918e99df06?p=0553ea016c3c4601b1f1aaa14d7983ab&pm=s
> Allow Editing of Gift Input when there are no vaults

- src/hooks/useVaultFactory.ts
- src/pages/VaultsPage/CreateForm.tsx
Adding a button in the modal that directs to the etherscan link of the tx hash when a vault is created.
Button should appear when creating a new vault. Existing unit tests should pass
@topocount @levity @crabsinger 
https://www.notion.so/coordinape/78924b82ebe4445cbe20f586cdcb2795?v=bbf298c4fee34b5ea4eb18db638676bf&p=db7f5e55c27c4986ba5dd50e9324708a&pm=s
> Add etherscan link to create vaults wait modal

- .prettierrc.json
- hasura/metadata/actions.graphql
- package.json
It's "pretty" apparent some of us aren't running lint-staged on commit,
which is fine. However, lint-stage prettier fixing was divergent from
our CI-enforced `yarn prettier:check`. This has caused some spam for
git-blames which isn't the biggest deal but has really irked me for
a while.
This change makes prettier executions consistent across lint-staged and
CI.
I've also configured our prettier CLI commands to run on all
our config files, which is best practice.
I'm also open to getting rid of husky, since I think devs should be responsible for configuring their IDEs to hook into a project's config correctly.
> Standardize Linter runs across CI and husky

- api-lib/contributions.ts
- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api/hasura/actions/_handlers/deleteContribution.ts
- api/hasura/actions/_handlers/updateContribution.test.ts
- api/hasura/actions/_handlers/updateContribution.ts
- api/hasura/actions/actionManager.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/metadata/databases/default/tables/public_contributions.yaml
- src/lib/zod/index.ts
- src/utils/testing/mocks.ts
The update contribution handler ensures a contribution can't be changed
to a time that was included in a closed epoch. Contributions with a
timestamp in closed epochs are not editable. Contributions cannot have
empty descriptions. Contributions must exist for the user as well.
Make inserts allowable from the autogenerated api. It's impossible to spam
contributions thanks to the custom check.
completely disallow updates from the autogenerated api since the action
exists.
allow selects for all contributions added by the user.
Added unit tests to ensure all error cases are handled
integration tests will be written when the frontend is implemented (imminent)
Merge after #1327 and rebase on top of it.
> Create updateContribution Handler

- api-lib/gql/queries.ts
- api/hasura/actions/_handlers/allocationCsv.ts
When there is an epoch where a member has received GIVE, but also was deleted, the CSV export is showing different data than the distribution page because the deleted users are still being taken into account.
Remove deleted users from CSV so their received GIVE will not be taken into consideration when calculating the percentages of other users. This is what happens in the distribution page's table.
Ran locally and observed the CSV without the deleted user as well as the correct adjusted percentages to account for the absence of the deleted users, refer to the screenshots below
@ashmbanks
Fixes https://github.com/coordinape/coordinape/issues/1363
> fix: Remove deleted users from CSV

- hasura/migrations/default/1663957477889_remove-old-laravel-tables/down.sql
- hasura/migrations/default/1663957477889_remove-old-laravel-tables/up.sql
Remove unused old laravel tables
Run the up and down migrations to test.
> Remove unused old laravel tables

- cypress/e2e/updateUser.cy.ts
- src/components/Table.tsx
- src/pages/AdminPage/MembersTable.tsx
- src/pages/AdminPage/NomineeTable.tsx
- src/pages/DistributionsPage/AllocationsTable.tsx
Fix Failed tests due to Changes in Members Page
Fix the issue regarding that every page is sorted separately
1- Add wait time after saving and update searched string in cypress tests
2- Move slicing for pages after sorting so that all the data is sorted unlike the current the situation where every page is sorted Separately
> Enhance sorting and fix cypress tests

- hasura/metadata/databases/default/tables/public_contributions.yaml
on the new allocations workflow, circle members need to be able to see contributions from other members
opened up the perms in hasura based on code snippet from topo
> open up hasura permissions to view contributions from all circle members

- hasura/metadata/databases/default/tables/public_contributions.yaml
some kind of typo that i don't fully understand was breaking metadata parsing, this is generated by hasura console and seems to work
> fixing indenting in the contributions select perms

- src/pages/AdminPage/MembersTable.tsx
Members table is not sorted correctly if admin or fixed payment columns are clicked
Corrected wrong indices for fixed payment and admin columns and added non receiver column index
Go to Members page and sort the members table using different criteria
> Fix admin and fixed payment coulmns sorting in members table 

- docker-compose.yml
- src/utils/apiKeyHelper.ts
Resolves #1391 
- bump hasura version to 2.11.2 (matching prod's current version)
- fix DevPortal link
@levity 
Seems this fix is working for me in localhost. Just use prod console pointed at localhost.
> Use cloud hasura graphiql for all dev portals

- src/stitches.config.ts
- src/ui/Text/Text.tsx
text compound variant for tags.  
nice paradigm to follow: buttons should have dark bg, non-clickable tags should have light bg
> Tag variant

- yarn.lock
This change seems to make this message go away:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
> Doing the caniuse thing prompted in the console

- src/pages/GivePage/ContributorButton.tsx
- src/pages/GivePage/GiveAllocator.tsx
- src/pages/GivePage/GiveDrawer.tsx
- src/pages/GivePage/GiveRow.tsx
Notes weren't properly changing when scrolling through users in the give drawer. There was also no animations on plus/minus or hovering on selected users, and I thought I'd add some for fun.
> Give notes fix

- src/pages/GivePage/AvatarAndName.tsx
#1365 removed margin around the avatar, so this restores it on the give page
> adding margin around avatar on give page that was lost in avatar updates

- src/pages/AdminPage/MembersTable.tsx
implements #1415
1- Add Give sent and Give received columns to members table
2- The columns will be visible only to Admins
3- Admins can sort the table by received and sent gives
4- GIVE in table header can be changed if token name is changed
Check Members table as Admin
> Add token sent & received columns to members table

- src/pages/AllocationPage/AllocationGive.tsx
- src/pages/AllocationPage/AllocationPage.tsx
- src/pages/AllocationPage/calculations.ts
- src/pages/AllocationPage/queries.ts
- src/pages/GivePage/GiveAllocator.tsx
- src/pages/GivePage/index.tsx
The new GiveAllocator allows for manual entry of a number, but you can't actually erase the 0 to start from scratch. 
* Made the `tokens` field optional;
* Added a logic to handle the empty string and zero on the input field.
Ran locally and tried it out, refer to screenshot below
@CryptoGraffe
Fixes https://github.com/coordinape/coordinape/issues/1401
> fix: Allow for empty string in the `GiveAllocator` input

- src/components/Drawer.tsx
- src/pages/AssetMapPage/AMProfileCard.tsx
Map should not be cut off at top of page, refer to issue https://github.com/coordinape/coordinape/issues/1421
Makes the position of the text absolute pinned to the top of the page
Ran locally and saw the map not being cut off, refer to screenshots below
@levity 
Fixes https://github.com/coordinape/coordinape/issues/1421
> fix: Map cut off

- src/pages/GivePage/GiveDrawer.tsx
When scrolling from a member w/ a note to a member w/o a note, the previous member's note was being cached in the textarea, which can cause other notes to get stomped. 
pass `note ?? ''` instead of `note` to the textarea value field
Change a note on a user adjacent to a member w/ no note and then scroll to the member with no note. The textarea should be empty.
> fix note re-use and stomp issue discovered by crabsinger

- src/pages/GivePage/index.tsx
If you click add/remove contributor in the give drawer and quickly scroll to a different member, the give drawer doesn't update when you scroll back to the original member. 
When the underlying members list was changing, we were only patching up the state of the currently selected member in the drawer, rather than all members. This fix updates all members. 
Change collaborator status and quickly scroll to a different user. After seeing the collab status change in the main members list,  scroll back to the original member in the give drawer and note that their collaborator status is correct.
> fix updation of collaborator status in give drawer when scrolled to other member

- .github/workflows/CI.yml
- README.md
- hardhat/scripts/start-ganache.sh
- package.json
- scripts/link_hardhat.sh
- scripts/rebuild_hardhat.sh
- scripts/setup.sh
- yarn.lock
The deployment of #1424 failed because the way we were using `yarn link` to import `@coordinape/hardhat` from the `hardhat` folder within the project didn't work with serverless functions. This PR implements an alternative.
Use a `file:` dependency in package.json for `@coordinape/hardhat` instead of `yarn link`. 
The downside of this is that incorporating changes from hardhat is slower because `yarn install` has to run again -- see changes to `link_hardhat.sh`.
Works with `vercel dev` locally. Will deploy to staging to make sure it works with staging Hasura as well.
> Serverless hardhat import

- src/pages/GivePage/GiveRow.tsx
This fixues a bug where the we would intermittently flicker "Add Collaborator" in the main GiveRow when removing Collaborator status inside the Drawer. This fixes the bug, and maintains the fade-in CSS transition.
However, it doesn't keep the fade-out transition.
@CryptoGraffe
> Fix bug showing "Add Contributor" on save

- src/ui/Modal.stories.tsx
- src/ui/SvgIcon.stories.tsx
- src/ui/ToggleButton.stories.tsx
- src/ui/Tooltip/Tooltip.stories.tsx
To support faster development and designing, there should be more stories added to Storybook
Added a story for the following components `Modal`, `Tooltip`, `ToggleButton` and all the generated icons
Ran storybook and played with the stories, refer to the screenshots below
Preview link https://coordinape-storybook-git-fork-karelianpie-issue-1462-coordinape.vercel.app/?path=/story/design-system-components-modal--modal
@crabsinger
Closes https://github.com/coordinape/coordinape/issues/1462
> feat: Stories for `Modal`, `Tooltip`, `ToggleButton` and all the generated icons

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api-test/hasura/actions/_handlers/markClaimed.test.ts
- api/hasura/actions/_handlers/markClaimed.ts
- api/hasura/actions/actionManager.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- scripts/generate_zeus.sh
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/vaults/contracts.ts
Track claims in interaction_events
interaction_events is only accessible from the backend, so we create a new Hasura action for claims. then we add the same mutation to it as we did for the other vault operations.
> add markClaimed action to hasura schema

- .github/workflows/chromatic.yml
We are getting the following [error](https://github.com/coordinape/coordinape/actions/runs/3195021921):
> Invalid workflow file: .github/workflows/chromatic.yml#L12
> The workflow is not valid. .github/workflows/chromatic.yml (Line: 12, Col: 9): Unexpected value 'with'
Set up your GitHub Actions workflow with a specific version of node.js
> fix: Set up your GitHub Actions workflow with a specific version of node.js

- src/components/MainLayout/CircleNav.tsx
- src/pages/AddMembersPage/NewMemberList.tsx
- src/pages/AdminPage/AdminPage.tsx
- src/pages/AllocationPage/AllocationEpoch.tsx
- src/pages/AllocationPage/AllocationPage.tsx
- src/pages/AllocationPage/AllocationStepper.tsx
- src/pages/AllocationPage/AllocationTeam.tsx
- src/pages/CircleAdminPage/CircleAdminPage.tsx
- src/pages/CircleAdminPage/getCircleSettings.ts
fixes #1399
1- refetch team selection using reac-query and use recoil data as initial data for it
1- Go to Allocate page and opt-in then select a team
2- Go to circle settings and turn off team selection
Expected: all circle members should appear and team selection should be removed from the stepper
3- Re enable team selection
Expected: selected members and team selection step should return
> Refresh team selection settings on change

- src/utils/index.test.ts
- src/utils/index.ts
Current implementation doesn't handle numbers that round up to the next whole number correctly.
e.g for cases like 6.999
> Fix number with commas helper function

- src/pages/GivePage/SavingIndicator.tsx
- src/ui/Button/Button.tsx
@wingfeatherwave 
Remove unncesssary Box, use CSS on the Text. Not sure if the "Saving Changes" spacing is perfect... but matches what is on `main`.
> Remove unneccessary Box in SavingIndicator

- src/components/LoadingModal.tsx
- src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx
On the Organization Settings Page, there is no state indication as the image uploads. This PR sets the loading modal to true during image upload.
Show loading state during image uploads
> show Loading modal during image uploads

- src/components/Drawer.tsx
fixes #1489
Removed zIndex from the Circle Map header text 
Go to Map page on mobile and touch a node to select it or to drag it
> Fix user nodes select on mobile

- src/pages/GivePage/GiveDrawer.tsx
fixes #1479 
set setNeedToSave to undefined upon changing notes
Go to new give page on active epoch and give feedback to one of the team mates 
While writing notes saving indicator should be hidden.
after finishing saving changes then changes saved should appear
while typing
> Hide changes saved/saving while writing notes in new Give page

- src/components/AvatarUpload.tsx
- src/components/EditProfileModal.tsx
- src/hooks/useApiWithProfile.ts
- src/lib/gql/mutations.ts
- src/lib/images.ts
- src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx
- src/utils/presentationHelpers.test.ts
- src/utils/presentationHelpers.ts
resolves #1496
Update AvatarUpload.tsx to follow org logo upload in OrganizationSettingsPage.tsx
- Button to upload new Image
- Auto-save Image after selected
- Error state
- While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."
Update updateProfileAvatar mutation to return the avatar to display after upload
I kept the same way of fetching the data by recoil. I think it needs a separate issue because there will be many changes in profile page
1- Go to your profile page
2- click edit profile
3- use correct image format to check the uploaded avatar
4- use large size photo or wrong format to check the error message
> Improve User profile picture upload pattern

- src/lib/images.ts
Seems the root cause of the image upload woes are that Vercel has a 4.5mb payload size limit, which we've been exceeding. Update FE UIs validation to support this limit.
https://vercel.com/docs/concepts/limits/overview#serverless-function-payload-size-limit
> Use 4mb image limit to respect vercel's payload size

- src/pages/ContributionsPage/ContributionsPage.tsx
The new contributions drawer had this regression where each modification
to the text generated a new contribution.
Normal behavior is now restored, and the new contribution drawer
seamlessly converts to "edit contribution" behavior after the initial
save.
Create a contribution and let it save. Ensure that any changes after the
initial save modify the newly created contribution and don't create any
more new contributions
@wingfeatherwave
> Fix For New Contributions Spam

- src/components/MainLayout/CircleNav.tsx
- src/pages/CirclesPage/CirclesPage.tsx
- src/pages/GivePage/index.tsx
This is the last step need to ship contributions: defaulting to GiveBeta so contributions are visible during the allocation process.
An opt-out button has been added to a banner so folks can go back to the
original allocations flow if they want.
The Nav bar `Allocations` button directs to GiveBeta and the `CircleRow`
button for Allocations also now links to GiveBeta. Please let me know if
I'm missing anything else.
This should be merged  before #1518.
n.b. #1516 also should be merged before #1518.
@CryptoGraffe
> Convert GiveBeta page to default allocations flow

- src/pages/GivePage/EpochStatementDrawer.tsx
- src/pages/HistoryPage/CurrentEpochPanel.tsx
the epoch statement save function was caching only on the backend
entrypoint and nothing else. This fixes that issue.
Additionally the "Allocate" button in the Current Epoch Panel was
pointing to the old allocations flow instead of givebeta
> Quick bugfixes for epoch statement and routing

- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/ContributionsPage/queries.ts
Integrator APIs can return errors if our filters are too large. Intead
of querying for all contributions since the beginning of time for an
initial epoch in a circle, we now query only back to the month before
the epoch started.
In the Contributions Page, Epochs that ended before the Contributions
feature was launched are now hidden.
Potential Future work: optionally hide all epochs with no contributions
> Hide irrelevant epochs and integrated contributions

- src/components/ReceiveInfo.tsx
- src/pages/AllocationPage/AllocationEpoch.tsx
- src/pages/GivePage/index.tsx
resolves #1475 
1- Fetch the receive data by react-query
2- refetch the data and rerender on opt-out change
3- used user.non_receiver to handle corner cases for the current epoch because gift data won't be ready from hasura immediately after opt out
1- opt out by old and new give after receiving gives from another user
expected: received gives should change to 0 immediately
2- Check last epoch received gives if there is no current epoch and still opted in
3- Check last epoch received gives if there is no current epoch and opted out after
tent.com/34943689/196160370-db76f988-4bf6-4116-a6a6-e5a078184ce0.png)
> Update Receive Info on opt out change

- src/components/FormInputField.tsx
- src/components/MainLayout/MainHeader.tsx
- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/GivePage/Contribution.tsx
- src/pages/GivePage/EpochStatementDrawer.tsx
- src/pages/GivePage/GiveDrawer.tsx
- src/pages/GivePage/SavingIndicator.tsx
- src/ui/Text/Text.tsx
UI fixes for allocations and contributions
* line height and font size unification / dialing for drawer fields
~~* persistent `✔ Saved` indicator for when text has been saved in the past (ie: not blank)~~
* css animations for hover states 
* remove double panel bubbles for contributions in give drawer.  use separator lines instead
TBD: adding an `Autosave` hint text beneath the initial form field to be edited.
> Fixup/contributions allocations UI fixes

- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/ContributionsPage/mutations.ts
Save state was getting overwritten when switching through contributions.
This also includes a fix from topo about contribution text getting stomped when mutation returned.
> Contribution save state fix

- docker-compose.yml
There may be an opportunity to simplify our service config so that:
- it's easier to explain to new devs
- it's easier to reason about
- it's easy to spin up multiple sets of the containers that don't collide, for CI or other purposes
This is a small change that I hope leads in that direction, a prelude to #1540
> use default internal ports for docker services

- src/pages/MembersPage/LeaveCircleModal.tsx
- src/pages/MembersPage/MembersTable.tsx
- src/ui/Button/Button.tsx
Using our below-field errors instead of the native html5 error popover
> Minor UI fixes: leave circle error notification, button colors

- src/components/ReceiveInfo.tsx
User hitting error with deleted user as sender in tokenGift
workaround this in UI for now by checking for null
> fix for error seen by user where the tokenGift.sender is null

- api-lib/event_triggers/sendInteractionEventToMixpanel.ts
Check for undefined was insufficient, needed a check for null as well. Fixes an error that was getting reported a lot to sentry.
> fixing null bigint in interaction events

- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/GivePage/EpochStatementDrawer.tsx
- src/pages/GivePage/GiveDrawer.tsx
- src/pages/GivePage/SavingIndicator.tsx
- src/pages/GivePage/index.tsx
- src/ui/SavingIndicator.stories.tsx
- src/ui/SavingIndicator.tsx
Resolves #1400 
*  Move SavingIndicator into a shared component
* Add error handling and retry support to SavingIndicator
* Update existing users of SavingIndicators to pass retry methods
This list of uses includes:
- Allocations Page
- Contributions Page
- Epoch Statement on New Give Page
Followup tasks:
- Add all this to storybook
Test that all of these pages work as expected when requests don't error. And that when errors happen it properly shows the error state, and the retry functions work as expected.
This commit adds some helpers to introduce errors cases around these mutations: https://github.com/coordinape/coordinape/commit/0119ddddcf0258ee595dd8c23a5106f4e97b4c81
> Refactor SavingIndicator; add retry to Allocations & Contributions

- src/pages/ContributionsPage/ContributionsPage.tsx
There was an edge case when if you switch between one selected Contribution to another selected Contribution BEFORE the mutation finished saving, the useMemo would not be invoked, and the page would show old state even though the save succeeded. We change from that pattern to use a dataUpdatedAt memo pattern that properly updates when new data is fetched.
> bugfix: Contributions doesn't re-render when data changes

- package.json
- yarn.lock
We have conflicting dependencies on react-refresh brought about by upgrading storybook. This resolves it to 0.11.0 .
> resolving react-refresh to 0.11.0 to fix import issues

- api/hasura/remote/vaults.ts
- hasura/metadata/databases/default/tables/public_vaults.yaml
- hasura/metadata/remote_schemas.yaml
- package.json
- scripts/serve_dev.ts
- yarn.lock
The API handler was split out ahead of #1520 to resolve difficulties encountered during deployment. Now that those are resolved, it's all in a single branch again. See #1520 for more context.
> pricePerShare in Hasura remote schema

- .storybook/preview.js
- src/ui/RadioGroup/RadioGroup.stories.tsx
Implements a story for the `RadioGroup.tsx` component.
@crabsinger 
> feat: Add `RadioGroup` story

- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/GivePage/EpochStatementDrawer.tsx
- src/pages/GivePage/GiveDrawer.tsx
Contributions do not reload on add/remove allocation
Invalidate `'allocate-contributions'` query on 
* createContributionMutation
* deleteContributionMutation
Ran locally and recorded a screencast, see below
https://user-images.githubusercontent.com/78794805/199474641-56223d6f-5f48-47d3-869a-89191c1d3c85.mov
@CryptoGraffe 
Fixes https://github.com/coordinape/coordinape/issues/1608
> fix: Invalidate 'allocate-contributions' query on add/remove contribution

- src/ui/Image/Image.stories.tsx
- src/ui/Table/Table.stories.tsx
Randomising data does not work well with Chromatic as it detects it as a change
Serve always the same assets and data for the `Image` and `Table` stories.
Ran storybook locally and observed always the same image being served as well as the same data for the table
@levity
> fix: Chromatic stories

- api-test/hasura/actions/_handlers/markClaimed.test.ts
- api-test/hasura/cron/recoverTransactions.test.ts
- cypress/e2e/allocate.cy.ts
- cypress/e2e/createEpoch.cy.ts
- cypress/e2e/createNominee.cy.ts
- cypress/e2e/createUser.cy.ts
- cypress/e2e/createVault.cy.ts
- cypress/e2e/updateCircle.cy.ts
- cypress/e2e/updateUser.cy.ts
- cypress/support/commands.ts
- cypress/util/index.ts
- src/lib/vaults/contracts.test.ts
- src/lib/vaults/contracts.ts
- src/lib/vaults/distributor.test.ts
- src/pages/ClaimsPage/useClaimAllocation.test.tsx
- src/pages/DistributionsPage/useSubmitDistribution.test.tsx
- src/pages/VaultsPage/VaultTransactions.tsx
- src/utils/provider.ts
- src/utils/testing/index.tsx
- src/utils/testing/mint.ts
- src/utils/testing/provider.ts
- src/utils/testing/unlockSigner.ts
These changes came out of work in #1540. They fix errors in Cypress when running ganache on a non-default port.
> refactor test provider code to work in Cypress

- .github/workflows/CI.yml
Attempt to speed up CI Github Actions a bit by caching Docker images. If this works correctly, we should see many `Downloading...` and `Extracting...` log lines ([e.g.](https://github.com/coordinape/coordinape/actions/runs/3417769084/jobs/5689286607)) go away
> cache docker images in CI

- .github/workflows/CI.yml
to deal with warnings about the set-output and save-state commands being deprecated
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> upgrade github actions

- hasura/metadata/databases/default/tables/public_circle_api_keys.yaml
- hasura/metadata/databases/default/tables/public_contributions.yaml
- hasura/migrations/default/1667278140823_contributions_api/down.sql
- hasura/migrations/default/1667278140823_contributions_api/up.sql
Allows 3rd party integrators / api users to programatically read and create contributions for a given circle.
Added columns and appropriate permissions in Hasura for the `api-user` role to create and read contributions. Also added a new column to contributions that tracks which API key was used to create the contribution (if any).
Ensure permissions are correctly configured and contributions created with a given API key are marked as such.
@topocount @zashton 
#1545
> Update datamodel for read/create contributions API

- src/hooks/gql/useCircleOrg.ts
- src/hooks/gql/useVaults.ts
- src/pages/DistributionsPage/DistributionsPage.tsx
- src/pages/MembersPage/MembersTable.tsx
- src/pages/MembersPage/index.tsx
fixes #1618
1-MembersPage have many useQuery's and some of them are defined inside custom hooks causing refetching and rerendering of Members Page solved by adding refetchOnWindowFocus: false to MembersPage queries
2- show saved changes only after saving the changes only
3- Handle the errors and Loading for main queries in MembersPage
follow the steps in the bug description #1618 the buggy behaviour should disappear
> Fix members table and member settings rendering

- api-lib/gql/adminClient.ts
- api-lib/gql/makeThunder.ts
We are getting 60s timeouts in vercel and it's a bit unclear why. If we timeout the zeus calls back to hasura at 45s maybe we will find some meaning. 
Adding 45s timeout to adminClient
Test out on a dev vercel instance and make sure some custom actions work ok (eg allocating)
> adding 45s timeout to all adminClient graphql calls

- src/components/MainLayout/OverviewMenu.tsx
- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/components/ReceiveInfo.tsx
- src/pages/GivePage/GiveRow.tsx
- src/pages/GivePage/MyGiveRow.tsx
- src/ui/Popover/Popover.stories.tsx
- src/ui/Popover/Popover.tsx
* Console log was getting filled with improper nesting warnings.  Fixed.
* Remove Popover anchor, as it's not actually needed.  I thought it would be helpful in making positioning easier, but the new version of Radix popover makes the positioning easier without `PopoverAnchor`, which can be used if you want the popover to appear someplace different than the trigger.
> Bugfix console warnings nested `button` and `anchor`

- src/components/FormInputField.tsx
- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/ContributionsPage/queries.ts
resolves #1566 
Allow admin to to Edit help text to the contribution page 
go to Contribution page--> contribution --> click edit edit text and change text-->click save and check saved text
as an admin
as non admin
@reeserj 
@sshmm 
https://github.com/coordinape/coordinape/issues/1566
> Allow admin to populate contribution text fields

- src/components/MainLayout/OverviewMenu.tsx
- src/components/ReceiveInfo.tsx
- src/pages/GivePage/GiveDrawer.tsx
- src/pages/HistoryPage/EpochPanel.tsx
resolves #1561
1- Allow user send markdown notes
2- display markdown in ReceiveInfo popover and EpochPanel
preocondition: Active Epoch
1- Go to Allocation page and click on the user that you want to allocate to 'another wallet of users so that you can view the notes
2-  write markdown note to that user
3- Switch to the other user to view the markdown note on the give popover
4- wait for the epoch to end to be able to view it on EpochPanel
scrollable popover
> add markdown support for allocation notes

- .gitignore
- craco.config.js
- cypress.config.ts
- cypress/plugins/index.ts
- cypress/support/commands.ts
- hardhat/scripts/start-ganache.sh
- package.json
- scripts/ci/manager.sh
- scripts/serve.sh
- scripts/serve_dev.ts
- tsconfig-backend.json
- tsconfig.json
- yarn.lock
For code coverage reporting, Jest only instruments the code that runs under its own process. There are two other processes running code that should be counted:
- Cypress (with a front-end bundle)
- The web server for action handlers
- This receives requests from both Jest and Cypress
If a Jest test makes a request to Hasura, and Hasura makes a request to an action handler, Jest cannot count that action handler as having run, because it's started by a different process.
So, in order to have a single unified report of test coverage, we have to combine multiple reports. 
This PR adds code coverage instrumentation to the web server, as well as to the frontend code run by Cypress. When Cypress runs, it combines these two sources into one report. ([See …
> combined code coverage reporting

- package.json
This change updates the repo lint:check script to return an error state
when one or more warnings are encountered.
Nothing else changes, but this error state will cause CI to fail when
warnings are encountered, ideally forcing devs to address the lint
problems so they don't get merged to main
> Configure Eslint Warnings to fail CI

- src/components/ProfileCard/ProfileCard.tsx
- src/hooks/useContributions.ts
Contribution providers do not want to support multi-year queries due to
adversarial concerns such as scraping. Our contribution hook would fall
back to epoch timestamp zero if no start date for the query was
supplied. This is now fixed and the query falls back to a month before
the current epochs start date if no prior epoch exists.
I've also tightened up the API to make the dates required params so that
no hidden fallbacks are possible. This is at the expense of the legacy
code in the ProfileCard, which utilizes recoil and irresponsibly tries
to render a result even if no epoch is currently active.
It'd be preferable to pass in a required epoch prop or two that the
component can rely on, but given that this is a legacy view, it's not
worth the maintenance. The solution, then is nominally …
> bugfix: stop querying contributions from time 0

- src/pages/GivePage/EpochStatementDrawer.tsx
- src/pages/GivePage/GiveDrawer.tsx
- src/pages/GivePage/index.tsx
- src/pages/GivePage/queries.ts
resolves #1691 
-Allow Dework and wonder tasks to show up on allocations card view 
-the start date of the epoch GiveDrawer and EpochStatementDrawer is the end of the previous epoch like ContributionsPage
Test 1 
open circle --> create epoch --> add tasks from (wonderverse Or Dework) connection --> check Allocations card view
test 2
open circle --> go to contributions page -->check the letest contribution and date  --> go to Allocations card view and check
test 1
test 2
@levity 
@sshmm 
#1691
>  Bug: Dework tasks not showing up on Allocations card view

- .env.example
- src/common-lib/log.test.ts
- src/common-lib/log.ts
Why implement a new logger class? In short, to improve dev experience
when it comes to:
- implementing nuanced, complex logic that might need to be extended or
debugged further later
- easily muting logging in unit tests (by aggressively mocking this class)
- runtime debugging locally by using the DEBUG environment variable
This is all possible because the class uses the debug package
under the hood: https://github.com/debug-js/debug#debug
unit tests are included and demonstrate how the logger can be used
add this code to `src/App.ts`:
```js
import { DebugLogger } from 'common-lib/log';
const logger = new DebugLogger('App');
logger.log('hello, world');
logger.error('derp');
```
> Implement a Debug Logger

- src/pages/CircleAdminPage/CircleAdminPage.tsx
Admin page will spin infinitely if you are on a chain that vaults are not deployed to.. Fixes this and prompts switch to mainnet.
> admin page requires vault chains

- src/components/MainLayout/SampleOrgIndicator.tsx
Users have expressed that they don't know how to "leave" or "progress out of" the sample circle experience.
New "Create real Circle" button in the sample org header
> link to create a real circle in the sample org alert bar

- src/lib/time.test.ts
- src/lib/time.ts
- src/pages/HistoryPage/NextEpoch.tsx
resolves #1719 
-Allow time of the created Epochs to be shown correctly 
open any circle --> create an epoch --> set a time that you like -->check Allocation countdown in (Epoch Overview, give)
@levity 
#1719
> fix bug: Allocation countdown

- api/login.ts
We added this to `first_login` but not all `login` events.
> Add chainId to `login` interaction event

- src/pages/AssetMapPage/AMDrawer.tsx
this change adjust the zIndex for the popup menu in the AMDrawer
fixes #1761
> zIndex for AMDrawer popup

- src/features/auth/NetworkSelector.test.tsx
- src/features/auth/WalletAuthModal.test.tsx
- src/features/auth/WalletAuthModal.tsx
- src/hooks/useWeb3React.tsx
- src/utils/testing/ethereum.ts
We want the web3 event handlers to be setup globally, not just via the auth modal, so moving these into Web3React hook setup.
Additionally adding a reload on accountsChanged hook.
> Move web3 event handlers into global

- api-lib/config.ts
- api/hasura/auth.ts
- hasura/metadata/databases/default/tables/discord_roles_circles.yaml
- hasura/metadata/databases/default/tables/discord_users.yaml
- hasura/metadata/databases/default/tables/public_circles.yaml
- hasura/metadata/databases/default/tables/public_profiles.yaml
- hasura/metadata/databases/default/tables/public_users.yaml
This role formalizes the access the discord bot will have to the db,
since it's administering an adjacent schema to persist state.
Specifically, the discord bot is now able to find all circles a user is
an admin of after they link their discord account to their coordinape
account. This is needed for the circle-linking flow.
> Create Hasura Role for the discord bot

- scripts/ci/manager.sh
- make interactive mode utilize nodemon
- move seed script invocation to only run before cypress tests
- make stop_services cleanup script delete db volume on quit
test plan: existing tests should all pass
> Optimize TestManager for backend test development

- api/hasura/auth.ts
- src/config/features.ts
In order to test the discord bot we need to have the discord feature enabled
* Enable the discord feature
* Add a `return` when discord auth, follow up on https://github.com/coordinape/coordinape/pull/1740
@topocount
> feat: Enable the discord feature

- api-test/hasura/remote/vaults.test.ts
- api-test/helpers/organizations.ts
- api-test/helpers/profiles.ts
- api/hasura/actions/_handlers/allocationCsv.test.ts
- api/hasura/actions/_handlers/allocationCsv.ts
- api/hasura/remote/vaults.ts
- scripts/ci/manager.sh
- src/common-lib/distributions.test.ts
- src/common-lib/distributions.ts
- src/pages/ClaimsPage/queries.ts
- src/pages/ClaimsPage/useClaimAllocation.test.tsx
- src/pages/DistributionsPage/DistributionsPage.test.tsx
- src/pages/DistributionsPage/DistributionsPage.tsx
- src/pages/DistributionsPage/queries.ts
In #1520 and #1624 we added a Hasura remote schema so the frontend can get pricePerShare values for vaults in a Hasura query instead of having to directly query the blockchain. This PR changes the distributions & claims code to use that.
> use price_per_share from remote schema

- cypress/e2e/give.cy.ts
- scripts/ci/manager.sh
Test was using indexes instead of user names to fetch rows in the give page. Switched to using names which is more reliable after other tests goof with the users in this circle.
> fixing flaky tests that were failing due to data from other tests

- src/pages/CircleAdminPage/CircleAdminPage.tsx
- src/pages/CircleAdminPage/getFixedPayment.ts
- src/pages/MembersPage/MembersTable.tsx
- src/pages/MembersPage/index.tsx
There was some vestigial code involved in loading the balance of the fixed payment vault on the members page; this PR removes it and looks up the balance in the most straightforward way
It also renames properties in an intermediate data structure to be less redundant
> simplify lookup of fixed payment vault balance

- src/components/ReceiveInfo.tsx
this change widen the text area in the dropdown for RecieveInfo 
before:
after:
no related issue just Lawris said this issue on devs-all
> wide text for ReceiveInfo 

- src/components/ReceiveInfo.tsx
Fixes #1710 
1- changed popover content maxHeight to 90vh
they are scrollable in all sizes
> Make receive Info drawer scrollable on smaller screens

- src/pages/HistoryPage/EpochForm.tsx
fixes #1797
use useState to rerender the epoch preview after updating the timing of the epoch
1- create or edit a new epoch using epoch form and watch the preview of the epoch timing every time you change the dates
> Fix epoch timing preview rendering

- src/components/ToastContainer.tsx
This overrides the pointerEvents none when Modals are displayed, showing toasts on Modal pages.
> Explicitly set pointerEvents for Toasts

- src/components/MainLayout/MainHeader.tsx
- src/components/MainLayout/getMainHeaderData.ts
- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/pages/JoinCirclePage/AddressIsNotMember.tsx
- src/pages/JoinCirclePage/JoinCirclePage.tsx
- src/pages/JoinCirclePage/JoinWithMagicLink.tsx
- src/pages/JoinCirclePage/queries.ts
some preparatory work for #1828 -- avoiding useMyProfile is preferable because it doesn't go through Recoil & so can avoid the use of Suspense
in these cases, replacing useMyProfile is pretty easy because not many fields are used, and so we can get them from `getMainHeaderData` instead. note that this latter API request is shaping up to be the one-stop shop for getting data when you load the page, at least once you're logged in
> remove some uses of useMyProfile

- api/discord/oauth.ts
- scripts/serve_dev.ts
The route invoked is /api/discord/oauth. This change allows the folder
structure to match the route.
> bugfix: align discord folder structure to match route

- src/pages/CircleAdminPage/HedgeyIntegrationSettings.tsx
- src/pages/ClaimsPage/LockedTokenGiftsTable.tsx
- src/pages/DistributionsPage/DistributionForm.tsx
We added a property "outline" to the hedgey buttons, with recent updates this has caused the buttons not to display. This PR removes the outline property.
Removes the outline property
Deploy and a quick visual test should work, previously the buttons did not show until you hover over them.
@levity @crabsinger
https://github.com/coordinape/coordinape/pull/1837
> Removes outline property from hedgey buttons

- src/pages/VaultsPage/VaultRow.tsx
$white was hardcoded and didn't look good in any theme
> removing white background from vault rows

- hasura/migrations/default/1674672458652_add_updated_at_trigger_missing_tables/down.sql
- hasura/migrations/default/1674672458652_add_updated_at_trigger_missing_tables/up.sql
These two tables (profiles, distributions) didn't have the `updated_at` trigger to update on row changes. Adding.
- Add updated_at trigger on `profiles` table
- Add distributions table `updated_at` trigger
> Add db triggers to update `updated_at` on tables

- api-test/helpers/circles.ts
- api-test/helpers/contributions.ts
- api-test/helpers/epochs.ts
- api-test/helpers/organizations.ts
- api-test/helpers/profiles.ts
- api-test/helpers/users.ts
- src/components/MyAvatarMenu/MyAvatarMenu.tsx
- src/pages/JoinCirclePage/JoinCirclePage.test.tsx
- src/pages/JoinCirclePage/JoinCirclePage.tsx
- src/pages/JoinCirclePage/JoinWithMagicLink.tsx
- src/routes/routes.tsx
Fixes #1807 
- Generate a valid join link
- Load it while logged out; verify the page appears with correct data and a "Connect Wallet" button
- Click "Connect Wallet" and log in; verify the page re-appears after login, now with a form instead of "Connect Wallet"
- Submit the form; verify that it adds you to the circle as before
- Load an invalid join link; verify it shows an error page, whether you're logged in or not
- Verify that welcome links still behave correctly (no change)
> Allow viewing join link page without login

- src/pages/ClaimsPage/LockedTokenGiftsTable.tsx
- src/pages/ClaimsPage/queries.ts
I noticed this issue during testing, the locked token distribution table on the claims page was not filtered by the profile ID. I had this check in but it must have gotten lost during the rebase from staging.
The locked token distribution table on the claims page was not filtered by the profile ID, so it shows all locked token distributions for each user.
Have some locked token distributions completed and visit the claims page, notice previously all locked token distributions were shown, now only the ones related to the current profile are.
@CryptoGraffe @levity 
https://github.com/coordinape/coordinape/pull/1837
> Locked token distribution gifts on the claim page should be filtered by ID

- src/pages/ClaimsPage/LockedTokenGiftsTable.tsx
We have a test app for testnets, the production app should link to the hedgey.finance production portfolio.
Updated the comparison to use numbers rather than strings as they are saved in the database as numbers.
Visit the claims page and ensure locked token gifts on mainnet, the view hedgeys link points to https://app.hedgey.finance/my-rewards
@levity @crabsinger
> chain_id was being compared as a string

- api-test/hasura/actions/_handlers/createEpoch.test.ts
- api/hasura/actions/_handlers/createEpoch.ts
- src/common-lib/epochs.test.ts
- src/common-lib/epochs.ts
This implements the backend for creating a repeating epoch that starts
on the same day of the same week each month.
This logic accepts a start date, end date, and week number. The start
date and end date must be the same weekday. They also must fall on the
week number of the month. The first week of the month is week 0.
The week number is a necessary extra parameter because it can't
necessarily be inferred from the date. If a following date overflows
into the following month, the inferred week number would cause all
following epochs to start at the beginning of the following month than
the end of the current month, as was originally intended
unit tests are provided
This can merge after #1773 is merged
#1816
> Implement Epoch Monthly backend

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api-test/hasura/actions/_handlers/updateEpoch.test.ts
- api/hasura/actions/_handlers/createEpoch.ts
- api/hasura/actions/_handlers/updateEpoch.ts
- api/hasura/actions/_handlers/updateEpochOld.ts
- api/hasura/actions/actionManager.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/schema/admin/schema.graphql
- hasura/schema/user/schema.graphql
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/gql/mutations.ts
This refactoring utilizes the more configurable epoch structures.
modifying a repeating epoch that has already begun is quite
difficult, so we have to convert that epoch to a one-off, then quietly
create a new repeating epoch using the original config after the
one-off. This flow is already fleshed out in the frontend, but it needs
to be re-integrated.
Unit tests have been written. They are fully integrated, using the
graphql api. Test cases where repeating epochs are modified are not
supported, for the reasons described above.
> Refactor updateEpoch to utilize repeat_data

- api/hasura/actions/_handlers/createUserWithToken.ts
- src/common-lib/circleShareTokens.ts
- src/common-lib/constants.ts
- src/pages/AddMembersPage/AddMembersPage.tsx
- src/pages/AddMembersPage/InviteLink.tsx
- src/pages/AddMembersPage/useCircleTokens.ts
- src/pages/JoinCirclePage/JoinCirclePage.test.tsx
- src/pages/JoinCirclePage/JoinCirclePage.tsx
- src/pages/JoinCirclePage/JoinWithInviteLink.tsx
Our naming of Magic Link clashes with the third party integration with magic.link 
Renamed our magic link to simply "invite link"
Make sure it all looks good in the add members pane and joining by invite link still works
> renaming magic link -> invite link

- src/hooks/useVaultFactory.ts
- src/hooks/useVaultRouter.ts
- src/lib/ethers/addContractWait.ts
- src/pages/ClaimsPage/useClaimAllocation.ts
- src/pages/DistributionsPage/useSubmitDistribution.ts
- src/utils/contractHelpers.ts
Fixes #1836 (on the frontend, at least)
On frontend: catch the TRANSACTION_REPLACED error and update the UI as well as the `pending_vault_transactions` table with the new transaction hash
- Submit any transaction (vault creation, deposit, distribution, claim, etc.) in the UI on Goerli with a very low gas price
- Re-submit it with a normal gas price (e.g. with the "Speed Up" button in MetaMask)
- Wait for the UI to update as normal
> Handle replaced transactions

- hasura/metadata/databases/default/tables/public_epoches.yaml
- hasura/migrations/default/1675295266838_alter_table_public_epoches_add_check_constraint_description_length_constraint/down.sql
- hasura/migrations/default/1675295266838_alter_table_public_epoches_add_check_constraint_description_length_constraint/up.sql
- hasura/schema/user/schema.graphql
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/gql/mutations.ts
- src/pages/HistoryPage/CurrentEpochPanel.tsx
- src/pages/HistoryPage/EpochForm.tsx
Resolves https://github.com/coordinape/coordinape/issues/1904
Move epoch description editing from the main form, into a inline experience.
* Change the epoch description field to be limited between 1 and 100 chars
* Enable graphql API updates for circle admins to modify the epoch description field
- constraints on updates of epoch description:
- must be circle admin, must be undeleted
- epoch must be NOT ended
* Remove description from Epoch form
* Add edit icon and inline editing expereience for epoch descriptions for "current epochs"
Testing:
- API endpoint is secured for non-admin users
- Inline expereience works as expected
- Errors are handled and shown via toast bar
> Edit Epoch Description Inline

- api-test/helpers/users.ts
- src/pages/ContributionsPage/ContributionsPage.tsx
- src/pages/ContributionsPage/index.test.tsx
- src/pages/JoinCirclePage/JoinCirclePage.test.tsx
- src/utils/testing/client.ts
Does not fully deal with #1890 (with a workaround that prevents the race condition from occurring, rather than a more involved rewrite to allow concurrent saving of new contributions)
This is currently stacked on #1923 but could also be merged directly to main.
> disable New button when new contribution is still saving

- api/hasura/cron/epochs.ts
- hasura/migrations/default/1676338256449_correct_repeating_epochs_not_ended/down.sql
- hasura/migrations/default/1676338256449_correct_repeating_epochs_not_ended/up.sql
The repeat data was missing the `type` member
I also improved the error message so we an know exactly what went wrong
without investigating the database.
> Bugfix: Epoch repeat migration

- api-test/hasura/actions/_handlers/updateEpoch.test.ts
- api/hasura/cron/epochs.ts
- hasura/migrations/default/1676338256449_correct_repeating_epochs_not_ended/down.sql
- hasura/migrations/default/1676338256449_correct_repeating_epochs_not_ended/up.sql
This is a bug in the test itself where a date calculation doesn't
account for the timezone as it should.
> Bugfix: set timezone before calculating date in tests

- api-lib/gql/queries.ts
- api-lib/handleOptOutMsg.ts
Fix the way we display the refunds
We were not displaying the refunds correctly, depending on if an opt out is a giver or a sender
@topocount
> fix: Refunds sender and receiver

- api-lib/event_triggers/userAddedDiscordBot.ts
- api-lib/event_triggers/userRemovedDiscordBot.ts
- api-lib/handleOptOutMsg.ts
- api-lib/handleUserAddedMsg.ts
- api-lib/handleUserRemovedMsg.ts
- api-lib/sendSocialMessage.ts
- api-test/hasura/cron/epochs_stubbed.test.ts
- api/hasura/event_triggers/eventManager.ts
- hasura/metadata/databases/default/tables/public_users.yaml
These handlers will be used to dispatch notification info to the discord
bot. Handlers have not been implemented for discord webhooks or
telegram, but it can be done with minimal lift if desired.
This code is still not accessible from within prod and requires integration
with the bot, so that's how it will be tested for now.
> Create User Circle Event Handlers

- src/features/nav/NavCurrentOrg.tsx
- src/ui/Button/Button.tsx
- src/ui/Text/Text.tsx
Vaults page should be viewable by anyone, but you don't see the create vault button if non-admin.  The views look like this:
---------------------------------------
Ignore the color difference in the **current balance** text, I fixed that after the screengrabs
> Bugfix: Always show vaults link in side nav

- api-lib/sendSocialMessage.ts
Change the placeholder to have the actual endpoint of the hosted bot in heroku
> refactor: Add the endpoint for the hosted bot

- .env.example
- api-lib/config.ts
- api-lib/sendSocialMessage.ts
The notification endpoints on the discord bot need to have a way to
reject unauthorized requests. A shared secret allows the discord bot
notification endpoints to authenticate requests in a simple way.
> Add Shared Secret For Discord Bot Notifications

- api/hasura/actions/_handlers/createSampleCircle.ts
Fix invalid epoch repeat data for the sample circle.
The `repeat` column is the old epoch repeat data column, and not used in the new UI. Also, 3 is a value I'm unfamiliar its meaning of.
> Remove invalid repeat data

- src/pages/DiscordPage/DiscordPage.tsx
https://github.com/coordinape/coordinape/pull/1955 was closed mysteriously, creating a new PR
Allow discord bot api users to access/update data with their api key
For example, in order to read a profile
`{"users":{"circle":{"api_keys":{"_and":[{"hash":{"_eq":"X-Hasura-Api-Key-Hash"}},{"read_member_profiles":{"_eq":true}}]}}}}`
Add all permissions to discord bot api users
@topocount
> feat: Give necessary permissons to generated api

- src/common-lib/constants.ts
We'd like the discord bot to have its own entrance
> feat: Add discord bot entrance to the enum

- api-test/hasura/cron/ensNames.test.ts
- api/hasura/cron/ensNames.ts
After investigation I found that the names are always changed correctly but but the profiles fetched for comparing is not updated
I added a delay of 500ms before fetching
> fix ensNames test

- api-test/hasura/cron/epochs_stubbed.test.ts
- api/hasura/actions/_handlers/endEpoch.ts
- api/hasura/cron/epochs.ts
Trigger the discord bot when an epoch ends, not when one it's ending.
Use `endEpoch` rather than `notifyEndEpochs`
Closes https://github.com/coordinape/discord-bot/issues/89
> fix: Use endEpoch rather than notifyEndEpochs

- api-lib/handleOptOutMsg.ts
- api-lib/handleUserAddedMsg.ts
- api-lib/handleUserRemovedMsg.ts
- api-lib/sendSocialMessage.ts
Have the profile name in the discord message
Send the profile name for the following events:
* user added;
* user removed; and
* user opts out.
Complements https://github.com/coordinape/discord-bot/pull/95
@topocount 
Closes https://github.com/coordinape/discord-bot/issues/86
> feat: Send profile name when user added, removed or opts out

- api/hasura/cron/epochs.ts
Fix epoch number coming as `null`
> fix: Epoch number

- api-lib/sendSocialMessage.ts
We are POST a bunch of requests that should not go through unless the channel is the discord bo
```
2023-02-25T12:01:23.336575+00:00 heroku[router]: at=info method=POST path="/api/epoch/undefined" host=coordinape-discord-bot.herokuapp.com request_id=f7aad109-e58c-4cfb-8eff-0dfdeed534e9 fwd="20.42.13.0" dyno=web.1 connect=0ms service=1ms status=404 bytes=403 protocol=https
2023-02-25T12:01:28.307190+00:00 heroku[router]: at=info method=POST path="/api/epoch/undefined" host=coordinape-discord-bot.herokuapp.com request_id=09cc83bc-e70d-4609-a7f2-564cd54aa1be fwd="20.42.13.0" dyno=web.1 connect=0ms service=1ms status=404 bytes=403 protocol=https
2023-02-25T12:01:31.943736+00:00 heroku[router]: at=info method=POST path="/api/epoch/undefined" host=coordinape-discord-bot.herokuapp.com …
```
> fix: Check if channel is discord bot

- src/lib/zod/index.ts
There are pages other than the circle admin page that call updateCircle and they don't include all the fields
> handling saving circle w/o guild fields

- api-lib/validateENS.ts
- api/hasura/actions/_handlers/createUsers.ts
- api/hasura/actions/_handlers/updateProfile.ts
- api/hasura/cron/ensNames.ts
- src/components/EditProfileModal.tsx
- src/components/MainLayout/CreateUserNameForm.tsx
- src/lib/zod/formHelpers.ts
- src/pages/AddMembersPage/NewMemberList.tsx
issue raised by @crabsinger :
if you use the Add Members page, and use a ENS .eth in the Name field, we won't verify it, and then it will be set on the user. 
1- verify the list of names on FE and BE
go to member page and try to add a mix of addresses with correct and wrong ens names
front-end
back-end if front-end is bypassed
> validate add members list ens names

- api-test/hasura/cron/epochs_stubbed.test.ts
- api/hasura/cron/epochs.ts
Update the epoch start notification so cron knows the notification has already been sent
Update the epoch start notification after the social message has been sent
@CryptoGraffe 
Closes https://github.com/coordinape/discord-bot/issues/98
> fix: Update epoch start notification after sending social message

- hasura/migrations/default/1677871430662_drop_index_activities_index_created_at/down.sql
- hasura/migrations/default/1677871430662_drop_index_activities_index_created_at/up.sql
- src/features/activities/useInfiniteActivities.tsx
created_at is the intended sort but we were sorting by id
> changing activities sort to created_at vs id

- src/features/auth/useFinishAuth.ts
- src/features/auth/useLoginData.ts
- src/lib/gql/mutations.ts
- src/pages/CircleAdminPage/RemoveCircleModal.tsx
- src/pages/CreateCirclePage/CreateCircleForm.tsx
this stores profile data locally. i've added it to ~the existing zustand auth store for now~ react-query, and to avoid bikeshedding about the structure of local data storage, i am just storing the entire `profiles_by_pk` subtree of the fetchManifest query.
in the short term, this will be used to determine whether the user is a member of a given org, without incurring additional requests. in the longer term it will also help us continue to move away from Recoil.
> store profile data globally

- api-test/hasura/actions/_handlers/createUserMutation.test.ts
- api/hasura/actions/_handlers/createUserMutation.ts
- api/hasura/actions/_handlers/createUserWithToken.ts
Name was still being passed in to create user, no more.
> Fix create user name

- api-test/hasura/cron/pGiveHistoricalGen.test.ts
- api/hasura/actions/_handlers/allocationCsv.test.ts
- api/hasura/actions/_handlers/allocationCsv.ts
Fix CSV exporting user name error
Upon trying to export allocations CSV users get the following error:
`GQL Error (validation-failed): field 'name' not found in type: 'users' at $.selectionSet.circles_by_pk.selectionSet.users.selectionSet.name`
The error is caused by fetching users.name field which is removed
Go to distribution page of an ended epoch and try export CSV
> Fix CSV export user name field

- hasura/metadata/databases/default/tables/public_activities.yaml
- hasura/metadata/databases/default/tables/public_contributions.yaml
Allow activities and contributions  select permission to circle org members
Update Hasura perms.
With activity enabled, add a user as org member but not circle member, and you should see contributions from circles, and activities for circles.
> Allow activities and contributions to circle org members

- hasura/metadata/databases/default/tables/public_users.yaml
- src/lib/gql/clientPermissions.test.ts
we already exclude soft-deleted users and circles themselves, but weren't excluding users associated with soft-deleted circles
> exclude users of deleted circles from all queries

- src/config/features.ts
- src/features/nav/NavCurrentOrg.tsx
- src/features/nav/SideNav.test.tsx
- src/features/nav/getNavData.ts
- src/features/nav/permissions.ts
- src/features/orgs/OrgMembersPage.tsx
- src/features/orgs/OrgMembersTable.tsx
- src/features/orgs/getOrgMembersData.ts
- src/features/orgs/index.tsx
- src/pages/OrgMembersPage/index.tsx
- src/routes/paths.ts
- src/routes/routes.tsx
resolves #2003 
1- Add Members Nav item to organization nav
2- Add OrgMembersPage to display list of org_members
1- you need to enable "org_view" feature use `localStorage.setItem('feature:org_view','true')` in browser console
2- open a terminal in coordinape folder and run `yarn repl` 
3-  use `createMembersFromCircles(OrgId:number)` inside the repl to populate org_members table for that org
> org members page

- src/features/nav/SideNav.tsx
- src/pages/GivePage/MyGiveRow.tsx
added some bottom padding to the logo so overflow isn't right at the edge of the logo.
> Minor spacing fix for sidenav

- api/hasura/actions/_handlers/createEpoch.ts
- src/common-lib/epochs.test.ts
allow time diff to be off by one hour during  checking for epoch end date to account for southern hemisphere DST switching during next epoch
1-change your time zone to UTC+13 and create a monthly or weekly epoch that includes the 2nd of April 2023
> fix creating epoch during if DST is included

- hasura/metadata/databases/default/tables/discord_user_api_tokens.yaml
- hasura/metadata/databases/default/tables/tables.yaml
- hasura/migrations/default/1678981500944_create_table_discord_user_api_tokens/down.sql
- hasura/migrations/default/1678981500944_create_table_discord_user_api_tokens/up.sql
To support the next phase of the Discord bot,, we want to support users creating contributions via the bot. This requires circle specific user api tokens. Since a user can belong to multiple circles, we need a new table for this.
This PR creates a new table in the discord schema to store these api_tokens for users.
> Create discord.user_api_tokens table

- src/features/nav/NavCircleItem.tsx
- src/features/nav/NavCurrentOrg.tsx
- src/features/nav/NavItem.tsx
- src/features/nav/NavLabel.tsx
- src/features/nav/NavLogo.tsx
- src/features/nav/NavOrgs.tsx
- src/features/nav/NavProfile.tsx
- src/features/nav/SideNav.tsx
- src/pages/CirclesPage/CirclesPage.tsx
* tighten up nav padding for breakpoints below `lg`
* remove chevron indicator from circles in nav list
* hide `Home` button below `lg`,  show again for `mobile`
> Small-ish screen nav breakpoint updates

- src/components/MainLayout/getMainHeaderData.ts
- src/hooks/gql/useVaults.ts
- src/lib/gql/mutations/vaults.ts
- src/pages/HistoryPage/HistoryPage.tsx
- src/pages/HistoryPage/getHistoryData.ts
- src/pages/VaultsPage/VaultRow.tsx
- src/pages/VaultsPage/VaultsPage.tsx
- src/routes/paths.ts
- src/routes/routes.test.tsx
- src/routes/routes.tsx
Removed all organization vaults content
Error:
1- creating a new circle with a new org (without vaults) will have a helper banner with a link to vaults page
2- Clicking this link will crash the page with the following error
3- it's caused by trying to access an org that's not fetched yet.
Fix:
1- Removed /vaults route and content
2- made all vaults routes specific to organizations
1- create a new circle with a new org
2- navigate  to Epochs/Overview page and click create a new vault
> Remove all orgs vaults routes

- src/pages/HistoryPage/EpochForm.tsx
resolves #2060
Make sure that current unit test passes.
1- created an epoch that starts in the past
2- created a future epoch and periodic epochs that starts in the past to check collision
> allow epochs to start 100 days in the past

- hasura/metadata/databases/default/tables/public_contributions.yaml
Fix typo to allow API to work if header is set.
> Fix typo in permissions

- api-lib/findUser.ts
- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api-lib/orgAdmin.ts
- api-test/hasura/actions/_handlers/createOrgMembers.test.ts
- api-test/helpers/index.ts
- api-test/helpers/org_members.ts
- api/hasura/actions/_handlers/createOrgMembers.ts
- api/hasura/actions/actionManager.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/migrations/default/1680036748448_create_org_share_tokens_table/down.sql
- hasura/schema/admin/schema.graphql
- hasura/schema/user/schema.graphql
- scripts/repl/org_membership.ts
- src/features/auth/useFinishAuth.ts
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
Create an action handler to support adding org_members.
Test these variations:
> Orgs Backend: createOrgMembers action handler

- src/features/activities/reactions/ReactionCounts.tsx
- src/features/activities/reactions/ReactionOptions.tsx
Upon adding a reaction to an activity the following error is received:
"instrument.ts:124 Error: Uniqueness violation. duplicate key value violates unique constraint "reactions_profile_id_activity_id_reaction_key"
at index.ts:54:17'
Cause:
1- Create Reaction was triggered twice 
Fix:
Moved onClick to the checkbox input 
Go to activity stream, add a reaction,
Expect: 1 createMutation request fired
> Fix triggering addReaction twice

- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- api-test/hasura/actions/_handlers/createUserWithToken.test.ts
- api-test/hasura/actions/_handlers/deleteOrgMember.test.ts
- api/hasura/actions/_handlers/createUserWithToken.ts
- api/hasura/actions/_handlers/deleteOrgMember.ts
- api/hasura/actions/actionManager.ts
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/schema/admin/schema.graphql
- hasura/schema/user/schema.graphql
- scripts/db_clean.ts
- scripts/seed_hasura.sh
- src/common-lib/circleShareTokens.ts
- src/common-lib/shareTokens.ts
- src/features/orgs/OrgMembersTable.tsx
- src/features/orgs/useOrgInviteToken.ts
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/lib/zod/index.ts
- src/pages/AddMembersPage/useCircleTokens.ts
- src/pages/JoinPage/JoinPage.test.tsx
- src/pages/JoinPage/JoinPage.tsx
- src/pages/MembersPage/index.tsx
- src/pages/OrgMembersPage/index.tsx
This adds a button in each row on the Org Members page, visible only when that row's member is in 0 circles and the viewing user is an org admin, to remove the member from the org (soft-deleting).
Add a new member to the org, then use the button to remove them. Verify that they no longer appear in the members list (immediately after, and also upon page reload).
> allow org admins to remove members

- hasura/metadata/databases/default/tables/public_users.yaml
We need to access the `id` of the user in order to insert a contribution https://github.com/coordinape/discord-bot/pull/116
Add the `id` column select permission to the role discord-bot in the users table
`create_contributions` was already being requested here https://github.com/coordinape/coordinape/blob/main/src/pages/DiscordPage/DiscordPage.tsx#L71
@crabsinger @CryptoGraffe
> feat: Add id column permission to users table

- src/pages/ContributionsPage/ContributionsPage.tsx
Upon adding a new contribution and closing the drawer before saving, an error is returned in console
1- The error is caused by calling reset() from the form (react-hook-form) as it tries to update the contribution with empty description
2- reset() is unnecessary because the form is reintialized with the new default data on re-rendering
1- Add a contribution and quickly close the drawer before saving like the below gif
>  fix add contribution description error 

- api-lib/circleAdmin.ts
- api-lib/event_triggers/createCircleCRM.ts
- api-lib/event_triggers/createNomineeTelegram.ts
- api-lib/event_triggers/createVouchedUser.ts
- api-lib/orgAdmin.ts
- api-lib/userDeleter.ts
- api/hasura/actions/_handlers/createCircle.ts
- api/hasura/actions/_handlers/createNominee.ts
- api/hasura/actions/_handlers/createSampleCircle.ts
- api/hasura/actions/_handlers/createUserWithToken.ts
- api/hasura/actions/_handlers/createVault.ts
- api/hasura/actions/_handlers/createVaultTx.ts
- api/hasura/actions/_handlers/deleteContribution.ts
- api/hasura/actions/_handlers/deleteOrgMember.ts
- api/hasura/actions/_handlers/getGuildInfo.ts
- api/hasura/actions/_handlers/linkDiscordUser.ts
- api/hasura/actions/_handlers/logoutUser.ts
- api/hasura/actions/_handlers/markClaimed.ts
- api/hasura/actions/_handlers/updateAllocations.ts
- api/hasura/actions/_handlers/updateContribution.ts
- api/hasura/actions/_handlers/updateProfile.ts
- api/hasura/actions/_handlers/updateTeammates.ts
- api/hasura/actions/_handlers/updateUser.ts
- api/hasura/actions/_handlers/uploadOrgLogo.ts
- api/hasura/actions/_handlers/uploadProfileAvatar.ts
- api/hasura/actions/_handlers/uploadProfileBackground.ts
- api/hasura/actions/_handlers/vouch.ts
- api/hasura/actions/actionManager.ts
See commit comments. Just taking advantage of the existing centralization in `actionManager` and `eventManager` to define middleware there rather than in each handler file.
> deduplicate middleware calls

- src/pages/HistoryPage/Notes.tsx
Here's the bug:
blank ones should't be included
> Bugfix: Filter epoch statements to exclude blank ones

- src/features/nav/NavLabel.tsx
org and circle labels in side nav did not have pointer cursor.
Hovering over the labels in side nav should inherit the cursor style of the parent, not use browser default.
> Minor UI fix for sidenav label cursor hover

- .env.example
- hardhat/deploymentInfo.json
- hardhat/dist/deploymentInfo.json
- hardhat/dist/hardhat.config.js
- hardhat/hardhat.config.ts
- hardhat/package.json
- hardhat/scripts/deploy/03-cosoul/00-cosoul-deploy.ts
- src/config/env.ts
- src/features/cosoul/chains.ts
- add support for deploying the `CoSoul` contract on Optimism Goerli via `yarn deploy:optimismgoerli`.
- adds optimism goerli deploy to deploymentInfo and dist/ and sets up app for testing on goerli
Testing:
- go to staging: https://coordinape-git-add-deploy-command-coordinape.vercel.app/
- mint a cosoul on goerli
- rejoice
> Setup optimismGoerli deploy and contracts

- src/features/cosoul/api/cosoul.ts
Fix gas prices in CoSoul syncing.
Ethers hardcodes arbirtary values for EIP-1559 transactions: https://github.com/ethers-io/ethers.js/blob/master/packages/abstract-provider/src.ts/index.ts#L252-L253
these hardcoded values are VERY high and are costing us a ton of extra money to sync CoSoul data. Override the defaults with much smaller values.
> Fix gas prices in CoSoul syncing

- api-lib/tenderlySignature.ts
- api/cosoul/verify.test.ts
- api/cosoul/verify.ts
- api/hasura/actions/_handlers/syncCoSoul.ts
Change tenderly webhook API to:
- add all on-chain cosouls to our cosouls table
- If no profile exists, that's fine, still add it.
Added test coverage
> Setup Tenderly CoSoul Webhooks

- src/features/cosoul/CoSoulButton.tsx
Resolves https://coordinape.sentry.io/issues/4367559158/?project=5863782&query=is%3Aunresolved+gasSettings&referrer=issue-stream&statsPeriod=14d&stream_index=0
Fix bug where we added gasSettings key to chain options, but also use this object to add new chains to metamask, which causes error because gasSettigns isn't known.
> Fix switch network button

- api-lib/contributions.ts
- api-test/hasura/actions/_handlers/updateContribution.test.ts
Changing contributions validation so that you can edit/delete contributions from past epochs
> Can edit past epoch contributions

- src/components/ToastContainer.tsx
> 🕷️ bugfix: flexible width toast for mobile

- src/routes/hooks.ts
Disable Mixpanel tracking for unauthenticated users
> Don't track unauthed views to MP

- src/pages/GivePage/GiveRow.tsx
fixing this:
now looks like this:
> bugfix: give page allocation breakpoint fix

- src/features/colinks/RecentCoLinkTransactions.tsx
- src/features/colinks/SkillTag.tsx
- src/pages/colinks/ExplorePage.tsx
- src/ui/MarkdownPreview/MarkdownPreview.tsx
bugfix for:
* skill tag overflow
* markdown table overflow
* markdown unbroken string overflow
* preserve natural word breaks
> overflow bug squash in markdown and skill tags

- src/components/MainLayout/CreateUserNameForm.tsx
- src/features/colinks/CoLinksStats.tsx
- src/features/colinks/SkillTag.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/pages/colinks/ExplorePage.tsx
- src/pages/colinks/explore/CoLinksMember.tsx
- src/pages/colinks/explore/SimpleBuyButtonWithPrice.tsx
- src/ui/MarkdownPreview/MarkdownPreview.tsx
- src/ui/Text/Text.tsx
* use `overflowWrap: 'anywhere',` to break words instead of deprecated break-word
* fix when people be adding long names
> 🐞 Text overflow

- src/features/colinks/wizard/WizardCoSoul.tsx
fix mobile minting button responsiveness
Mint Cosoul is not working on mobile. the button is not responsive or crashing the app although the same button works on main app.
CoLinksMintPage is covering the button.
try creating a new user on colinks on one of mobile wallets browser.
minting button should be unresponsive or crashing the app.
to test it's working you can use the preview link to test on mobile apps or in normal browser using responsive design mode
> fix minting button responsiveness on mobiles

- src/features/activities/replies/ReplyForm.tsx
- src/features/colinks/PostForm.tsx
Also switch post storage to sessionStorage
Each tab is unique and has its own storage. If you "duplicate" a tab, it copies storage from first tab but does not share or sync updates between them.
Seems to work fine.
> Store pending replies in sessionStorage

- api-lib/config.ts
- api-lib/email/postmark.ts
- api-lib/email/unsubscribe.ts
- api-test/email/unsubscribe.test.ts
- api-test/hasura/cron/epochs_emails_stubbed.test.ts
- api/email/unsubscribe/[unsubscribeToken].ts
- api/hasura/actions/_handlers/addEmail.ts
- api/hasura/actions/_handlers/inviteWaitingList.ts
- api/hasura/actions/_handlers/requestInviteCode.ts
- api/hasura/cron/colinksNotificationEmails.ts
- api/hasura/cron/dailyReportEmail.ts
- api/hasura/cron/epochs.ts
- api/hasura/cron/hourlyReportEmail.ts
- scripts/repl.ts
- scripts/serve_dev.ts
- src/pages/colinks/UnsubscribeEmailPage.tsx
- src/routes/coLinksRoutes.tsx
- src/routes/paths.ts
Create one click link to unsubscribe from receiving emails:
1- generate a token based on profile Id, email and email type
2- generate a link with the token and send it to post mark
3- adjust postmark template
4- create a landing page for the unsubscribe link
Allow users to easily unsubscribe from emails
The production templates on postmark needs to be updated as well
1- A new layout needs to be updated "CoLinks with one click unsubscribe"
this layout will have the ubsubscribe link at the footer
2- CoLinks Unread Notifications template needs to use this new layout instead.
> Oneclick unsubscribe

- src/ui/MarkdownPreview/MarkdownPreview.tsx
Here's the bug:
fixed to be stacked like this:
> ui bugfix: md block image

- src/ui/Modal.tsx
bug:
pass loader prop into dialog.content
> UI Bugfix: wrong modal style for loading indicator

- _api/email/unsubscribe/[unsubscribeToken].ts
- _api/hasura/cron/epochs.ts
- api-lib/email/postmark.ts
- api-lib/email/unsubscribe.ts
- api-test/email/unsubscribe.test.ts
- api-test/hasura/cron/epochs_emails_stubbed.test.ts
- src/pages/UnsubscribeEmailPage/UnsubscribeEmailPage.tsx
- src/routes/coLinksRoutes.tsx
- src/routes/giveRoutes.tsx
- src/routes/paths.ts
add one click unsubscribe to epoch notifications emails
1- for notifyEndEpochs and notifyStartEpochs: the users query is filtered by app_emails flag value
2- for endEpoch the users are filtered after fetching because the full list of users is required for other calculations
3- updated the emailType except for the already in use type 'notification' which is used for colinks emails
4- updated postmark functions and template
Tested  unsubsribe link for all epochs type and for colinks notifications
On postmark, layout: "Basic with one click unsubscribe" with alias basic-one-click-unsubscribe should be copied to production server and used for Epoch Ended, Epoch Ending Soon and Epoch Started templates
> one click unsubscribe to epoch notifications emails

- src/features/activities/useInfiniteActivities.tsx
- src/features/colinks/CoLinksContext.tsx
- src/features/colinks/CoLinksNav.tsx
- src/features/colinks/FaviconNotificationBadge.tsx
Fixes two whole page re-render bugs
1. useNotificationCount in the Provider causes everything nested in the provider (whole app) to rerender. Fixed by wrapping in Component
See
https://www.developerway.com/posts/why-custom-react-hooks-could-destroy-your-app-performance
for a description of the issue and why this resolves it
2. Fix activity list re-rendering on new data fetching, and changes it to only re-render when new data is fetched via `notifyOnChangeProps`
> Wrap useNotificationCount query and favicon changing into sub component so it doesn't cause full app re-renders on every refetch.

- src/components/ComboBox.tsx
- src/components/SkillComboBox/SkillComboBox.tsx
Not sure why this "be the first to add" is appearing above the list, but we can pin it to the bottom with css.  
buggy prod:
absolute pin:
Hopefully this will work in prod
> UI Bug: "first to add" button position

- hasura/migrations/default/1710180069058_alter_table_public_colinks_gives_add_column_cast_hash/down.sql
- hasura/migrations/default/1710180069058_alter_table_public_colinks_gives_add_column_cast_hash/up.sql
- hasura/migrations/default/1710180075129_alter_table_public_colinks_gives_alter_column_activity_id/down.sql
- hasura/migrations/default/1710180075129_alter_table_public_colinks_gives_alter_column_activity_id/up.sql
- hasura/migrations/default/1710180175525_alter_table_public_colinks_gives_add_check_constraint_give_object_constraint/down.sql
- hasura/migrations/default/1710180175525_alter_table_public_colinks_gives_add_check_constraint_give_object_constraint/up.sql
Allow colinks_give to be associated with a cast hash. This can be used to lookup the cast via API.
> DB: give associates to a Farcaster cast

- _api/frames/getFramePostInfo.tsx
- _api/frames/router.tsx
- src/config/webAppURL.ts
* Adds frame validation for !IN_DEVELOPMENT. Tested w/ the warpcast frame debugger.
* Added ability  in local dev to force a web app url for testing w/ ngrok
* Forced image/png content type for img return. This fixes an error in the warpcast debugger about missing content type.
> validate against neynar, fake webapp url, force content type

- _api/hasura/cron/syncCoSouls.ts
Reverts coordinape/coordinape#2905
This was accidentally causing full sync of all co-souls. We want to do that, but only after the new ones are synced.
> Revert "fix sync date"

- _api/hasura/cron/bigQuestionEmails.ts
- _api/hasura/cron/colinksNotificationEmails.ts
- api-lib/HttpError.ts
- api-lib/email/postmark.ts
set verified_at to null if the user is rejecting colinks emails
I tried it by throwing an error with 'spam complaint' and the notified email got unverified
> Colinks handle inactive emails

- api-lib/event_triggers/createNotificationReplies.ts
- src/pages/colinks/NotificationsPage.tsx
#replaces #2860 
when a user replies to a post you have replied to before you will receive a notification
Create a post by a user and comment on it with two other users and then comment by the post creator, each user will receive a different notification as per by the screenshots
Commenter 1
Thread owner
Commenter 2
1- When a user reply to a post, get all other replies to that post and their posters.
2- notify other replies posters.
> add notifications for others replies

- _api/hasura/event_triggers/eventManager.ts
- api-lib/event_triggers/createNotificationReplyReactions.ts
- api-lib/gql/__generated__/zeus/const.ts
- api-lib/gql/__generated__/zeus/index.ts
- hasura/metadata/databases/default/tables/public_notifications.yaml
- hasura/metadata/databases/default/tables/public_replies.yaml
- hasura/metadata/databases/default/tables/public_replies_reactions.yaml
- hasura/metadata/databases/default/tables/tables.yaml
- hasura/migrations/default/1717308575449_create_table_public_replies_reactions/down.sql
- hasura/migrations/default/1717308575449_create_table_public_replies_reactions/up.sql
- hasura/migrations/default/1717844615993_alter_table_public_notifications_add_column_reply_reaction_id/down.sql
- hasura/migrations/default/1717844615993_alter_table_public_notifications_add_column_reply_reaction_id/up.sql
- hasura/schema/admin/schema.graphql
- hasura/schema/user/schema.graphql
- src/features/activities/replies/RepliesBox.tsx
- src/features/activities/replies/ReplyReactionBar.tsx
- src/features/activities/replies/mutations.ts
- src/lib/gql/__generated__/zeus/const.ts
- src/lib/gql/__generated__/zeus/index.ts
- src/pages/colinks/NotificationsPage.tsx
Reactions:
notifications:
As long as the user can see the reply, he should be able to react.
I considered that if the reply is deleted, the user is muted, or the last key is sold "no visibility and the data is not refreshed yet, it won't create the reaction
The insert permission is as follows:
{"reply":{"_and":[{"deleted_at":{"_is_null":true}},{"_not":{"profile_public":{"mutes":{"profile_id":{"_eq":"X-Hasura-User-Id"}}}}},{"_or":[{"private_stream_visibility":{"profile_id":{"_eq":"X-Hasura-User-Id"}}},{"activity":{"big_question_id":{"_is_null":false}}}]}]}}
> add replies_reactions table

- src/features/guild/GuildSelector.test.tsx
- src/features/guild/guild-api.ts
update guild.xyz apis
v1 of guild.xyz is deprecated
I created a new guild testingco and integrated it to one of the test circles then tried to add users by the guild link
it only passed when the user has the required role
> update guild.xyz api

- src/pages/colinks/LaunchPage.tsx
Previously an infintie loader could occur if you connect your wallet,
but do not have an auth token. This fixes that by redirecting to login
in that case.
> Bugfix: launch page redirects if logged out

- .env.example
- _api/hasura/actions/_handlers/syncCoSoul.ts
- _api/hasura/cron/cosoulMinter.ts
- _api/hasura/cron/syncCoSoulReputation.ts
- _api/hasura/cron/syncCoSouls.ts
- api-lib/config.ts
- api-lib/frames/personas/PersonaOneFrame.tsx
- api-lib/provider.ts
- api-lib/signature.ts
- api-lib/viem/contracts.test.ts
- api-lib/viem/contracts.ts
- api-lib/viem/walletClient.ts
- hardhat/constants.ts
- hardhat/scripts/start-ganache.sh
- package.json
- scripts/env.sh
- scripts/repl.ts
- scripts/serve_dev.ts
- src/config/env.ts
- src/features/auth/magic.tsx
- src/features/cosoul/api/cosoul.test.ts
- src/features/cosoul/api/cosoul.ts
- src/features/magiclink/RainbowMagicConnector.ts
- src/features/wagmi/config.ts
- src/lib/zod/formHelpers.ts
- src/utils/provider.ts
- src/utils/viem/chains.ts
- src/utils/viem/contracts.ts
- src/utils/viem/publicClient.ts
Alchemy (finally) supports multiple chains with one API key, so we can vastly simplify our env vars which use Alchemy tokens.
We have two API tokens:
VITE_FE_ALCHEMY_API_KEY - this is visible to clients and users and has domain origin limitations set on its use. Only use this from the FE where requests will have an origin.
BE_ALCHEMY_API_KEY - this is a private API_KEY and should not be exposed to clients, it is used for backend requests without origin.
Change all contract instance code to use appropriate versions of frontend or backend clients.
> Cleanup and Refactor Alchemy tokens

- _api/hasura/actions/_handlers/getCasts.ts
- hasura/metadata/cron_triggers.yaml
- hasura/migrations/default/1725485388641_modify_enriched_casts_func_ignore_replies/down.sql
- hasura/migrations/default/1725485388641_modify_enriched_casts_func_ignore_replies/up.sql
- hasura/migrations/default/1725485496450_delete_fk_public_activities_activities_cast_id_fkey/down.sql
- hasura/migrations/default/1725485496450_delete_fk_public_activities_activities_cast_id_fkey/up.sql
- hasura/migrations/default/1725485516620_set_fk_public_activities_cast_id/down.sql
- hasura/migrations/default/1725485516620_set_fk_public_activities_cast_id/up.sql
- hasura/migrations/default/1725485555694_delete_enriched_casts_with_parents/down.sql
- hasura/migrations/default/1725485555694_delete_enriched_casts_with_parents/up.sql
casts, delete reply casts, fix 'latest cast', ignore reply casts when inserting into enriched_casts
> reply cast cleanup

- _api/hasura/actions/_handlers/syncCoSoul.ts
We were having a race condition in syncCoSoul where the alchemy webhook
would fire first, deleting the cosouls record from db, then the handler
syncCoSoul fires, and but does not find any cosoul to delete, and
errors. This changes makes the handler idempotent and handle the case
where the cosoul is already deleted (by the webhook).
> Fix race in syncCoSoul

- _api/hasura/actions/_handlers/createCoLinksGive.ts
Fixed bu
in fetchPoints function where invalid negative array index was being used for
EMISSION_TIERS. Changed from EMISSION_TIERS[-1] to EMISSION_TIERS[EMISSION_TIERS.lengt
- 1]
> Fix: Correct array indexing for emission tiers

- package.json
- src/lib/anongql/.gitignore
- src/lib/anongql/.npmignore
- src/lib/anongql/README.md
- src/lib/anongql/anonClient.ts
- src/lib/anongql/index.ts
- src/lib/anongql/package.json
- src/lib/anongql/tsconfig.json
Exports the anongql client from the coordinape repo so other projects can use it. Unfortunately this carries all along the coordinape dependencies with it. We could potentially break this out at some point. 
Here is how to use it (example in the fv2 project):
```
pnpm add github:coordinape/coordinape#export_anongql
```
then in code:
```
import { anonClient } from 'coordinape-app/anongql';
```
works!
> export anongql

- src/features/points/emissionTiers.ts
This PR adjusts the GIVE emission rates, which are tiered based on a user's CO token balance. The token thresholds, multipliers, and give caps for each tier have been updated to create a more conservative emission system with an additional low tier.
The previous emission tiers were not well-aligned with the desired incentive structure for holding CO tokens. This update aims to encourage token acquisition and holding by providing more distinct tiers and clearer benefits for users as they accumulate more tokens. The new structure provides a smoother progression and rewards users more effectively for their stake in the ecosystem.
**Testing:**
Verify on a staging environment that users with different CO token balances are assigned the correct emission tier and give cap as defined in the new …
> change GIVE emission rates to more conservative amounts

- _api/hasura/actions/_handlers/createCoLinksGive.ts
- _api/hasura/actions/_handlers/deleteCoLinksGive.ts
- api-lib/tokenBalances.ts
- src/features/points/getAvailablePoints.ts
- src/features/points/usePoints.tsx
This change updates the application to check for a user's `CO` token balance on both the Ethereum and Base chains. It aggregates the balances from both chains to calculate a user's total `CO` token holdings, which is then used to determine their "GIVE" accrual rate and capacity.
Previously, the application only checked for a user's `CO` token balance on Ethereum. With the token also existing on Base, this change was necessary to ensure the application accurately reflects a user's total holdings across all supported chains. This provides a correct and consistent user experience, regardless of where their tokens are held.
The implementation involved several key steps:
1.  **Enabled Base Chain Support:** The Alchemy configuration in `api-lib/tokenBalances.ts` was updated to include …
> Detect base CO and add to total CO token balance

- _api/give/balance/fid/[fid].ts
- _api/give/balance/fid/[fid]/debug.ts
- scripts/serve_dev.ts
- vercel.json
FID-Based GIVE Balance API Implementation Plan  
Create a new API endpoint that takes a Farcaster FID, fetches all associated wallet addresses via Neynar, aggregates CO token balances across all chains, and returns GIVE balance calculations.
Main API: /api/give/balance/fid/3
- Returns standard GIVE balance format with real user data
- Aggregates CO tokens across all user addresses
Debug API: /api/give/balance/fid/3/debug
- Shows complete calculation breakdown
- Displays all addresses being checked: 0x187c7b0393ebe86378128f2653d0930e33218899,
0x6b0bda3f2ffed5efc83fa8c024acff1dd45793f1, 0xd7029bdea1c17493893aafe29aad69ef892b8ff2
- Shows Farcaster user info + Coordinape profile mapping
- Real points balance from profile: 1296000 points
> Neynar multiple acct co
