src/components/TeammateCard/TeammateCard.tsx
src/theme/colors.ts
src/types/material-ui.d.ts

Had talked to Alex about using a less contrasting color for the admin tag than black

+character limit on notes & update color

---

public/index.html

#1 Add plausbile analytics to all pages
Add https://plausible.io analytics
Reviewers: @exrhizo @levity

Add plausbile analytics to all pages

---

src/pages/LandingPage/LandingPage.tsx
src/theme/createLandingPageTheme.ts
src/theme/index.ts

Also added another style of button from the designs,
TODO: switch it out in all the places that use that style

Move start a circle button to top

---

src/components/LoadingModal/LoadingModal.tsx

I'm working my way to the login process
You'd mentioned that by having the white box, the loader looked like it was going to load something in it, no longer.

Dont imply that the loader is getting a modal

---

src/index.tsx

Sentry to ignore unactionable errors

---

.gitignore
hardhat/package.json
hardhat/tsconfig.json
hardhat/yarn.lock

Created `dist` package for `coordinape/hardhat` so we can easily link it in other modules

feat: add build commands for hardhat

---

src/pages/AdminPage/AdminPage.tsx

Scratching my own itch here... I think this looks better
Before
After

simplify title on admin page

---

src/forms/AdminVaultForm.tsx
src/pages/VaultsPage/AllocateModal.tsx
src/pages/VaultsPage/CreateVaultModal.tsx
src/pages/VaultsPage/DepositModal.tsx
src/pages/VaultsPage/EditModal.tsx
src/pages/VaultsPage/FundModal.tsx
src/pages/VaultsPage/HasVaults.tsx
src/pages/VaultsPage/WithdrawModal.tsx

I am merging this now because it is blocking my API PR and this code isn't in production

Remove hooks from the vault modals, which aren't needed

---

src/components/ProfileCard/ProfileCard.tsx
src/components/ReadMore/ReadMore.tsx
src/components/index.ts

adds read more component for profile card

---

src/pages/ProfilePage/ProfilePage.tsx

Remove 'No epoch statement' message

---

src/pages/AdminPage/AdminCircleModal.tsx
src/types/api.circle.d.ts
src/types/api.d.ts

adds auto_opt_out to edit circle admin

---

src/components/ApeInfoTooltip/ApeInfoTooltip.tsx
src/components/ProfileCard/GiftInput.tsx
src/components/ProfileCard/ProfileCard.tsx
src/components/ReadMore/ReadMore.tsx
src/hooks/useMobileDetect.ts

refactors ReadMore component to show tooltip

---

src/index.tsx

The app was disabled for a server upgrade, this re-enables it.

Re-enable after server upgrade

---

src/index.tsx

Reverts coordinape/coordinape#328

Revert "Update server message"

---

src/forms/AdminUserForm.tsx

https://github.com/coordinape/coordinape/issues/336
Needs backend change to complete:
https://github.com/coordinape/coordinape-backend/pull/71

Fix default opt status

---

src/components/ReceiveInfo/ReceiveInfo.tsx
src/pages/AdminPage/AdminUserModal.tsx
src/recoilState/db.ts

https://github.com/coordinape/coordinape/issues/333

Fix Received active epoch no gift & myEpoch&Circle

---

package.json
src/pages/AllocationPage/AllocationGive.tsx
src/pages/AllocationPage/AllocationPage.tsx
src/recoilState/allocation.test.tsx
src/routes/allocation.ts
src/types/recoil.d.ts
yarn.lock

Fixes header and sort text that used 'Give' instead of custom token name #342

---

src/hooks/useApiAdminCircle.ts
src/pages/AdminPage/AdminPage.tsx
src/services/api.ts

Change download CSV to use API instead of direct link (#335)

---

src/pages/ProfilePage/ProfilePage.tsx

- Change skill tag max count to 50 in ProfilePage, adjust styles

show all skill tags in ProfilePage

---

README.md

As per https://discord.com/channels/845400066532704256/898299792575299654/928017825103245363

add hardhat setup script note in readme

---

api/time.ts
src/services/api.ts

to work around an issue where a user has their clock set to a different time

get current time for login from serverless function

---

hardhat/deploymentInfo.json
src/components/WalletAuthModal/WalletAuthModal.tsx

added coinbase wallet support.
Fixes #254

add coinbase wallet

---

.github/ISSUE_TEMPLATE/migration.md

Update issue template

---

hardhat/deploymentInfo.json
src/pages/CreateCirclePage/CreateCirclePage.tsx

closes #406 I removed the following fields.
- What do you want to use Coordinape for?
- How many people will be in the circle?
- How much will you distribute each month?
Fixes #406

Removed Fields from Create Circle Page

---

src/components/ApeInfoTooltip/ApeInfoTooltip.tsx
src/pages/AdminPage/AdminPage.tsx
src/routes/paths.ts

Closes #428 by updating the Tooltip Component to accept a custom styling prop and moved the Add Circle button to the top right nav.

Updated Tooltips on Circle Admin page

---

.github/workflows/delete-hasura-preview.yml
.github/workflows/hasura-preview.yml

The variable changed from PG_DATABASE_URL to HASURA_GRAPHQL_DATABASE_URL

Fix PG_ENV_VARS_FOR_HASURA in Github Actions

---

.github/workflows/hasura-preview.yml

Setup [this action](https://github.com/Fieldguide/action-hasura-change-summary) to show a table summary of changes to Hasura metadata to make it easier to see any permissions that have changed, tables that have been added etc (vs having to read through YAML)

Hasura Preview change summary

---

api-lib/Gql.ts
api-lib/config.ts

closes https://github.com/coordinape/coordinape/issues/464
As seen in my comments on https://github.com/coordinape/coordinape/pull/465
this is temp for deeper issue.

Fix 464 in a temporary way

---

.github/workflows/CI.yml
README.md
api-lib/node-fetch-shim.ts
package.json
scripts/db-add-me.ts
scripts/db-seed.ts
scripts/generate-zeus.sh
scripts/setup.sh
src/lib/gql/zeusHasuraAdmin/index.ts

Fix the build instructions, running `prisma generate` is needed to create prisma's node_modules
Also, the global fetch to be included with an import
Having it in the generated files is hard to maintain.
Rename `setup-hardhat.sh` to `setup.sh`

Update setup w prisma and fetch-shim

---

src/components/StaticTable/StaticTable.tsx
src/hooks/gql.ts
src/pages/DistributePage/AllocationsTable.tsx
src/pages/DistributePage/DistributePage.tsx
src/pages/DistributePage/index.ts
src/routes/paths.ts
src/routes/routes.tsx
src/stitches.config.ts
src/ui/Button/Button.tsx
src/ui/Panel/Panel.tsx
src/ui/index.ts

Submitted in partial completion of 486.
To access the vaults use anything other than 1 for circleid and epochid and it should render the screen. Use 1 in either of those paramaters to show the Not Authorized error message.
Completed:
- Added the UI for the Submission Page using a mix of stitches and material. 
WIP: 
- Circle and Vault Validation
- Form Validation

Submit Distribution UI

---

.storybook/main.js
package.json
src/ui/Button/Button.stories.tsx
src/ui/Button/Button.tsx
src/ui/Divider/Divider.tsx
src/ui/IconButton/IconButton.tsx
src/ui/TextArea/TextArea.tsx
src/ui/TextField/TextField.stories.tsx
src/ui/TextField/TextField.tsx
src/ui/type-utils.ts
yarn.lock

Adds types utils for stories

---

src/components/MenuNavigationLinks/MenuNavigationLinks.tsx
src/components/MyAvatarMenu/MyAvatarMenu.tsx

Hides "My Team" path when team selection is false

---

hasura/metadata/databases/default/tables/public_token_gifts.yaml

need this for getting the count of gifts received during an epoch, for the upcoming distribution page in the vaults UI

allow users to run aggregation queries in hasura

---

.env.example
api-lib/config.ts
api-lib/constants.ts
api-lib/sendSocialMessage.ts
api/cron/check-nominee.ts
api/hasura/cron/check-nominee.ts
api/hasura/event-triggers/check-nominee-discord.ts
api/hasura/event-triggers/check-nominee-telegram.ts
api/hasura/event-triggers/utils/handleCheckNomineeMsg.ts
api/hasura/types.d.ts
docker-compose.yml
hasura/metadata/actions.yaml
hasura/metadata/cron_triggers.yaml
hasura/metadata/databases/default/tables/public_nominees.yaml
src/lib/gql/GqlHasuraAdmin.ts

**Deploy TODO:**
- Add env var `HASURA_API_BASE_URL` to staging and prod.
- Add env car `TELEGRAM_BOT_TOKEN` to staging and prod
**Points open for discussion:**
- Telegram API usage still unclear, where does `chat_id` come from? It's available at least in table `profiles`. ✅
- What webhook url should a cron trigger call? Does `docker-compose` need something for cron triggers to work? ✅
- Caesar the Coordinape bot avatar url needs to be filled in for Discord notifs ✅

Feature/ape 404: check nominees cron trigger

---

src/components/ApeInfoTooltip/ApeInfoTooltip.tsx
src/pages/AllocationPage/AllocationEpoch.tsx
src/pages/AllocationPage/AllocationPage.tsx

Simple addition of tooltips for the header and the stepper fix #427 (basic implementation with modification of ApeInfoTooltip component to popup a modal when user is in mobile devices)

Adding Tooltip

---

public/index.html

update description - fixes #531

update description - fixes #531

---

hardhat/hardhat.config.ts
src/hooks/useBlockListener.ts
src/hooks/useContracts.ts
src/hooks/useVaultRouter.ts
src/pages/VaultsPage/DepositModal.tsx
src/pages/VaultsPage/HasVaults.tsx
src/services/contracts.ts

Update the vault's balance immediately after a deposit succeeds, and also on every block.

Update balance after deposit

---

.github/workflows/hasura-preview.yml
hasura/metadata/actions.graphql

Testing if the new version of hasura-cloud-preview-apps is functional again

Test Hasura Preview v0.1.5

---

src/components/MyAvatarMenu/MyAvatarMenu.tsx

ADD Give Feedback button to the profile dropdown menu

---

src/lib/gql/mutations.ts
src/recoilState/app.ts
src/services/api.ts

Fixes #647 
Test plan:
1. Login to the app using any user
2. Open the hasura console in admin mode (set the admin-secret)
3. In the console, go to Data/ personal_access_tokens and query the rows, find your user
4. Back in the web app, logout / disconnect wallet
5. In the console, refresh the personal access tokens query, see your token removed

implement logout mutation in frontend

---

src/config/constants.ts

This adds a few tags that we want to add to the app for Yearn's sake. We worked to make them generic enough to be useful to others and not be weird or out of place. Resolves #644

Update profile/skills tags

---

api/hasura/actions/adminUpdateUser.ts

The FE inputs all values by default with the existing info if unchanged.
These changes support this behavior
test plan:
ensure existing values for starting_tokens and new_address yield a
successful mutation without tripping any validation errors.

AdminUpdateUser: existing values can bypass validation

---

src/hooks/useApiAdminCircle.ts
src/lib/gql/mutations.ts
src/services/api.ts
src/types/api.d.ts

Fixes #631 
To test,
Go to a circle you are the admin of and try updating users with all the various options.

port adminUpdateUser FE to hasura

---

api-lib/gql/__generated__/zeus/index.ts
hasura/migrations/default/1647664469497_create_circle_changes/down.sql
hasura/migrations/default/1647964671455_create_circle_changes_fix/down.sql
hasura/migrations/default/1647964671455_create_circle_changes_fix/up.sql
src/lib/gql/__generated__/zeus/index.ts
src/types/api.circle.d.ts

making created_at and updated_at optional and trying to restore the contact column

---

.github/workflows/hasura-preview.yml
hasura/metadata/actions.graphql

Internal version of https://github.com/coordinape/coordinape/pull/662 for testing Hasura Previews

Fix hasura preview ci workflow

---

.github/workflows/hasura-preview.yml
hasura/metadata/actions.graphql

@META-DREAMER 
these will always fail on forks, so let's just always skip them.
Not sure if syntax is correct...

Skip hasura previews on forks

---

src/hooks/useApiWithSelectedCircle.ts
src/lib/gql/mutations.ts
src/services/api.ts

Fixes #635 
Test Plan:
1. Visit vouching page
2. Vouch for new member
3. They should show up in Vouch for Nominees Section

port createNominee FE to use hasura

---

api/hasura/event_triggers/eventManager.ts
src/hooks/useApiWithSelectedCircle.ts
src/lib/gql/mutations.ts
src/services/api.ts

Fixes #634 by integrating mutation in FE. 
To test:
1. db-seed-fresh
2. navigate to Conn -Friese Health circle
3. Vouch for Malinda
... Nothing in the UI changes (see bug I submitted #687 ) but you can tell it worked because you can't vouch again. I verified this workflow behaves the same with and without this ticket implemented.

fixes #634 by migrating FE to use vouch mutation

---

api-lib/event_triggers/removeTeammate.ts
api-lib/findUser.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/updateTeammates.ts
api/hasura/event_triggers/eventManager.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_teammates.yaml
hasura/metadata/databases/default/tables/public_users.yaml
hasura/migrations/default/1648190335295_alter_table_public_teammates_add_unique_user_id_team_mate_id/down.sql
hasura/migrations/default/1648190335295_alter_table_public_teammates_add_unique_user_id_team_mate_id/up.sql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/zod/index.ts

fixes #544 
1. Test using a circle that has more than 3 users.
2. Create an epoch in the FE http://localhost:3000/admin/circles, set the start date/time so it begins immediately.
3. Update your teammates via the mutation, note the teammates you add must be in the same circle 
```gql
updateTeammates(payload: {circle_id:<circle_id>, teammates: [<user_id>, <user_id>]}) {
user {
teammates {
teammate {
id
name
}
}
}
}
}
```
4.  Go to http://localhost:3000/team to check if your teammates is updated 
5. Go to the allocation page and allocate some tokens to all your teammates and save your allocation
6. run the mutation again and but this time remove a few of your teammates.
7. check the `pending_token_gifts` table to check if your tokens are correctly refunded.  Check the …

Update teammate Hasura Migration

---

api-lib/config.ts
api-lib/gql/queries.ts
api-lib/sendSocialMessage.ts
api/hasura/cron/_epochs.test.ts
api/hasura/cron/epochs.ts
craco.config.js
hasura/metadata/cron_triggers.yaml

closes #525
There is some query code in here for the epoch ending cron task that resets circle state and optionally creates new epochs. The logic that utilizes that query will be implemented in a subsequent PR.

Migrate epoch beginning and ending notification cron tasks

---

api-lib/event_triggers/refundPendingGift.ts
api-lib/gql/queries.ts
api/hasura/actions/deleteUser.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_users.yaml
src/lib/zod/index.ts

closes #543
test plan:
1. start an epoch
2. give tokens to others in the the circle
3. execute
```gql
mutation deleteMe {
deleteUser(payload: {circle_id: <your circle id>, address: "<your address>" }) {
success
}
}
```
4. verify
a. that your user has a deleted_at timestamp
b. your user's give_token values have been reset
c. the users you gave to have had their token values reset
d. the pending_token_gifts entries created by your user have been
deleted.
e. all of your teammate entries have been deleted
5. optionally test receiving gifts from others and deleting your user.

Implement deleteUser hasura action

---

src/components/ProfileCard/ProfileCard.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/pages/VouchingPage/NomineeCard.tsx

Fix: Username not wrapping on Allocation ProfileCard, ProfilePage Name and Nominee Card

---

api/hasura/cron/dailyUpdate.ts
api/hasura/cron/epochs.ts

Received some feedback from the users regarding having deleted users appearing in the notifications, seems like we missed out handling this part.

Omitting deleted users in notifications

---

api/hasura/actions/createUser.ts

In order to prevent duplicate user entries with the same circle_id and
address from showing up in the database, createUser should recover
soft-deleted users instead of creating a new entry with the same address
alongside the soft-deleted entry.
This is relevant for the coordinape user in #558
test plan:
1. create a user in an existing circle:
```gql
createUser(payload: {
address: "0x02675dfa4d4d6b3fb7d04e0c8ad000eff752bd89", 
circle_id: 1, 
name: "dopeocount"
}) {
id
UserResponse {
address
}
}
}
```
2. soft-delete the user:
```sql
UPDATE users
SET deleted_at = 'now()'
WHERE name = 'dopeocount'
;
```
3. recreate the user:
```gql
createUser(payload: {
address: "0x02675dfa4d4d6b3fb7d04e0c8ad000eff752bd89", 
circle_id: 1, 
name: "dopeocount"
}) {
id …
```

Refactor createUser to use existing softdeleted users

---

hasura/metadata/databases/default/tables/public_profiles.yaml
src/components/EditProfileModal/EditProfileModal.tsx
src/hooks/useApiWithProfile.ts
src/lib/gql/mutations.ts
src/services/api.ts
src/types/api.d.ts

Fixes #633 ~~This is blocked by #689  and shouldn't be tested until then.~~
To test, 
1. visit profiles page and set/unset a bunch of fields and change settings
2. ensure that network traffic is going to /graphql instead of laravel
~~3. this will let in bogus website values until #689 is qualified and merged~~
4. Try to set website to valid url, invalid url, and then also after setting it, try clearing it out

fixes #633 by integrating updateProfile graphql into FE

---

src/hooks/useApiAdminCircle.ts
src/lib/gql/mutations.ts
src/services/api.ts

Fixes #640 
Test plan:
1. Visit the admin page for a circle
2. delete any active epoch 
3. open the network tab in your browser
4. create a new epoch
5. make sure we are hitting /graphql instead of the old `/v2/${circleId}/admin/epoches` laravel endpoint
6. delete it and make some more, try the various settings and make sure they work

integrating createEpoch mutation into FE

---

api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/databases/default/tables/public_circles.yaml
hasura/metadata/databases/default/tables/public_profiles.yaml
hasura/migrations/default/1649224609274_set_fk_public_circles_protocol_id/down.sql
hasura/migrations/default/1649224609274_set_fk_public_circles_protocol_id/up.sql
src/lib/gql/__generated__/zeus/index.ts

I tested that this should work in prod by running this query:
```
select count(*) from circles c LEFT OUTER JOIN protocols p ON c.protocol_id=p.id where p.id is null;
```
and getting 0 results back

make an FK from circles.protocol_id to protocols.id

---

src/hooks/useApiAdminCircle.ts
src/lib/gql/mutations.ts
src/services/api.ts
src/types/api.epoch.d.ts

Fixes #641 
To test: 
1. visit the admin page for a circle with an active epoch
2. open up the network tab in dev console
3. edit some settings of the epoch
4. save
5. make sure it hit /graphql instead of laravel
6. make sure it all works ok!

Integrating hasura updateEpoch into FE

---

src/hooks/useApiBase.ts
src/lib/gql/queries.ts
src/recoilState/app.ts
src/services/api.ts

Fixes #758 
I broke this into multiple queries instead of one massive one. I think we can break it up further and ultimately eliminate it in some future work to come. 
I'd like some eyes on this, particularly from @zashton . I am nervous about the fetching of users in this way and the nuances between how the php code was using teammates. I don't follow it all 100%.  
Test plan:
This touches pretty much everything in the app so we just need really thorough acceptance testing. I'd like to merge it into staging for testing up there after a bit of review.

migrate fetch manifest to graphql

---

package.json

The update prompt on first run can be a real buzzkill.

Skip Hasura Update check

---

src/hooks/useApiWithSelectedCircle.ts
src/pages/VouchingPage/NewNominationModal.tsx
src/pages/VouchingPage/NomineeCard.tsx

Based on #788 with some minor tweaks from me

Bugfix/749/update UI after nomination

---

api/hasura/actions/createUser.ts

Fixes #804 
To Test (locally, i dont think we can test this on test vercel cuz it has hasura dependencies):
1. Try to add users with existing and non-existing address to a circle you are an admin of

Make sure profile exists before user is created to keep FK happy

---

src/services/api.ts

fixes #628 
1. Try to login on the website via metamask & contract based wallets like Argent
2. Check if `login` is posting to the new api endpoint instead of laravel
3. Ensure your client receives a valid token and you are successfully logged in.

migrate FE to hasura for login #628

---

src/lib/gql/queries.ts
src/pages/ProfilePage/ProfilePage.tsx
src/recoilState/app.ts
src/services/api.ts
src/types/api.user.profile.d.ts
src/utils/modelExtenders.ts
src/utils/testing/recoil.ts

Fixes #759 
I'm going to merge this into staging and deploy there for testing.
To test:
1. visit other users profile pages and make sure they look good!

Migrate FE getProfile to use Hasura

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
src/hooks/useApiAdminCircle.ts
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/pages/AdminPage/AdminPage.tsx
src/services/api.ts

Fixes #756 
To test:
1. Visit admin page for a circle with ended epochs. 
2. Open the network tab in the dev console
3. Download some Epoch CSVs
4. Verify the network traffic is to /graphql vs a laravel endpoint
5. Make sure the contents of the CSV looks reasonable
Note: this is currently targeting @zashton's branch but I can rebase and move to main if that gets merged.

Migrate FE to graphql based CSV export

---

hasura/metadata/databases/default/tables/public_profiles.yaml
src/hooks/useApiBase.ts
src/lib/gql/queries.ts
src/recoilState/app.ts
src/services/api.ts
src/types/api.nominee.d.ts
src/utils/testing/recoil.ts

Fixes #758 and #744 
This has been deployed to staging for a while. 
To test:
1. Login with new and existing users
2. Look at all the pages and do all the workflows. 
This code touches pretty much everything in the frontend, so it's a bit hard to scope the testing.

migrate FE getFullCircle and fetchManifest to hasura

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api-lib/gql/queries.ts
api-lib/s3.ts
api/hasura/actions/allocationCsv.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
package.json
src/config/env.ts
src/hooks/useApiAdminCircle.ts
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/lib/zod/index.ts
src/pages/AdminPage/AdminPage.tsx
src/services/api.ts
src/utils/domain.ts
yarn.lock

fixes #724 
1. run `yarn hasura console`
2. run this mutation on a epoch that has multiple `token_gifts` connected to it, put any grant amount you desire, you can either use `epoch`(number) or `epoch_id`
```gql
allocationCsv(payload: {circle_id: <circle>, epoch_id:<epoch>, grant:300}) {
file
}
}
```
3. the response should generate a link containing a csv file.
4. download the file and check whether the csv file correspond with the `token gifts` in the epoch's records

CSV allocations

---

src/pages/AllocationPage/AllocationEpoch.tsx

Fix for https://github.com/coordinape/coordinape/issues/844

Fixing epoch text box doesn't expand issue

---

src/hooks/useApiBase.ts

This is to help debug a common user surfaced error

add some logging to the graphql error we are getting during fetchManifest

---

hasura/metadata/databases/default/tables/public_vaults.yaml
hasura/migrations/default/1651715716591_vaults_created_by_profile/down.sql
hasura/migrations/default/1651715716591_vaults_created_by_profile/up.sql

since vaults aren't associated with a circle

change vaults.created_by to point to profiles

---

hasura/metadata/databases/default/tables/public_claims.yaml
hasura/migrations/default/1651728556427_claims_drop_created_by/up.sql
hasura/migrations/default/1651729723073_claims_drop_updated_by/up.sql

same as with #870 -- these were set up incorrectly & now the vaults flow is broken

remove problematic user columns from claims table

---

src/pages/VouchingPage/NewNominationModal.tsx

This PR is fix for https://github.com/coordinape/coordinape/issues/855
https://user-images.githubusercontent.com/4746256/167426465-7272d635-c49c-4a2d-ac01-69a38c523716.mp4

Fix: Show server side error

---

api-lib/event_triggers/refundPendingGift.ts
api/hasura/event_triggers/eventManager.ts
hasura/metadata/databases/default/tables/public_users.yaml

1. Allocate to a teammate some GIVES
2. Delete that teammate from the circle
3. Make sure the GIVES are refunded correctly and not double counted.

Enables the remaining event triggers and fix the double trigger issue

---

api-lib/HttpError.ts
src/hooks/useApiBase.ts
src/recoilState/app.ts
src/utils/reporting.ts

Fixes #818 
Fixes #903 
Fixes #904

Improve sentry logging

---

api-lib/config.ts
api-lib/contracts.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api-lib/provider.ts
api/hasura/actions/createVault.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_vaults.yaml
hasura/migrations/default/1652110122820_alter_table_public_vaults_add_column_chain_id/down.sql
hasura/migrations/default/1652110122820_alter_table_public_vaults_add_column_chain_id/up.sql
hasura/migrations/default/1652824553996_alter_table_public_vaults_alter_column_vault_address/down.sql
hasura/migrations/default/1652824553996_alter_table_public_vaults_alter_column_vault_address/up.sql
scripts/db_seed_test.ts
src/hooks/useVaultFactory.test.tsx
src/hooks/useVaultFactory.ts
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/lib/zod/index.ts
src/pages/DistributionsPage/useSubmitDistribution.test.tsx
tsconfig-backend.json

test plan:
1. `docker compose --profile dev down -v` && `yarn docker:start`
2. vercel dev
3. browse to http://localhost:3000/admin/vaults
4. create a new vault with any token and observe it populate
Here's a template mutation for ensuring the endpoint is secure:
```gql
mutation testCreateVault {
createVault(payload: {chain_id: 1338, org_id: 2, vault_address: "0x<address>"}) {
id
vault {
id
created_at
created_by
decimals
org_id
simple_token_address
symbol
token_address
updated_at
vault_address
}
}
}
```
try different org IDs that the user might not have access to, and test out an invalid vault address.

Implement createVault Hasura Action

---

src/lib/gql/queries.ts

adds skills[] to users in full circle

---

api/hasura/actions/adminUpdateUser.ts

Fixes #940 
Test plan:
1. As an admin, try to update the address for a circle member.
2. it should work

fix input to update_users mutation by removing the new_address field

---

api-lib/HttpError.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/cron/epochs.ts
scripts/generate_zeus.sh
src/hooks/useApiBase.ts
src/lib/gql/__generated__/zeus/index.ts
src/utils/reporting.ts

Fixes #917 
Fixes #916
Fixes #902
Fixes #878
Fixes #875 
Fixes #874
Improving error handling and ignoring certain classes of errors to clean up Sentry.

Error handling improvements for #917 #916 #902 #878 #875 #874

---

api-lib/circleAdmin.ts

It only checked if the role was not admin, but didnt explicitly test if it was admin for the default allow case. Updated it to reject the request by default and only allow it if it passes explicit checks for either hasura admin or circleAdmin roles

Fix potential security issue in circleAdmin middleware

---

src/pages/AdminPage/AdminUserModal.tsx

Fixes #969 
Exchange tooltips texts for send and receive give check boxes
1- Go to Admin Page
2- click edit to one of the circle memebers
3- check the tool tips for "Alow contrbutor to send gives" and  "Alow contrbutor to receive gives"

Fix #969 exchange tooltips texts for send and receive give

---

scripts/db_seed_test.ts
scripts/util/seed.ts
src/pages/CirclesPage/CirclesPage.tsx
src/recoilState/app.ts

Fixes #983 
Test Plan:
1. Use the new seed data from this PR
2. Navigate to the circles page
3. hover over the "Toys not a member " circle and make sure you can't navigate to it or see the allocation/history/etc buttons

Remove buttons on hover for circles you aren't a member of

---

api/hasura/cron/epochs.ts

Solves the issue of repeated epoch number for the circle

fix repeated epoch number for same circle

---

README.md
package.json

Add yarn dev command
Add yarn dev command and set BROWSER=none for craco command. Context: https://discord.com/channels/845400066532704256/898299792575299654/984131256272945222
This stops a browser from opening on a random port that doesn't actually work.

Add yarn dev command

---

src/pages/AdminPage/components.tsx
src/pages/AllocationPage/AllocationEpoch.tsx

Fixed Broken Link in Doc.
Resolving #1012

Updated Doc Link

---

api-lib/findUser.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api-lib/gql/mutations.ts
api-lib/gql/queries.ts
api/hasura/actions/createUser.ts
cypress/integration/createNominee.ts
cypress/integration/createUser.ts
cypress/integration/updateUser.ts
hasura/metadata/actions.graphql
scripts/db_seed_test.ts
src/forms/AdminUserForm.tsx
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/lib/gql/queries.ts
src/lib/zod/index.ts
src/pages/AdminPage/AdminPage.tsx
src/pages/AdminPage/AdminUserModal.tsx
src/pages/AdminPage/components.tsx
src/pages/DistributionsPage/AllocationsTable.tsx
src/types/api.d.ts
src/types/api.user.profile.d.ts
src/utils/modelExtenders.ts
src/utils/testing/recoil.ts

fixes #809 
1. Enable Fixed Payments in Circle Settings by selecting a token
2. Go to any contributor and set a value for their fixed payment amount
3. Save and make sure the amount is reflected in the main contributors table.
Alternatively can just run cypress test for createUsers/updateUsers

feat: Fixed Payment Amount

---

api-lib/types.d.ts
api/hasura/actions/_handlers/adminUpdateUser.ts
api/hasura/actions/_handlers/allocationCsv.ts
api/hasura/actions/_handlers/createCircle.ts
api/hasura/actions/_handlers/createEpoch.ts
api/hasura/actions/_handlers/createNominee.ts
api/hasura/actions/_handlers/createUser.ts
api/hasura/actions/_handlers/createUsers.ts
api/hasura/actions/_handlers/createVault.ts
api/hasura/actions/_handlers/deleteEpoch.ts
api/hasura/actions/_handlers/deleteUser.ts
api/hasura/actions/_handlers/generateApiKey.ts
api/hasura/actions/_handlers/logoutUser.ts
api/hasura/actions/_handlers/updateAllocations.ts
api/hasura/actions/_handlers/updateCircle.ts
api/hasura/actions/_handlers/updateEpoch.ts
api/hasura/actions/_handlers/updateTeammates.ts
api/hasura/actions/_handlers/updateUser.ts
api/hasura/actions/_handlers/uploadCircleLogo.ts
api/hasura/actions/_handlers/uploadOrgLogo.ts
api/hasura/actions/_handlers/uploadProfileAvatar.ts
api/hasura/actions/_handlers/uploadProfileBackground.ts
api/hasura/actions/_handlers/vouch.ts
api/hasura/actions/actionManager.ts
hasura/metadata/actions.yaml

Our builds our slow right now (circa 15-22 minutes).
[This preview build](https://vercel.com/coordinape/coordinape/7QCDu4WKwF5fFpwJ3iwyy61ekN4B) completes in 10 minutes, without 
the benefit of the build cache for the new handler bundle, even, and ~5 minutes with the benefit of the cache.
There are still further optimizations to be made as well,
as far as bundling and routing different types of requests
into a single endpoint.
E2E tests are passing so it appears that all endpoints are functioning as expected.
merge after #1047 because it fixes an issue that will cause all endpoints to crash after combining them all.

Unite actions behind a central hander

---

.env.example

With the changes in https://github.com/coordinape/coordinape/pull/1047 it is necessary to have a `GOERLI_RPC_URL` env var for the service to run
Add an example `GOERLI_RPC_URL` to the `.env.example`
Added the env var and it initialises
@topocount

chore: Add `GOERLI_RPC_URL` to .env.example

---

api/login.ts

causing the issue of new users unable to access their newly created circle.

Fix for mix cased address in profiles table

---

src/pages/VaultsPage/DepositModal.tsx

This refactor utilizes new preferred, more maintainable form components
and is otherwise functionally identical
This is basically just an update to improve maintainability and deprecate some older underlying components
existing E2E tests should pass and 2nd Wallet deposit should work
#1070

vaults: Refactor Deposit Modal

---

api/hasura/actions/_handlers/createVault.ts
cypress/integration/createVault.ts
src/components/MainLayout/MainHeader.tsx
src/components/OverviewMenu/OverviewMenu.tsx
src/lib/vaults/tokens.ts
src/pages/AdminPage/AdminUserModal.tsx
src/pages/DistributionsPage/AllocationsTable.tsx
src/pages/DistributionsPage/DistributionForm.tsx
src/pages/VaultsPage/CreateForm.test.tsx
src/pages/VaultsPage/CreateForm.tsx
src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/VaultsPage.tsx

rename to "coVaults"

---

cypress/integration/createVault.ts
src/hooks/useVaultRouter.ts
src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/WithdrawModal.tsx

Implement Vault Withdraw modal

---

src/components/MyAvatarMenu/MyAvatarMenu.tsx
src/components/OverviewMenu/OverviewMenu.tsx

This reverts commit ebf370f23bcb28645f08d0b57ffced311ff0e259.
This is causing some really unexpected behavior in firefox at least, like links not getting followed and navigation redirecting to the original page.

Revert "close menus after an item is clicked"

---

src/pages/AdminPage/components.tsx

Fixes #1082 by making the button label a prop on `EmptyTable` reusable component

fix incorrect label for Create Epoch button

---

cypress/e2e/createVault.cy.ts
cypress/e2e/updateCircle.cy.ts
src/hooks/useVaultRouter.ts
src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/WithdrawModal.tsx

Forgot to rebase #1053 before merging.

implement withdraw modal

---

src/hooks/useApiBase.ts
src/services/api.ts

Users have reported that logging in with mobile wallets on iOS is broken.
Fixes #1116

fix login on iOS

---

hasura/migrations/default/1657113614850_alter_table_public_circle_integrations_add_column_created_at/down.sql
hasura/migrations/default/1657113614850_alter_table_public_circle_integrations_add_column_created_at/up.sql
hasura/migrations/default/1657113629100_alter_table_public_circle_integrations_add_column_updated_at/down.sql
hasura/migrations/default/1657113629100_alter_table_public_circle_integrations_add_column_updated_at/up.sql
hasura/migrations/default/1657272216350_trigger_migration_updated_at/down.sql
hasura/migrations/default/1657272216350_trigger_migration_updated_at/up.sql

We don't have a way to track growth of integrations
Add `created_at` and `updated_at` columns to `circle_integrations` table
@zashton
Closes https://github.com/coordinape/coordinape/issues/1014

feat: Add created_at and updated_at columns to circle_integrations table

---

src/pages/DistributionsPage/DistributionsPage.test.tsx
src/pages/DistributionsPage/DistributionsPage.tsx
src/pages/DistributionsPage/queries.ts

Fix distribution table to new amounts

---

api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/allocationCsv.ts
src/lib/gql/__generated__/zeus/index.ts
src/pages/DistributionsPage/DistributionForm.tsx
src/pages/DistributionsPage/DistributionsPage.tsx
src/pages/DistributionsPage/queries.ts

fixes #811 
1.  Choose a circle with an ended epoch and go to circle settings and set the fixed payment token type to any value
2.  Go to admin page and set a few members fixed payment token amounts
3.  Click on Export CSV button and check if the downloaded CSV whether the columns and rows are correct

Fixed payment csv output

---

src/pages/DistributionsPage/AllocationsTable.tsx
src/pages/DistributionsPage/DistributionsPage.tsx

Preview values for allocation table

---

src/components/ApeTextField/ApeTextField.tsx
src/components/ApeToggle/ApeToggle.tsx
src/components/OverviewMenu/OverviewMenu.tsx
src/pages/VaultsPage/DepositModal.tsx
src/ui/Modal.tsx
src/ui/Text/Text.tsx

Minor UI updates to deposit modal, including adding address.
Global form label updates

Deposit modal UI

---

src/pages/CirclesPage/CirclesPage.tsx

Resolves 1143
Add 'Create Circle in New Organization' button to the overview page, also add Overview header.  some flex positioning
Pretty simple PR 🎉

Add 'Create Circle in New Organization' button to the overview page

---

src/pages/CreateCirclePage/CreateCirclePage.tsx

This seems to resolve bug, but not sure if the "right" way to fix this issue.

Fix state bug with create circle form

---

api-lib/gql/queries.ts
api/hasura/actions/_handlers/createVaultTx.ts
cypress.config.ts
src/common-lib/contracts.ts
src/hooks/gql/useVaults.ts
src/lib/gql/mutations.ts
src/lib/gql/queries.ts
src/pages/DistributionsPage/mutations.ts
src/pages/DistributionsPage/useSubmitDistribution.ts
src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/VaultTransactions.tsx
src/pages/VaultsPage/queries.ts
src/utils/provider.ts

Both the VaultRow and All Transactions lists are implemented. Deposit,
Distribution and Withdraw events are captured and logged. Events
that do not have entries in our DB are not yet logged because we
need a better way to capture details from those txs or at least
communicate that the events are incomplete.
- deploy a vault and create deposits, distributions and withdraws
- wait a few seconds
- events should show up inline in the Vault transactions tables
closes #476
Some remaining tasks I need to log:
- implement E2E tests
- optimize the marshalling sequence a bit better if logs are
slow to render on Goerli
- force the logs to re-render directly due to user interactions. It
seems like deposits and withdrawals dont automatically submit a
refetch request to useVaults yet.

Integrate Vault Transaction Logs

---

src/pages/CreateCirclePage/CreateCirclePage.tsx

cleanup : https://github.com/coordinape/coordinape/pull/1153#pullrequestreview-1043409433

Remove redundent undefined

---

hardhat/deploymentInfo.json
hardhat/dist/deploymentInfo.json

This Vault Factory will deploy yvaults with 6 decimal places and add them
to the registry on Goerli.

Add MockUSDC Vault Factory to Goerli

---

cypress/e2e/createVault.cy.ts
scripts/db_clean.ts
src/hooks/gql/useVaults.ts
src/lib/gql/mutations.ts
src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/queries.ts

- Add Vault Statistics to each Vault Row
- Add E2E tests for VaultRow Table
These stats were hardcoded and now they are computed in the frontend.
I also added E2E tests for the Vault Tx Table in this PR.
E2E te
@levity
closes #1148
closes #1098

Add Vault Stats to Vault Rows

---

src/pages/HistoryPage/EpochForm.tsx

fixes #1163
1- Enable Date and Time fields on new Epochs
1- Click create epoch button on history page
- The date and time fields should be editable
Tested other scenarios like editing current Epoch or an upcoming epoch

fix dsiabled fields on new epoch

---

src/components/WalletAuthModal/WalletAuthModal.tsx
src/hooks/useMediaQuery.ts
src/hooks/useMobileDetect.ts
src/hooks/useNavigation.ts
src/pages/AdminPage/AdminPage.tsx
src/pages/AssetMapPage/AssetMapPage.tsx
src/pages/CircleAdminPage/AdminIntegrations.tsx
src/pages/VaultsPage/DepositModal.tsx
src/utils/domain.ts
src/utils/reporting.ts

Fixes #1027 by making sure we only reference `window`  when we are on the client-side. 
**NOTE:** After deploy, we need to make sure login and landing page (non-app) still work ok.

changing all references to `window` to be client-side conditionalized

---

src/pages/VaultsPage/DepositModal.tsx
src/pages/VaultsPage/WithdrawModal.tsx
src/utils/index.ts

Fixes
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=d101db86e01047f4a5e2a8ce3b522789&pm=s

Add commas formatting for max labels

---

src/pages/DistributionsPage/DistributionForm.tsx
src/pages/DistributionsPage/DistributionsPage.tsx

Fixes
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=fbabd925698840ad865f37d6425c687a&pm=s

Remove export csv button in fixed payment form

---

src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/VaultTransactions.tsx

Fixes
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=89cecf1fe5b64377ae2f0065d40f0808&pm=s
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=dccbe9c08ae148ea9b1b7db3b45c84ab&pm=s

Vault transactions etherscan fix

---

src/routes/paths.ts
src/routes/routes.tsx

Fixes
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=569db46d7d4d4d5988160e676808203d&pm=s

Fix all transactions error

---

src/pages/ClaimsPage/ClaimsPage.tsx
src/pages/ClaimsPage/queries.ts

Fixes
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=1cf38c2a2f3f427bada2cb278364a878&pm=s

Fix for etherscan link on claims page

---

api-lib/config.ts
scripts/seed_hasura.sh
scripts/util/seed.ts
scripts/vault_QA_seed.ts

Script used to seed QA test users. checking in for transparency and knowledge sharing

Create QA Seed Script

---

src/pages/DistributionsPage/AllocationsTable.tsx
src/pages/DistributionsPage/DistributionsPage.tsx

Fixes 
https://www.notion.so/coordinape/226b9363ee0d45cead60e5365ae65d10?v=2137f63c15394b32b90fb80dd09a5244&p=5041d864aeeb4797b2e1f48d974270f7&pm=s

Fix fund allocated in distributions displaying 0 issue

---

package.json
src/components/HelpButton.tsx
src/components/MainLayout/MainHeader.tsx
src/components/MyAvatarMenu/MyAvatarMenu.tsx
src/routes/paths.ts
yarn.lock

Reverts coordinape/coordinape#1187

Revert "move docs/feedback to help button and link to typeform"

---

src/pages/CirclesPage/CirclesPage.tsx
src/pages/DistributionsPage/AllocationsTable.tsx
src/pages/HistoryPage/EpochPanel.tsx
src/ui/Panel/Panel.tsx

* Remove `Distributions` button from the Notes area of the epoch panel
* Add "Review / Export" bottom-pinned button to the panel with distribution overview info

Vaults CTA - "Review / Export" button

---

src/pages/DistributionsPage/DistributionForm.tsx

Fixes 
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=6623ce445b9c4a67beeaf3b4a920f7ab&pm=s

Fixed payment symbol issue

---

hasura/metadata/actions.yaml

adding in the missing deleteCircle input and response hasura metadata

Add missing hasura metadata for deleteCircle

---

hasura/metadata/databases/default/tables/public_distributions.yaml
hasura/migrations/default/1659467509391_set_fk_public_distributions_created_by/down.sql
hasura/migrations/default/1659467509391_set_fk_public_distributions_created_by/up.sql

Create fkey relationship from distributions.created_by -> profile.id

Create relationship from distributions.created_by -> profile.id

---

scripts/db_clean.ts
scripts/db_seed_test.ts
scripts/seed_hasura.sh

- add 5 epochs
- fix order of epochs
- add echo statement
- delete more data in truncate

Update seed scripts:

---

hasura/metadata/databases/default/tables/public_claims.yaml

update perms to only allow insertion when circle is still active

Update claims insert perm

---

src/pages/ClaimsPage/ClaimsPage.tsx
src/pages/ClaimsPage/hooks.ts
src/pages/ClaimsPage/mutations.ts
src/pages/ClaimsPage/queries.ts
src/pages/ClaimsPage/utils.test.ts
src/pages/ClaimsPage/utils.ts

TODO:
Update Claims Page to properly group, sort, and batch claims.
Fixes:
- grouping
- etherscan link
- amount show
- date sorting

Claims Page

---

api/hasura/actions/_handlers/createUserWithToken.ts

these were just added in https://github.com/coordinape/coordinape/pull/1199/files#diff-facdccf70ca95c8fd27abae06840850cc36d240dec8aeab36d3607bf89d79018R27 so lets remove them
@CryptoGraffe

Remove console logs

---

src/pages/AllocationPage/queries.ts

fix missing epoch statements on allocation page

---

scripts/db_seed_test.ts
scripts/util/seed.ts

Add more seed data, and helper function to create it

Add more seed data, and helper function to create it

---

src/components/MyAvatarMenu/MyAvatarMenu.tsx

Claims button in menu should be  feature flagged

wrap hide claims in feature flag

---

src/pages/DistributionsPage/DistributionForm.tsx

Updated submitting text state to only to be shown to specific button
Fixes 
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=f955930f031541849c4b426959203330&pm=s

Submit button text state change

---

hasura/migrations/default/1656098131988_create_table_public_circle_share_token/up.sql

This works around a permissions issue in our db with hasura user vs postgres user

commenting out creation of trigger

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api-test/hasura/cron/recoverTransactions.test.ts
api/hasura/cron/recoverTransactions.ts
hasura/migrations/default/1659719605137_fix_total_amount/down.sql
hasura/migrations/default/1659719605137_fix_total_amount/up.sql
hasura/migrations/default/1659968853380_fix_distribution_json/up.sql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/merkle-distributor/index.test.ts
src/lib/merkle-distributor/index.ts
src/lib/merkle-distributor/parse-balance-map.ts
src/pages/ClaimsPage/hooks.ts
src/pages/ClaimsPage/useClaimAllocation.test.tsx
src/pages/DistributionsPage/DistributionsPage.test.tsx
src/pages/DistributionsPage/mutations.ts
src/pages/DistributionsPage/useSubmitDistribution.test.tsx
src/pages/DistributionsPage/useSubmitDistribution.ts

https://www.notion.so/coordinape/Recover-distribution-transactions-f66554e0bbad40f3b3e85d2e69b6b1d6
extend the `recoverTransactions` cron job to handle Distribution transactions as well

Recover distributions

---

api-lib/circleAdmin.ts
api-lib/constants.ts
api-lib/dateTimeHelpers.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/allocationCsv.test.ts
api/hasura/actions/_handlers/allocationCsv.ts
hasura/metadata/actions.graphql
src/hooks/useApiAdminCircle.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/lib/zod/index.ts
src/pages/DistributionsPage/AllocationsTable.tsx
src/pages/DistributionsPage/DistributionsPage.tsx
src/pages/HistoryPage/EpochPanel.tsx
src/pages/HistoryPage/HistoryPage.tsx

Fixes
https://www.notion.so/coordinape/VAULTS-QA-dd5a668750314cbc8f9a431fac1132a0?p=5658986b4684436a8efe22b7eb4588d7&pm=s
Syncing the CSV with the allocation to show preview values

Distribution csv sync

---

src/components/ApeAutocomplete/ApeAutocomplete.tsx
src/components/DeprecatedApeTextField/DeprecatedApeTextField.tsx
src/components/FormAutocomplete/FormAutocomplete.tsx
src/components/FormTokenField/FormTokenField.tsx
src/pages/DistributionsPage/DistributionForm.tsx

implements #1168
Update DistributionForm to use useController instead of FormControl
1- Removed FormControl from mui and Controller from react-hook-form
2- Used UseController from react-hook-form
1- Created a covault
2- test normal distribution and fixed payment distribution

Update DistributionForm to use useController instead of FormControl

---

cypress/e2e/createVault.cy.ts
src/hooks/gql/useVaults.ts
src/lib/vaults/tokens.ts
src/pages/ClaimsPage/ClaimsPage.tsx
src/pages/ClaimsPage/utils.ts
src/pages/DistributionsPage/AllocationsTable.tsx
src/pages/DistributionsPage/DistributionForm.tsx
src/pages/DistributionsPage/DistributionsPage.test.tsx
src/pages/DistributionsPage/DistributionsPage.tsx
src/pages/VaultsPage/DepositModal.tsx
src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/VaultTransactions.tsx
src/pages/VaultsPage/WithdrawModal.tsx
src/utils/index.ts

This allows us to distinguish between Yearn and simple token vaults in
the UI.

Prepend 'Yearn - ' to Yearn Vaults in UI

---

src/components/FormInputField/FormInputField.tsx
src/pages/CircleAdminPage/CircleAdminPage.tsx
src/ui/Panel/Panel.tsx
src/ui/Select/Select.tsx
src/ui/TextField/TextField.tsx
src/ui/Tooltip/Tooltip.tsx

Adding some props for the `<Select>`

Disabled state for radix select.  Label for radix select

---

src/pages/CircleAdminPage/CircleAdminPage.tsx

this fixes the mobile UI problem when on circle page edit screen
https://github.com/coordinape/coordinape/issues/1137

this is the fix for the mobile ui problem

---

src/pages/ClaimsPage/useClaimAllocation.ts
src/pages/DistributionsPage/DistributionForm.tsx
src/pages/DistributionsPage/useSubmitDistribution.test.tsx
src/pages/DistributionsPage/useSubmitDistribution.ts

Improve Recent Transaction info by adding circle and epoch ID to the modal
Updated the `useSubmitDistribution` and `useClaimAllocation` hooks to include more info. Also update the tests for the same file and they all work as expected.

update transaction descriptions to include circle and epoch info

---

src/ui/Select/Select.stories.tsx
src/ui/Select/Select.tsx

@levity is this the right correction for the import?  Variables seem to work properly

Select Radix Import Fix

---

src/pages/DistributionsPage/DistributionForm.tsx

Reduce the text in the pre-label/label to free up more space to display token balance
Fixes one of issues in the UI nits

Update label for distribution form token input

---

src/pages/HistoryPage/HistoryPage.tsx

feature flagging vaults button on epoch get started

---

.vscode/settings.json
src/pages/VaultsPage/CreateForm.test.tsx
src/pages/VaultsPage/CreateForm.tsx
src/pages/VaultsPage/VaultsPage.tsx
src/ui/Button/Button.tsx
src/ui/Panel/Panel.tsx

References: https://www.notion.so/coordinape/Create-CoVault-Change-Hierarchy-a8a69e49c1e14d6889d7a0176e73d093
Big thanks to @crabsinger for all the pairing help!
@levity @topocount please take a look at the hard coded USDC and DAI addresses (CreateForm.tsx:Line 19-20).  Is this an okay way to do things for now?  Is there another, better way?

Create Vault Options:  CoVault & Yield Generating CoVault

---

src/config/features.ts

this lets us personally turn on feature flags

feature flags via local storage

---

src/lib/gql/queries.ts

Fixes #1317  - user setup demo circles, deleted them, then couldn't make any new ones. 
check for deleted_at
Follow the recreation steps in the ticket
I was able to recreate the issue and then prove that this fixes it.

omit deleted circles when fetching manifest

---

src/components/ProfileCard/GiftInput.tsx

it converts decimal into real numbers on time so the user won't enter any decimal and save it 
https://user-images.githubusercontent.com/94828675/185784641-01f8c3b6-215a-459c-80f8-22be62a408d9.mov
https://github.com/coordinape/coordinape/issues/1292

decimal input Fix

---

api-lib/gql/__generated__/zeus/index.ts
api-lib/gql/mutations.ts
api/hasura/actions/_handlers/createCircle.ts
hasura/metadata/actions.graphql
hasura/metadata/cron_triggers.yaml
src/forms/CreateCircleForm.tsx
src/lib/gql/__generated__/zeus/index.ts
src/lib/zod/index.ts
src/pages/CreateCirclePage/CreateCirclePage.tsx
src/types/api.d.ts

resolves #1130 
1- Add circle logo field to create circle Form
2- Update create circle action to accept logo file
3- Update createCircle Handler to accept logo and resize it before uploading
1- Click Add circle button  from overview page
2- Add a new circle and use upload button to upload a logo to the circle
3- Check the newly created page circle settings for the circle logo

Create circle logo upload

---

src/components/ProfileCard/ProfileCard.tsx
src/pages/AdminPage/components.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/routes/paths.ts

from
https://coordinape.notion.site/Why-is-Coordinape-in-my-Circle-fd17133a82ef4cbf84d4738311fb557a
to
https://coordinape.com/post/why-is-coordinape-in-my-circle?utm_source=coordinape-app&utm_medium=tooltip&utm_campaign=coordinapeincircle

External Feedback link location edit

---

CONTRIBUTING.md

Fix: typos

---

CONTRIBUTING.md

Fix: minor typos

---

api-lib/event_triggers/sendInteractionEventToAmplitude.ts
api-lib/event_triggers/sendInteractionEventToMixpanel.ts
api-lib/nominees.ts
api/hasura/actions/_handlers/updateAllocations.ts
hasura/migrations/default/1663351749749_alter_table_public_interaction_events_drop_column_user_id/down.sql
hasura/migrations/default/1663351749749_alter_table_public_interaction_events_drop_column_user_id/up.sql

* Update interaction_events table removing unncessary `circle_id`
* Add allocation updates event to interaction_events

Add allocation updates to interaction_events, update table

---

src/config/env.ts
src/utils/apiKeyHelper.ts

Update the link from http://localhost:3000/developers
to properly go to a local hasura console for UI with current auth token.
Successful loading:

Support local hasura console links

---

src/components/OrgLogoUpload.tsx
src/hooks/useApeSnackbar.tsx
src/pages/AddMembersPage/NewMemberList.tsx
src/pages/CircleAdminPage/RemoveCircleModal.tsx

make snackbar's showError a little smarter

normalize errors in useApeSnackbar

---

.github/workflows/CI.yml
api/hasura/actions/_handlers/updateCircle.ts
src/pages/CircleAdminPage/CircleAdminPage.tsx

Users have the ability to designate a custom GIVE Token name, this causes some confusion for users when all of our docs refer to GIVE.
* Remove the custom token name field from the Circle Admin general section if it is not custom, expands remaining fields to take full width;
* Disable the custom token name field if there is one already set;
* Throw an error if the user somehow manages to attempt to change the token name.
FE: Ran locally with and without a custom token name and saw the diff
BE: Tried to set a custom token name and saw the error message, users will not be able to do that from the frontend as the field is disabled.
Refer to the screenshots below
@topocount 
Closes https://github.com/coordinape/coordinape/issues/1335

feat: Remove Custom Token Name

---

src/stitches.config.ts
src/ui/Button/Button.tsx
src/ui/Flex.tsx
src/ui/Text/Text.tsx

Adding some missing variants for the contributions and allocation work
some new helpers for ellipsis text, tag colors, etc

minor new variants and helpers for stitches

---

api-lib/gql/__generated__/zeus/index.ts
cypress/e2e/allocate.cy.ts
docker-compose.yml
src/lib/gql/__generated__/zeus/index.ts

Undo graphql image upgrade

---

src/pages/GivePage/GiveAllocator.tsx
src/pages/GivePage/GiveDrawer.tsx

after playing more the animation was too slow

Give notes fix

---

src/pages/AdminPage/AdminPage.tsx
src/pages/AdminPage/MembersTable.tsx
src/pages/AdminPage/NomineeTable.tsx
src/pages/CirclesPage/CirclesPage.tsx
src/stitches.config.ts
src/ui/Button/Button.tsx

- only show nominee table if there are nominees
- change x color to neutral
- minor ui spacing updates
- button name fix: manager member to manage member
- admin link in circle page circle should go to settings not member page
- add members link to circle hover links

Fixup/members page UI

---

src/components/ReceiveInfo.tsx

Avatar and Name fix for drop down menu 
https://github.com/coordinape/coordinape/issues/1425

Avatar and Name fix for drop down menu

---

src/pages/AdminPage/MembersTable.tsx
src/pages/GivePage/MyGiveRow.tsx
src/ui/Button/Button.tsx
src/ui/ToggleButton.tsx
src/ui/index.ts

- Add ToggleButton @CryptoGraffe made for give page to /ui
- Use toggleButton in members list admin area
- Modify the hover and unselected state of button

ToggleButton unification

---

api-lib/contracts.ts
api/hasura/actions/_handlers/createVault.ts
api/hasura/cron/recoverTransactions.ts
src/lib/vaults/contracts.ts
src/lib/vaults/tokens.ts

Reverts coordinape/coordinape#1424

Revert "make src/lib/vaults/contracts work in backend code"

---

src/ui/Panel/Panel.stories.tsx

The `Panel` component is lacking documentation when it comes to its usage, for example https://discord.com/channels/845400066532704256/898299792575299654/1025452274824253591
Add a story for the `Panel` component
Ran storybook and saw the `Panel` story working correctly with a `Select` and `TextArea` components
@wingfeatherwave 
Closes https://github.com/coordinape/coordinape/issues/1441

story: Panel with Select

---

public/index.html
src/components/OrgLogoUpload.tsx
src/pages/AdminCircleApiPage/ApiKeyDisplay.tsx
src/pages/AdminCircleApiPage/ApiKeyForm.tsx
src/pages/CirclesPage/CirclesPage.tsx
src/pages/OrganizationPage/OrganizationPage.tsx
src/pages/VaultsPage/CreateForm.tsx
src/pages/VaultsPage/VaultRow.tsx
src/ui/Text/Text.tsx

* Avatars in org names should be 32px
* fix upload popover size
* remove non-inter fonts that we don't use

Circles page avatar alignment

---

api/hasura/actions/_handlers/uploadOrgLogo.ts

Errors should be properly raised in ImageUpdater.ts

Remove try / catch in ImageUpdater

---

src/pages/ContributionsPage/ContributionsPage.tsx

mergable fork of #1494. Resolves #868

Implement dework/wonder integration in new contributions page

---

src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/ContributionsPage/util.tsx

@sshmm discovered some buggy behavior with the current nav buttons when
jumping between contributions that are grouped into different epochs.
I fixed this by formalizing the "Latest" timespan as a pseudo-epoch of
sorts, and add it to the epochs array if we're outside of an epoch and
no future epoch is scheduled. The time logic was getting tricky so i
added a bunch of library functions that probably need unit tests at
some point to verify correctness of behavior.
test plan: Play around with seeded data to ensure that the nav buttons
behave correctly.
merge plan: rebase and merge after #1494

Contributions Nav Button Fixes

---

hasura/metadata/actions.yaml

To support easier debugging, and query params to webhook handlers so we can see what actions are happening in our logs

Add query param action name tracking to webhook handler

---

src/pages/ContributionsPage/util.tsx

I hoped this was just local to the Contributions page and didn't realize
this had uninitended side effects

bugfix: remove utc config

---

src/lib/gql/mutations.ts
src/pages/CircleAdminPage/CircleAdminPage.tsx
src/pages/CircleAdminPage/CircleLogoUpload.tsx

resolves #1497
1- Created  CircleLogoUpload.tsx to follow org logo upload in OrganizationSettingsPage.tsx and use it in CircleAdminPage:
Button to upload new Image
Auto-save Image after selected
Error state
While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."
I created a new component file so that CircleAdminPage doesn't get bigger
2- Update uploadCircleLogo mutation to return the avatar to display after upload
3- Changing the logo now won't make circle settings form become dirty
3- clean CircleAdminPage 
1- Go to Circle Settings
2- Change the logo
3- go to another page and return to circle settings to check that the data are preserved
4- refresh and check again

Improve Circle Logo Upload Pattern

---

src/components/MainLayout/CircleNav.tsx
src/pages/CirclesPage/CirclesPage.tsx
src/routes/paths.ts

Bring contributions to the people!
merge after:
- #1505
- #1516
- #1525

Add Contributions to the NavBar

---

src/components/MyAvatarMenu/MyAvatarMenu.tsx
src/pages/HistoryPage/CurrentEpochPanel.tsx
src/pages/HistoryPage/HistoryPage.test.tsx
src/pages/HistoryPage/HistoryPage.tsx

resolves #1470
merge after:
https://github.com/coordinape/coordinape/pull/1505
https://github.com/coordinape/coordinape/pull/1516
https://github.com/coordinape/coordinape/pull/1525

Epoch page with allocations contributions links

---

src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/GivePage/EpochStatementDrawer.tsx
src/pages/GivePage/GiveDrawer.tsx
src/pages/GivePage/SavingIndicator.tsx
src/pages/GivePage/index.tsx

Allocate setTimeout clearing wasn't really working and its a mystery, tried to debug with levity but I decided to get rid of it anyway. This is actually a better and more react-friendly impl that has some extensibility to it. I use a state machine and changed all the setTimeouts to lodash debounce and was able to eliminate some. 
Try to allocate and edit notes and edit epoch statement. 
@levity

Fix allocate debounce

---

src/pages/GivePage/EpochStatementDrawer.tsx
src/pages/GivePage/GiveDrawer.tsx

this change just let the text wrap and whiteSpace the epoch statement 
#1481

white spacing for EpochStatment

---

src/pages/MembersPage/LeaveCircleModal.tsx
src/pages/MembersPage/MembersTable.tsx
src/pages/MembersPage/index.tsx
src/pages/OrganizationPage/OrganizationPage.tsx
src/pages/OrganizationPage/getOrgData.ts
src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx

resolves #1431
1- Add Leave circle button in Members table to trigger LeaveCirlceModal
2- Add LeaveCircleModal to confirm the user choice
3- Navigate to circles page after confirming
1- Go to member page and click Leave circle button if you are not an admin or Manage user then Leave Circle if you are an admin
2- Confirm the choice by writing the circle name the press enter
2a6d8.png)

Allow users to leave circles Front End

---

src/pages/ContributionsPage/ContributionsPage.tsx

This pattern follows the Give page's pattern rather than using UseEffect to conditionally enqueue saves

Switch to use a buffering -> scheduled debounce enqueue pattern

---

src/ui/FormLabel/FormLabel.stories.tsx
src/ui/FormLabel/FormLabel.tsx

* Implement a basic story for the `FormLabel.tsx` component.
@crabsinger 

feat: Add `FormLabel` story

---

src/ui/Table/Table.stories.tsx

* Implement a basic story for the `Table` component.
@crabsinger 

feat: Add `Table` story

---

src/ui/Link/Link.stories.tsx
src/ui/Link/Link.tsx

* Implement a basic story for the `Link` component with `type` and `color` controls.
@crabsinger 

feat: Add `Link` story

---

src/ui/layouts.stories.tsx

* Implement a basic story for the `SingleColumnLayout` component;
* Implement a basic story for the `TwoColumnLayout` component.
@crabsinger 

feat: Add `Layouts` story

---

src/ui/Popover/Popover.stories.tsx
src/ui/Popover/Popover.tsx
src/ui/index.ts

* Implement a basic story for the `Popover.tsx` component;
@crabsinger 

feat: Add `Popover` story

---

src/ui/Checkbox/CheckBox.stories.tsx

* Implement a basic story for the `Checkbox.tsx` component;
@crabsinger 

feat: Add `Checkbox` story

---

src/ui/Image/Image.stories.tsx

* Implement a basic story for the `Image.tsx` component.
@crabsinger 

feat: Add `Image` story

---

.storybook/preview.js
src/ui/Box/Box.stories.tsx

* Implement a basic story for the `Box.tsx` component;
* Implement a story for the usage of `Box.tsx` as a truncating component.
@crabsinger 

feat: Add `Box` story

---

src/ui/Avatar/Avatar.stories.tsx
src/ui/Avatar/Avatar.tsx
src/utils/domain.ts

* Implement a basic story for the `Avatar` component.
@crabsinger 

feat: Add `Avatar` story

---

src/ui/HR/HR.stories.tsx

* Implement a basic story for the `HR` component.
@crabsinger 

feat: Add `HR` story

---

src/pages/ContributionsPage/ContributionIntro.tsx
src/pages/ContributionsPage/ContributionPanel.tsx
src/pages/ContributionsPage/ContributionRow.tsx
src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/ContributionsPage/PlaceholderContributions.tsx

Fixes #1604 
Blue intro box and example contributions when you have no contributions yet. Links to docs

contribution helper box and examples, with a little refactoring

---

.github/pull_request_template.md

Follow up of this https://github.com/coordinape/coordinape/pull/1625#pullrequestreview-1181036703
Add a bit more context to what is suppose to go in the test plan section
@topocount 
https://github.com/coordinape/coordinape/pull/1625#pullrequestreview-1181036703

refactor: Improve the description of the test plan in the PR template

---

src/pages/ContributionsPage/ContributionsPage.tsx

Logic was accidentally silly
>= becomes === 0

fixing logic that was erroneously showing contribution help aggressively

---

src/components/MainLayout/MainHeader.tsx

this change return the drop down menus to be over the whole page 
fixes #1682

zindex for mainheader

---

src/components/MainLayout/OverviewMenu.tsx
src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/GivePage/index.tsx
src/ui/Link/Link.tsx

Less obtrusive inline edit text pattern
* add support for svg icon links with nice alignment

Minor UI update: inline edit text ui update

---

src/components/MainLayout/MainLayout.tsx
src/components/MainLayout/RequireAuth.tsx

move RequireAuth to its own file
just refactoring to prep for auth changes

move RequireAuth to its own file

---

src/components/MainLayout/OverviewMenu.tsx
src/pages/GivePage/Contribution.tsx
src/pages/GivePage/ContributorButton.tsx
src/pages/MembersPage/MembersTable.tsx

* Simple popover minWidth
* some straggling comment and eslint disable cleanup

UI Bugfix: Overview menu minWidth

---

README.md
src/components/MainLayout/MainHeader.tsx

- fixing a hoverOn problem for give drawer.
-changing the node model on the read me file, because we use 16 not 14 and that miss lead me badly a couple of days ago .
https://user-images.githubusercontent.com/94828675/204401128-172c3f4e-ae2e-4d2d-82a3-3906de90f216.mov
fixes #1701

give drawer on main header

---

api/hasura/actions/_handlers/createSampleCircle.ts
api/hasura/actions/_handlers/createSampleCircle_data.ts

This silences the eslint warnings in CI
This is part of a small sequence of changes to make CI more strict and
fail when eslint encounters a warning, as opposed to its current
behavior of passing even on warnings
manually ensured the sample circle creation code still works in my local
environment
@levity

Remove Non-null assertions in Sample Circle Code

---

api-test/hasura/actions/_handlers/deleteContribution.test.ts
api-test/hasura/actions/_handlers/updateContribution.test.ts

Mock console info logs in deleteContribution & updateContribution tests 
@topocount

Mute console info logs inside deleteContribution & updateContribution

---

src/config/features.ts
src/pages/GivePage/index.tsx

We want to try allowing for disabling this in a particular circle to see if it helps their experience.

add ability to disable distribute evenly for particular circles using our feature flagging mechanism

---

.env.example
src/features/auth/magic.tsx
src/hooks/useRequireSupportedChain.test.tsx
src/hooks/useRequireSupportedChain.ts
src/pages/VaultsPage/VaultTransactions.tsx
src/pages/VaultsPage/VaultsPage.tsx
src/utils/contractHelpers.ts

Some non-user-facing changes extracted from #1704

small fixes pre-magic connect

---

api-test/hasura/actions/_handlers/deleteCircle.test.ts

Adding units tests for deleteCircle action handler

Unit test for deleteCircle handler

---

api-test/hasura/actions/_handlers/restoreCoordinape.test.ts
api-test/helpers/users.ts
api/hasura/actions/_handlers/restoreCoordinape.ts

Adding Unit tests for restoreCoordinape action handler

Unit tests for restoreCoordinape handler

---

api-test/hasura/actions/_handlers/logoutUser.test.ts
api/hasura/actions/_handlers/logoutUser.ts

Adding Unit tests for logoutUser handler

 Unit Tests for logoutUser handler

---

api-test/hasura/actions/_handlers/deleteEpoch.test.ts
api-test/helpers/epochs.ts

Adding unit tests for deleteEpoch handler

Unit tests for deleteEpoch handler

---

src/components/MainLayout/CreateUserNameForm.tsx
src/components/MainLayout/MainHeader.tsx

remove close button from create user name modal
change address field from input to span

remove close button and update address field

---

api-test/hasura/actions/_handlers/deleteUser.test.ts
api/hasura/actions/_handlers/deleteUser.ts

update non existent user test flow to make it 100% coverage for deleteUser.ts action handler

Fix to deleteUser unit test

---

api-lib/gql/queries.ts
api/hasura/actions/_handlers/allocationCsv.ts

Fixes bug where give sent doesn't match give received.
If you deelte a user after an epoch ends, they should still get old give, so show them inthe lsit but as deleted.

Show users in csv if deleted after epoch ends

---

cypress/e2e/give.cy.ts
src/pages/GivePage/GiveAllocator.tsx

The GiveAllocator was display:none and in some cases this was still allowing the test to click it (not sure how). However it would fail in CI. I changed this to be conditionally rendered and then changed the click to allocate test to use a different user that wasn't opted out. I also broke the test up into smaller tests.

conditionally render the give allocator and improve the give test

---

.env.example
.github/workflows/CI.yml
README.md
api-lib/config.ts
api-lib/provider.ts
hardhat/constants.ts
hardhat/hardhat.config.ts
hardhat/scripts/start-ganache.sh
scripts/env.sh
src/features/auth/connectors.ts

Reworks some of the handling of ETH-related environment variables for more consistency and clarity.

Clean up some environment variables

---

src/pages/AssetMapPage/AMDrawer.tsx
src/pages/MembersPage/MembersTable.tsx
src/pages/MembersPage/NomineeTable.tsx
src/pages/MembersPage/getCircleUsers.ts
src/pages/MembersPage/index.tsx

resolves #1706 and resolves #1767
1- Fetch circle users by use-query
2- refetch data on focus
1- Go to members page.
2- Change your allocations. 
3-Go back to members page and check allocations listed on Members page 
expected: give sent column should be updated
4- I used another browser to sent give to my user and the data is updated on focus on my user browser

fix members page caching

---

src/App.tsx
src/components/MainLayout/MainHeader.test.tsx
src/components/MainLayout/MainHeader.tsx
src/components/MainLayout/MainLayout.tsx
src/components/MyAvatarMenu/MyAvatarMenu.tsx
src/features/theming/ThemeProvider.tsx
src/features/theming/ThemeSwitcher.tsx
src/features/theming/osPreference.ts
src/features/theming/storage.ts
src/utils/testing/index.tsx

Move stitches theming into a new provider that also honors the OS level theme preference. Default to legacy theme for now but can change to default to 'auto' when we have proper dark/light.

honor os dark/light mode preferences

---

src/lib/gql/mutations.ts
src/pages/NewNominationPage/NewNominationPage.tsx

resolves #1737
1- if the user has a profile with a name in our system. inform the nominator that this name will be user
1- Test 1
- Nominate a member with a unique name
- Nominate the same address in a different circle with a different name
expected: an alert will inform the nominator of the name that will be user

inform nominators about ignored names

---

src/pages/CircleAdminPage/CircleAdminPage.tsx

fixes #1800
used contracts from useContracts to hide and disable vaults related elements as it is undefined if the chain is not supported
access admin page after using Eth wallet and Polygon wallet the page should be available in both chains with different fixed payment section as below

support admin page loading on all chains

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/linkDiscordCircle.ts
api/hasura/actions/actionManager.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/discord_circle_api_tokens.yaml
hasura/metadata/databases/default/tables/discord_roles_circles.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1670355959284_create_table_discord_circle_api_tokens/down.sql
hasura/migrations/default/1670355959284_create_table_discord_circle_api_tokens/up.sql
hasura/migrations/default/1670795162160_alter_table_discord_roles_circles_alter_column_role/down.sql
hasura/migrations/default/1670795162160_alter_table_discord_roles_circles_alter_column_role/up.sql
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/pages/DiscordPage/DiscordPage.tsx

⚠️ Please read through https://github.com/coordinape/coordinape/pull/1741 first, it's in essence the same code plus a bit more:
* Rebase [Create_discord_API_token_table](https://github.com/coordinape/coordinape/tree/Create_discord_API_token_table) with [main](https://github.com/coordinape/coordinape)
* [Implement  LinkDiscordCircle handler](https://github.com/coordinape/coordinape/pull/1788/commits/1984110d293807c1e7a8efe3949969f1be796b32)
The reason for this PR is that I had to continue working on the discord bot and the previous PR was idle for a while.

feat: Create table to store api tokens for the discord bot and circle linking flow

---

.github/workflows/CI.yml
src/features/auth/WalletAuthModal.test.tsx
src/features/auth/WalletAuthModal.tsx
src/ui/Flex/Flex.tsx

fixes #1805 
also adds `gap` as a top-level prop for `Flex`

email login explainer modal

---

src/features/auth/useFinishAuth.ts
src/hooks/useApiBase.ts
src/pages/DefaultPage/DefaultPage.tsx
src/recoilState/app.ts

minor cleanup
just removing some cruft around recoil user data flows

remove rMyProfile

---

src/components/FormFileUpload.tsx
src/components/ProfileSkills.tsx
src/components/SkillToggles.tsx
src/pages/ProfilePage/ProfilePage.tsx

resolves #1813
1- replaced styling by makeStyles with stitches styles for profile page and profile page sub components:
FormFileUpload, ProfileSkills and skillToggles
2- replaced mui buttons by stitches styled buttons 
Tested by switching between dark and light mode

remove mui from profile page components

---

src/components/HintBanner.tsx
src/features/auth/RequireAuth.tsx
src/features/auth/index.ts
src/features/auth/magic.tsx
src/features/auth/store.ts
src/pages/VaultsPage/VaultsPage.tsx

show warning on vaults page for email-based wallets

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/updateProfile.ts
api/hasura/actions/actionManager.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_profiles.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/components/EditProfileModal.tsx
src/components/MainLayout/CreateUserNameForm.tsx
src/components/MainLayout/mutations.ts
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/lib/zod/formHelpers.ts

resolves #1826
1- check if the provided ENS matches the user address
1-enter a valid ENS for a different address in create user name modal or edit profile modal in the name field

validate ENS with addresses

---

src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/GivePage/index.tsx

Contrubution and allocation helptext markdown support

---

src/features/nav/NavItem.tsx

nav items lost some left padding somehow, adding it in specifically

tweak nav item padding slightly

---

src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/VaultTransactions.tsx

another simple,  perhaps transitional change

Fix vault tx row color

---

src/pages/VaultsPage/VaultRow.tsx
src/pages/VaultsPage/VaultTransactions.tsx

Switching to surface with some border radius

Fix vault row color

---

src/components/EditProfileModal.tsx
src/components/MainLayout/MainHeader.tsx
src/components/ProfileSkills.tsx
src/features/nav/NavCurrentCircle.tsx
src/features/nav/NavProfile.tsx
src/features/nav/SideNav.tsx
src/features/theming/ThemeSwitcher.tsx
src/pages/AssetMapPage/AMProfileCard.tsx
src/pages/CirclesPage/CirclesPage.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/pages/VaultsPage/VaultsPage.tsx
src/stitches.config.ts
src/ui/Modal.tsx
src/ui/layouts.tsx

* profile page ui fixes
* nav padding fixes
* global padding fixes
* side nav overflow hinting

Side nav gradient and padding fixes

---

src/features/nav/NavCircles.tsx
src/features/nav/NavOrgs.tsx
src/features/nav/SideNav.test.tsx

Just make sure basic things get rendered

super basic side nav unit test

---

src/components/LoadingModal.tsx
src/pages/CirclesPage/CirclesPage.test.tsx
src/ui/Modal.tsx

Old loader was always blue , new one is more fun and can use stitches colors
Note: this look makes it look blurry/ghosty but it isn't
https://www.loom.com/share/86aab23feeea41049634f6b35e6831e4
The modal for this still uses some MUI we need to remove the Modal

New stitches friendly loading modal

---

src/pages/DistributionsPage/DistributionForm.tsx
src/pages/DistributionsPage/DistributionsPage.tsx
src/pages/DistributionsPage/queries.ts

fixes #1846
1- vaults related features are disabled
2- Admins can still enter the allocation amount to export it on CSV

show allocation table for all chains

---

src/components/ToastContainer.tsx
src/hooks/useToast.tsx
src/pages/CirclesPage/CirclesPage.tsx
src/stitches.config.ts

- Add a copy icon to error toasts
- add drop shadows
- fix hover css
- turn off click to close

Toast Style Improvements

---

src/components/LoadingModal.tsx
src/pages/VaultsPage/CreateForm.tsx
src/pages/VaultsPage/VaultsPage.tsx
src/stitches.config.ts
src/ui/Button/Button.tsx
src/ui/Modal.tsx
src/ui/Panel/Panel.tsx

Fixing some bolding issues, shrinking loading indicator, making some panels less dark, fixing selected state on create vaults modal

tweaking modal styles and vault modal details, shrinking loading indicator

---

src/features/nav/NavProfile.tsx

When you navigate to anything outside the profile or click outside the profile box , it should dismiss.

dismiss profile when click outside

---

src/components/CopyCodeTextField.tsx
src/components/DragFileUpload.tsx
src/pages/AddMembersPage/AddMembersPage.tsx
src/pages/AddMembersPage/MagicLink.tsx
src/pages/AddMembersPage/NewMemberList.tsx
src/pages/AddMembersPage/TabButton.tsx

update the styling of add members form, copy link, error and success state

Add members

---

src/components/MainLayout/MainLayout.tsx
src/components/Table.tsx
src/features/nav/NavLogo.tsx
src/pages/AddMembersPage/NewMemberList.tsx
src/pages/CircleAdminPage/CircleAdminPage.tsx
src/pages/CircleAdminPage/HedgeyIntegrationSettings.tsx
src/pages/ContributionsPage/ContributionPanel.tsx
src/pages/ContributionsPage/ContributionRow.tsx
src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/CreateCirclePage/CreateCircleForm.tsx
src/pages/GivePage/GiveRowGrid.tsx
src/pages/GivePage/MyGiveRow.tsx
src/stitches.config.ts
src/ui/ContentHeader/ContentHeader.tsx
src/ui/FormLabel/FormLabel.tsx
src/ui/Modal.tsx
src/ui/Panel/Panel.tsx
src/ui/RadioGroup/RadioGroup.tsx
src/ui/Select/Select.tsx
src/ui/Table/Table.tsx

* removing nested panel styles
* radio buttons (perhaps need better hover state)
* outlines on contributions and allocation rows
* mygiverow bg

Branding sync 2

---

src/components/ToastContainer.tsx
src/stitches.config.ts

Fix the progress bar colors for lightmode and succes.
I noticed the success progress bar wasn't showing its progress bar.
There was an issue in our stitches, so cleanedthis up and defined one.

Fix progress bar colors

---

api-lib/event_triggers/createContributionInteractionEvent.ts
api/hasura/event_triggers/eventManager.ts
hasura/metadata/databases/default/tables/public_contributions.yaml

Track contribution created events in Mixpanel
Using a event_trigger pattern on the INSERT.
Verified these show in Mixpanel (logged to user and circle)

Track contribution created events in Mixpanel

---

src/pages/AssetMapPage/AssetMapPage.tsx

🪲 Map height fix

---

src/stitches.config.ts
src/ui/Panel/Panel.tsx
src/ui/TextArea/TextArea.tsx
src/ui/TextField/TextField.tsx

There were some scenarios where input fields didn't have a border and looked invisible.  changed the default.

Bugfix default form styles

---

src/pages/AssetMapPage/AMDrawer.tsx
src/pages/AssetMapPage/AMProfileCard.tsx
src/stitches.config.ts
src/ui/new-colors.ts

* tighter cards
* truncate epoch statement
* click the whole card to select member
* update colors with lighter secondary 1-3

Less chunky map drawer

---

src/stitches.config.ts
src/ui/ToggleButton.tsx

Yes-No button brand styling

---

src/config/features.ts

enable guild feature flag

---

src/components/MainLayout/CreateUserNameForm.tsx

Missing braces caused a bug in this.

fix ens validation

---

src/components/MainLayout/MainLayout.tsx
src/features/theming/ThemeSwitcher.tsx

Theme toggler style update

---

hasura/migrations/default/1674602440329_convert_epoch_repeat_data/down.sql
hasura/migrations/default/1674602440329_convert_epoch_repeat_data/up.sql

Hasura Migrations For new Epoch Schema

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/endEpoch.ts
api/hasura/actions/actionManager.ts
api/hasura/cron/epochs.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/pages/HistoryPage/EndEpochDialog.tsx
src/pages/HistoryPage/EpochForm.tsx
src/pages/HistoryPage/HistoryPage.tsx
src/pages/HistoryPage/getHistoryData.ts
src/pages/HistoryPage/mutations.ts

This can be deployed after the new epoch stuff is deployed. It is not a blocker for the others to be merged.
resolved #1882
add end epoch button to current epoch
preconditon: active epoch with gifts
1- Go to hisory page and click edit epoch on current epoch
2- click end epoch and confirm on the warning modal
3- the epoch should end and the gifts are refilled

End epoch feature

---

src/components/HintBanner.tsx
src/config/features.ts
src/pages/CirclesPage/CirclesPage.tsx
src/pages/ContributionsPage/ContributionIntro.tsx
src/pages/HistoryPage/HistoryPage.tsx
src/pages/VaultsPage/VaultsPage.tsx
src/ui/Panel/Panel.tsx

resolves #1905 
Show banner under feature flag and env REACT_APP_FEATURE_FLAG_EPOCH_TIMING_BANNER.
We probably will want to turn this off and remove it at some point in the future.
add blue banner to indicate changes to epoch settings

Add epoch settings changed banner

---

src/pages/CircleAdminPage/CircleLogoUpload.tsx
src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx

resolves #1915
1- refetch sidenav  and circles data after updating org logo
1- update the org logo. it should affect the side nav immediately
2- try the same in the old same and return to circles page and the logo should be updated too

refetch sidenav data after updating org logo

---

api-test/helpers/users.ts
src/pages/ContributionsPage/ContributionList.tsx
src/pages/ContributionsPage/ContributionsPage.tsx
src/pages/ContributionsPage/index.test.tsx
src/pages/ContributionsPage/types.ts
src/pages/ContributionsPage/util.tsx
src/pages/JoinCirclePage/JoinCirclePage.test.tsx
src/utils/testing/client.ts

This PR refactors ContributionsPage to make it a bit shorter, by pulling ContributionList into its own file and removing some unnecessary whitespace in JSX.

refactor ContributionsPage

---

src/components/Network/Network.tsx
src/features/nav/NavClaimsButton.tsx
src/features/nav/NavProfile.tsx
src/features/theming/ThemeSwitcher.tsx
src/pages/GivePage/EpochStatementDrawer.tsx
src/pages/GivePage/GiveAllocator.tsx
src/pages/GivePage/GiveRow.tsx
src/pages/GivePage/GiveRowGrid.tsx
src/pages/GivePage/index.tsx
src/stitches.config.ts
src/ui/Text/Text.tsx
src/utils/index.ts

* allocation card breakpoint adjustment
* primary button color in light mode
* network in profile menu adjustment
* wallet address center truncation, ty @CryptoGraffe 
* bugfix claim button beneath overflow gradient
**address center truncation:**
**allocation card gradient overflow:**

Allocation cards fixes, and more

---

cypress/e2e/createNominee.cy.ts
src/pages/MembersPage/Table.tsx
src/pages/NewNominationPage/NewNominationPage.tsx
src/ui/Flex/Flex.tsx
src/ui/Select/Select.tsx
src/ui/TextArea/TextArea.tsx
src/ui/TextField/TextField.tsx

Nominate member page

---

src/config/features.ts

One of our member DAOs wants to disable "Distribute Evenly"

adding another circle to the list for disable distribute evenly button

---

src/components/FormInputField.tsx
src/pages/HistoryPage/CurrentEpochPanel.tsx
src/pages/HistoryPage/EpochForm.tsx
src/pages/HistoryPage/EpochPanel.tsx
src/pages/HistoryPage/HistoryPage.tsx
src/pages/HistoryPage/Notes.tsx
src/stitches.config.ts
src/ui/Button/Button.tsx
src/ui/Link/Link.tsx
src/ui/Panel/Panel.tsx

* show received notes in current epoch
* epoch panel alignments.
* epoch form styling. 
* epoch preview styling/editing

Show notes in current epoch 📒

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/actions.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

update zeus schema
just the contents of `yarn generate`, no other changes

update zeus schema

---

src/lib/merkle-distributor/index.ts

need to accomodate an 19-decimal user issue
A proper fix to account for larger decimal quantities will follow

Double the dust allowance

---

hasura/metadata/databases/default/tables/discord_roles_circles.yaml
hasura/metadata/databases/default/tables/public_profiles.yaml

Add a few missing permissions to the discord bot

chore: Add missing permissions to the discord bot

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
docker-compose.yml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
package.json
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
yarn.lock

Our local image of hasura is has fallen nearly 10 increments behind our cloud console, so this is a proactive measure to avoid any issues due to inconsistencies

Upgrade Hasura

---

api/hasura/actions/_handlers/createSampleCircle.ts
api/hasura/actions/_handlers/createSampleCircle_data.ts

Add hardcoded addresses to sample circle users

---

src/pages/CreateCirclePage/CreateCircleForm.tsx

fix bug where new circle couldn't upload image.  This is basically reverting a change I made recently.

Fix circle upload bug

---

api/hasura/actions/_handlers/createSampleCircle_data.ts
scripts/db_seed_test.ts
scripts/util/seed.ts
src/ui/Avatar/Avatar.tsx

Make sure the Sample DAO profiles exist when seeding local db, set avatars for all the sample dao profiles.

create sample DAO profiles in db-seed with avatars

---

api-lib/HttpError.ts
api-test/hasura/cron/epochs_stubbed.test.ts
api/hasura/actions/_handlers/endEpoch.ts
api/hasura/cron/epochs.ts
src/features/activities/ActivityRow.tsx
src/features/activities/EpochEndedRow.tsx
src/features/activities/EpochStartedRow.tsx
src/features/activities/useInfiniteActivities.tsx

- Implement activity for epoch start and end
- Create UI for epoch started and ended

Add epoch start and epoch end to activities

---

src/features/activities/ActivityAvatar.tsx
src/features/activities/ActivityList.tsx
src/features/activities/ActivityProfileName.tsx
src/features/activities/ContributionRow.tsx
src/features/activities/NewUserRow.tsx
src/features/activities/RecentActivityTitle.tsx
src/features/activities/useInfiniteActivities.tsx
src/features/orgs/OrgPage.tsx
src/pages/ProfilePage/ProfilePage.tsx

adding activity list to profile and orgs, linking circle/avatar to pages and making some reusable components

org and profile activities and some cleanup / linkage

---

scripts/repl/org_membership.ts
src/components/MainLayout/MainLayout.tsx
src/hooks/migration.ts
src/hooks/useApiBase.ts
src/pages/CircleAdminPage/RemoveCircleModal.tsx

just some things that were worth quickly fixing as i was working on org member access

a few small fixes

---

api/hasura/cron/historicalActivity.ts

decrease BATCH_SIZE from 500>250 due to timeouts on prod

---

api-test/hasura/cron/epochs_stubbed.test.ts
api/hasura/cron/epochs.ts

fixing missing mocks and a sketchy missing question mark

---

api/login.ts
src/features/auth/RequireAuth.tsx
src/features/auth/login.ts
src/features/auth/useFinishAuth.ts
src/features/auth/useLogout.ts
src/features/auth/useSavedAuth.ts
src/hooks/useApiBase.ts

save profile id in local storage, in addition to address, so it can be used in queries

save profile id in auth local storage

---

hasura/metadata/databases/default/tables/public_activities.yaml
hasura/metadata/databases/default/tables/public_reactions.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1677875088114_create_table_public_reactions/down.sql
hasura/migrations/default/1677875088114_create_table_public_reactions/up.sql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

Enable reactions on activities

Create reactions db and hasura

---

src/features/activities/ActivityRow.tsx
src/features/activities/ContributionRow.tsx
src/features/activities/ReactionBar.tsx
src/features/activities/ReactionButton.tsx
src/features/activities/mutations.ts
src/features/activities/useInfiniteActivities.tsx

create reactions bar

---

api/hasura/cron/epochs.ts

This will fix the count in cron

use pending_gifts instead of permanent gifts for notification because we haven't refetched

---

src/features/activities/ContributionRow.tsx
src/features/activities/EpochCreatedRow.tsx
src/features/activities/EpochEndedRow.tsx
src/features/activities/EpochStartedRow.tsx
src/features/activities/NewUserRow.tsx

- flip epoch ended icon, small size circle avatars, end epoch Review button
- Change text to `joined` and shrink left padding on user join
- fix user join padding

activity touchups

---

src/features/activities/CircleLogoWithName.tsx
src/features/activities/ContributionRow.tsx
src/features/activities/EpochEndedRow.tsx
src/features/nav/NavCircleItem.tsx
src/features/nav/NavCurrentCircle.tsx
src/features/orgs/OrgPage.tsx
src/pages/CircleActivityPage/CircleActivityPage.tsx
src/pages/CircleAdminPage/CircleAdminPage.tsx
src/pages/CirclesPage/CirclesPage.tsx
src/pages/DistributionsPage/DistributionsPage.tsx
src/pages/JoinCirclePage/AddressIsNotMember.tsx
src/pages/JoinCirclePage/JoinCircleForm.tsx
src/pages/JoinCirclePage/JoinCirclePage.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/routes/paths.ts
src/routes/routes.tsx

Changing the default page for circles to Activity (e.g. /circle/3) and same for orgs. Rename overview to epochs (/history -> /epochs) and feature flag all of it.

IA updates

---

src/features/activities/ActivityRow.test.tsx
src/features/activities/heart.css
src/features/activities/reactions/ReactionOptions.tsx
src/features/nav/SideNav.test.tsx

- Add test for Other Circes in nav
- add activity row tests

activity tests and ui cleanup

---

src/features/activities/reactions/ReactionBar.tsx
src/features/activities/reactions/ReactionButton.tsx
src/features/activities/reactions/ReactionCounts.tsx
src/features/activities/reactions/ReactionOptions.tsx
src/stitches.config.ts
src/ui/Button/Button.tsx

reaction button style

---

src/config/features.ts
src/features/nav/SideNav.test.tsx

Enable feature flag to turn on activities

launch activity

---

api-lib/gql/mutations.ts
api/hasura/actions/_handlers/createCircle.ts
api/hasura/actions/_handlers/createSampleCircle.ts

We weren't creating the `circle_create` interaction event for circles created without a logo.
Paired with @CryptoGraffe to review in person

Create circle event fix

---

api-lib/event_triggers/createReactionInteractionEvent.test.ts
api-lib/event_triggers/createReactionInteractionEvent.ts
api/hasura/event_triggers/eventManager.ts
hasura/metadata/databases/default/tables/public_reactions.yaml

Add reaction logging to mixpanel

Add reaction logging to mixpanel

---

api-lib/event_triggers/sendInteractionEventToMixpanel.test.ts
api-test/helpers/circles.ts
scripts/env.sh

Add a test for adding circle & org names to events

---

api-test/helpers/circles.ts
api-test/helpers/organizations.ts
api-test/helpers/profiles.ts
api-test/helpers/users.ts
cypress/e2e/createEpoch.cy.ts
cypress/e2e/createNominee.cy.ts
cypress/e2e/createUser.cy.ts
cypress/e2e/createVault.cy.ts
cypress/e2e/give.cy.ts
cypress/e2e/updateCircle.cy.ts
cypress/e2e/updateUser.cy.ts
cypress/util/index.ts
src/lib/zod/index.ts

the default timeout was extended to 60s and 120 seems... excessive... let's see what happens in CI

remove all 120s timeouts from Cypress

---

api/hasura/actions/_handlers/updateAllocations.ts
src/config/constants.ts
src/features/auth/WalletAuthModal.tsx
src/lib/users.ts
src/pages/GivePage/AvatarAndName.tsx
src/pages/GivePage/index.tsx

default to sending 1% of GIVE to Coordinape during allocation

Set default donation to Coordinape

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/databases/default/tables/public_org_share_tokens.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1680029062925_alter_table_public_org_members_add_column_entrance/down.sql
hasura/migrations/default/1680029062925_alter_table_public_org_members_add_column_entrance/up.sql
hasura/migrations/default/1680036748448_create_org_share_tokens_table/down.sql
hasura/migrations/default/1680036748448_create_org_share_tokens_table/up.sql
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

- add entrance to org_members
- Create org_share_tokens
- Update types and expose org_share_tokens via graphql

Create org_share_tokens and other db work for orgs

---

src/pages/HistoryPage/EpochForm.tsx

Change default epoch start to current time

---

api-lib/airtable.ts
api-lib/event_triggers/createCircleCRM.ts

These columns were dropped / unused in our airtable.

removing unused fields

---

src/components/AvatarUpload.tsx
src/components/EditProfileModal.tsx
src/features/auth/useFinishAuth.ts
src/features/auth/useLoginData.ts
src/hooks/index.ts
src/hooks/legacyApi.ts
src/hooks/migration.ts
src/hooks/useApiAdminCircle.ts
src/hooks/useApiWithProfile.ts
src/pages/AddMembersPage/AddMembersPage.tsx
src/pages/AssetMapPage/AMDrawer.tsx
src/pages/CircleAdminPage/CircleAdminPage.tsx
src/pages/CircleAdminPage/RemoveCircleModal.tsx
src/pages/CreateCirclePage/CreateSampleCircle.tsx
src/pages/JoinPage/JoinForm.tsx
src/recoilState/app.ts

just removing a grouping that is no longer relevant

give fetchManifest and fetchCircle their own hooks

---

src/features/map/AMDrawer.tsx
src/features/map/AMForceGraph.tsx
src/features/map/AMProfileCard.tsx
src/features/map/state.ts
src/pages/AssetMapPage/index.ts
src/pages/MapPage/index.tsx
src/recoilState/app.ts
src/recoilState/index.ts
src/routes/routes.tsx

this makes it a bit easier to see what code is associated with the map

move map files into src/features/map

---

src/pages/ProfilePage/ProfilePage.tsx
src/pages/ProfilePage/queries.ts
src/recoilState/app.ts

It was only being used by one page

remove useProfile

---

src/features/map/AMDrawer.tsx
src/features/map/AMProfileCard.tsx
src/features/map/queries.ts
src/hooks/migration.ts
src/pages/MapPage/index.tsx
src/routes/routes.tsx

Hide pending give on map by hiding current epoch, not redirecting

alternate implementation for hiding pending GIVE on map

---

cypress/e2e/createUser.cy.ts
src/features/nav/NavCurrentCircle.tsx

Fix cypress test
THis was broken by ORg Members link being added

Visit circle members page directly

---

src/pages/AddMembersPage/AddMembersPage.tsx

Adding org member copy update

---

api/hasura/cron/epochs.ts

Expecting to see these logs in DD

Add logging to cron epochs

---

src/pages/MembersPage/MembersTable.tsx

fixes a regression caused by #1995

fix visibility of Coordinape user in members list

---

api-lib/constants.ts
api-lib/sendSocialMessage.test.ts
api-lib/sendSocialMessage.ts
api-test/helpers/circles.ts

resolves #2063
parallelized the different actions in sendSocialMessage and make sure that one of them failing doesn't prevent the rest from occurring

Parallelize sendSocialMessage actions

---

api-lib/gql/mutations.ts
src/features/auth/useFinishAuth.ts
src/features/nav/NavCircles.tsx
src/features/nav/NavCurrentOrg.tsx
src/hooks/legacyApi.ts
src/pages/CreateCirclePage/CreateCircleForm.tsx
src/pages/JoinPage/JoinForm.tsx

Admin was not being added to new org upon circle creation

Bugfix Members link not showing up after org creation

---

hasura/metadata/databases/default/tables/public_pending_token_gifts.yaml
hasura/metadata/databases/default/tables/public_token_gifts.yaml
src/features/map/AMDrawer.tsx
src/features/map/AMForceGraph.tsx
src/features/map/AMProfileCard.tsx
src/features/map/queries.ts
src/features/map/state.ts
src/features/nav/NavCurrentCircle.tsx
src/pages/MapPage/index.tsx
src/routes/routes.tsx
src/utils/modelExtenders.ts

- add Map link to side nav for all circles
- move route so org-wide access is permitted
in initial testing, it seems like the map code already works for an org member not in the circle (after the changes in #2087 and #2094)

allow access to map for all circles in org

---

src/pages/CreateCirclePage/CreateCircleForm.tsx

Needed to add fetchManifest before attempting to navigate to `members`. Thanks @levity

🪲 Should navigate to members page after circle creation

---

src/features/nav/NavItem.tsx
src/features/nav/NavProfile.tsx
src/pages/CirclesPage/CirclesPage.tsx

old / new
simple breakpoint fixes
bug getting fixed for nav:
those links are incorrectly highlighted as they match the `/` path. gave them unique url param.

Minor Bug-fixes: circle row breakpoint & profile nav current

---

src/features/nav/NavLabel.tsx
src/stitches.config.ts

UI: Uppercase side nav labels

---

api/cosoul/[address].ts
scripts/serve_dev.ts
src/features/cosoul/ViewPage.tsx
src/features/cosoul/index.tsx
src/routes/paths.ts
src/routes/routes.tsx

Create public page to view any minted cosoul.
- creates a serverless function that allows unauthenticated access to minted cosoul data, with a 5 min vercel cache
- setup UI on page

cosoul public view

---

src/features/cosoul/MintOrBurnButton.tsx

Disable the mint button and show a LoadingModal while the mint is in progress.

show loader while tx is pending

---

src/features/cosoul/art/CoSoulArt2.stories.tsx

link to another cosoul story to help demonstrate the webgl canvas issue

Storybook linking cosoul bug test tool

---

api-lib/config.ts
cypress/e2e/createVault.cy.ts
src/config/env.ts
src/config/features.ts
src/features/analytics/index.ts
src/features/cosoul/CoSoulArtOnlyLayout.tsx
src/features/cosoul/api/cosoul.ts

This will hopefully fix this error when accessed via opensea: Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.

Try catch localStorage access

---

api/cosoul/metadata/[tokenId].ts
src/features/cosoul/art/CoSoulArtPublic.tsx

Show org that contributed pgive for member

Update opensea description

---

api-lib/config.ts
api/hasura/actions/_handlers/syncCoSoul.ts
src/features/cosoul/api/cosoul.ts

This reverts commit 0d5bee262dce317fe6327e67d71f2d245304dde9.
There API doesn't support this for OP-mainnet so removing

Revert "ping opensea after mint (#2218)"

---

src/features/nav/SideNav.tsx

on mobile phones sometimes the keyboard and gui is causing the profile menu and bottom buttons to be unclickable.  This fixes that issue

🐛 Bugfix: hopefully fix scroll bug for mobile menu

---

src/config/features.ts
src/features/orgs/OrgPage.tsx
src/pages/CircleActivityPage/CircleActivityPage.tsx
src/pages/ContributionsPage/ContributionsPage.tsx

Remove `activity_contributions` feature flag

⚡️Turn On Activity Contributions ⚡️

---

src/features/activities/useInfiniteActivities.tsx

Fixes a bug in streaming when we don't have a defined starting place.

fix undefined streaming bug

---

src/features/orgs/OrgPage.tsx
src/pages/CircleActivityPage/CircleActivityPage.tsx
src/pages/ContributionsPage/CircleSelector.tsx
src/pages/ContributionsPage/ContributionForm.tsx
src/ui/Avatar/Avatar.tsx

* fix circle indicator
* also fix radix avatar fallback bug
* also, fixing a strange posting bug that can sometimes post to the wrong circle when circle switching (needed to add `key={circle.id}`
* code cleanup

🐞 Bugfix: activity contribution circle identifier

---

src/components/HintBanner.tsx
src/features/nav/NavProfile.tsx
src/features/nav/SideNav.tsx
src/pages/AccountPage/AccountPage.tsx
src/pages/ProfilePage/EmailSettings/EditEmailForm.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/routes/paths.ts
src/routes/routes.tsx
src/stitches.config.ts
src/ui/ContentHeader/ContentHeader.tsx

* account settings page
* nav display bug fixing
* Remove `recent transactions` modal

Account settings page

---

src/components/MainLayout/MainLayout.tsx
src/features/nav/SideNav.tsx
src/pages/ProfilePage/EmailSettings/EditEmailForm.tsx
src/pages/ProfilePage/EmailSettings/EmailBanner.tsx
src/pages/ProfilePage/EmailSettings/EmailModal.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/ui/Modal.tsx
src/ui/Text/Text.tsx

If there are emails added and none of them are verified, show this banner
(Not sure if I am doing this query in the most economical way)

Feat: verify email banner

---

src/components/MainLayout/MainLayout.tsx
src/features/nav/SideNav.tsx
src/pages/HistoryPage/CurrentEpochPanel.tsx
src/pages/HistoryPage/HistoryPage.tsx
src/pages/ProfilePage/EmailSettings/EmailBanner.tsx
src/pages/ProfilePage/EmailSettings/EmailCTA.tsx
src/pages/ProfilePage/EmailSettings/EmailPromo.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/pages/VerifyEmailPage/VerifyEmailPage.tsx

Email Promos and CTAs

---

src/pages/ProfilePage/EmailSettings/EditEmailForm.tsx
src/pages/VerifyEmailPage/VerifyEmailPage.tsx
src/ui/Panel/Panel.tsx

* change color or verification notification
* add "view email settings" link to verification page

UI: verify your email messaging color.  

---

src/pages/CreateCirclePage/CreateCircleForm.tsx
src/pages/CreateCirclePage/mutations.ts

Remove email field from circle creation form

---

src/config/features.ts
src/features/nav/NavProfile.tsx
src/pages/ProfilePage/EmailSettings/EmailBanner.tsx
src/pages/ProfilePage/EmailSettings/EmailCTA.tsx
src/pages/ProfilePage/EmailSettings/EmailModal.tsx
src/pages/ProfilePage/EmailSettings/EmailPromo.tsx
src/ui/Modal.tsx

remove email feature flag to turn on collecting email in prod

Turn on email collection

---

yarn.lock

for some reason the yarn lock file didn't get updated in the babel fix from earlier today

`yarn.lock` babel update

---

api-test/hasura/actions/_handlers/updateEpoch.test.ts
src/features/cosoul/CoSoulCreate.tsx
src/utils/contractHelpers.ts

cosoul minting fees is updated

update mint cosoul message

---

src/components/MarkdownGuide.tsx
src/features/activities/replies/ReplyForm.tsx
src/features/soulkeys/PostForm.tsx
src/pages/ContributionsPage/ContributionForm.tsx
src/pages/SoulKeyActivityPage.tsx
src/pages/ViewSoulKeyPage/ViewSoulKeyPageContents.tsx

Rename Contribution to Post and add Prompts

Rename Contributions to Post via itemNounName prop Also add tooltip show/hide bool

---

src/features/cosoul/CoLinksSplashLayout.tsx

feature flag colinks splash page

---

src/features/colinks/CoLinksNav.tsx
src/features/colinks/CoLinksNavProfile.tsx
src/features/cosoul/CoLinksMintPage.tsx
src/features/cosoul/CoSoulArtContainer.tsx
src/features/cosoul/CoSoulCompositionRep.tsx
src/features/invites/InviteCodeLink.tsx
src/pages/CoSoulExplorePage/CoSoulItem.tsx
src/pages/colinks/RepScorePage.tsx
src/ui/ContentHeader/ContentHeader.tsx

View rep detail in colinks with cosoul

---

src/features/activities/ContributionRow.tsx
src/features/activities/replies/RepliesBox.tsx
src/features/colinks/CoLinksNav.tsx
src/features/colinks/wizard/CoLinksWizard.tsx
src/features/colinks/wizard/WizardBuyOtherLinks.tsx
src/features/colinks/wizard/WizardInstructions.tsx
src/features/colinks/wizard/WizardSteps.tsx
src/features/cosoul/CoLinksCoSoulArtContainer.tsx
src/features/cosoul/CoLinksMintPage.tsx
src/features/cosoul/CoSoulCompositionRep.tsx
src/features/cosoul/InitialRepDetail.tsx
src/features/cosoul/MintingModal.tsx
src/keyframes.ts
src/pages/AccountPage/EditProfileInfo.tsx
src/pages/colinks/wizard/WizardStart.tsx

* Adding spider arms to colinks minting page
* more visible hover cta button on activity items for encouraging replies
* wizard tweaks
* copy changes
* add rep score to main nav

Show cosoul data in wizard mint flow

---

src/features/colinks/BuyOrSellCoLinks.tsx
src/features/colinks/CoLinksNav.tsx
src/features/cosoul/CoLinksMintPage.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/CoLinksTaskCards.tsx
src/pages/colinks/ViewProfilePage/CoLinksProfileHeader.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx
src/ui/layouts.tsx

Goal: nudge people to add more rep and buy links
task cards for:
rep below # (currently set to <51)
user hasn't purchased anyone other links
Showing these on the activity page and on the current user profile page.

Task cards

---

src/pages/CoSoulExplorePage/CoSoulItem.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx

* can't resize the webgl canvas dynamically, so I fixed the whole right column to a single width.  
* Adjusted the stats display below the art

WebGL CoSoul on CoLinks profile page

---

src/features/colinks/wizard/WizardBuyOtherLinks.tsx
src/features/colinks/wizard/WizardInstructions.tsx
src/features/colinks/wizard/WizardSteps.tsx
src/features/colinks/wizard/WizardSwitchToOptimism.tsx
src/pages/colinks/wizard/WizardStart.tsx

short fat screens get love.  adjust instruction card header.

Wizard aspect ratio media queries and gradient bgs

---

src/components/CopyCodeTextField.tsx
src/components/MarkdownGuide.tsx
src/features/activities/replies/ReplyForm.tsx
src/pages/ContributionsPage/ContributionForm.tsx

* remove the onBlur event, 
* add some spacing to the copy content

bugfix: markdown helper

---

src/components/ComboBox.tsx
src/features/colinks/CoLinksNav.tsx
src/features/colinks/LinkTxProgress.tsx
src/features/colinks/wizard/CoLinksWizard.tsx
src/features/colinks/wizard/WizardInstructions.tsx
src/features/cosoul/CoLinksCoSoulArtContainer.tsx
src/features/cosoul/CoLinksMintPage.tsx
src/features/cosoul/CoSoulCompositionRep.tsx
src/features/invites/RedeemInviteCode.tsx
src/features/nav/NavLogo.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/InvitesPage.tsx

* Some various UI tweaks
* medium and some small screen breakpoint fixes
* minting animation timing now faster
* cmdk border outline in input field

Smaller UI fixes, breakpoint fixes

---

src/features/CoLinksWalletMenu.tsx
src/features/auth/store.ts
src/features/colinks/CoLinksContext.tsx
src/features/colinks/wizard/CoLinksWizardLayout.tsx
src/features/colinks/wizard/WizardInstructions.tsx
src/features/cosoul/CoLinksSplashNav.tsx
src/features/theming/ThemeSwitcher.tsx
src/hooks/useWeb3React.tsx
src/pages/colinks/LaunchPage.tsx
src/pages/colinks/wizard/WizardStart.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts
src/ui/Button/Button.tsx

* naked url is the launcher, which will take you to wizard start or col…inks app.  
* auth fixes with g-dawg
* colinks marketing page at `/info`

.com root url is now wizard start

---

src/features/colinks/wizard/WizardInstructions.tsx
src/features/invites/RedeemInviteCode.tsx
src/features/invites/WaitListForm.tsx
src/pages/colinks/wizard/WizardStart.tsx

* small screen stuff
* refactor email invite form out of wiz start
* no more autocomplete email

small screen fixes.

---

src/pages/colinks/wizard/WizardStart.tsx

Learn more button size

---

api-lib/postmark.ts
src/pages/colinks/VerifyEmailPage.tsx
src/routes/coLinksRoutes.tsx

Colinks verification email

---

src/components/OrBar.tsx
src/features/invites/RedeemInviteCode.tsx
src/features/invites/WaitListForm.tsx
src/pages/colinks/wizard/WizardStart.tsx

start page copy

---

src/components/ComboBox.tsx
src/features/colinks/CoLinksNav.tsx
src/features/colinks/CoLinksStats.tsx
src/pages/ContributionsPage/ContributionForm.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ViewProfilePage/CoLinksProfileHeader.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx
src/ui/MarkdownPreview/MarkdownPreview.tsx
src/ui/Modal.tsx
src/ui/layouts.tsx

Cmdk section styles

---

src/features/colinks/wizard/CoLinksWizardLayout.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ViewProfilePage/CoLinksProfileHeader.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx
src/stitches.config.ts
src/ui/ContentHeader/ContentHeader.tsx
src/ui/layouts.tsx

Mobile fixes

---

src/features/colinks/CoLinksNav.tsx
src/pages/colinks/HighlightsPage.tsx

highlights style tweaks

---

src/pages/CoSoulExplorePage/CoSoulItem.tsx

stats should wrap when they get too long

UI: cosoul art stats wrap and spacing

---

src/features/SearchBox/SearchBox.tsx
src/features/colinks/api/updateHolders.ts
src/pages/colinks/ViewProfilePage/ViewProfilePage.tsx

Fix update holders

---

src/features/colinks/api/updateHolders.ts

fix txhash

---

src/features/activities/reactions/ReactionOptions.tsx
src/features/colinks/ScoreComponent.tsx
src/pages/colinks/InvitesPage.tsx
src/pages/colinks/NotificationsPage.tsx
src/pages/colinks/ViewProfilePage/CoLinksProfileHeader.tsx
src/ui/layouts.tsx

notification fixes.  gutter fixes on home.  other small screen fixes

UI: Mobile fixes

---

api/hasura/actions/_handlers/updateProfile.ts
src/lib/zod/formHelpers.ts

prohibit websites that we can validate through social linking

---

hasura/metadata/actions.yaml
hasura/migrations/default/1703099550654_fix_reply_count_trigger/down.sql
hasura/migrations/default/1703099550654_fix_reply_count_trigger/up.sql

fix reply count triggers

---

src/pages/colinks/SearchPage.tsx

Make interests fuzzy

---

src/features/colinks/BuyButton.tsx
src/features/colinks/BuyOrSellCoLinks.tsx
src/features/colinks/CoLinksContext.tsx
src/features/colinks/CoLinksLayout.tsx
src/features/colinks/useCoLinks.ts
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ViewProfilePage/CoLinksProfileHeader.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx

use our own rpc for all non-buy non-sell interactions

---

src/features/activities/ActivityList.tsx
src/features/activities/useInfiniteActivities.tsx
src/features/orgs/OrgPage.tsx
src/pages/CircleActivityPage/CircleActivityPage.tsx
src/pages/ContributionsPage/ContributionForm.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx

do a burst of quick polling instead of using websockets, cmd+enter to send

---

src/features/colinks/BuyButton.tsx

Fix this front run error:
With:
TODO: add fun graphics.
How to reproduce:
Change to invoke the buyLinks method twice in localhost

Frontrun errors

---

hasura/metadata/actions.yaml
hasura/migrations/default/1703115149809_alter_table_public_contributions_alter_column_description/down.sql
hasura/migrations/default/1703115149809_alter_table_public_contributions_alter_column_description/up.sql
src/pages/ContributionsPage/ContributionForm.tsx

Limit contribution text

---

src/features/colinks/InifiniteMembersList.tsx
src/features/colinks/useInfiniteMembers.tsx
src/pages/ContributionsPage/ContributionForm.tsx
src/pages/colinks/explore/HighestRepScorePage.tsx
src/pages/colinks/explore/HoldingMostLinksPage.tsx
src/pages/colinks/explore/MostLinksPage.tsx
src/pages/colinks/explore/NewestMembersPage.tsx

infinite scroll member utility and converting all the leaderboard pages

---

src/features/colinks/InifiniteMembersList.tsx
src/features/colinks/useCoLinks.ts

invalidate better

---

package.json
src/App.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ExplorePage.tsx
src/pages/colinks/HighlightsPage.tsx
src/pages/colinks/InvitesPage.tsx
src/pages/colinks/LinkHistoryPage.tsx
src/pages/colinks/LinkHoldersPage.tsx
src/pages/colinks/LinkHoldingsPage.tsx
src/pages/colinks/NotificationsPage.tsx
src/pages/colinks/RepScorePage.tsx
src/pages/colinks/TradesPage/index.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx
src/pages/colinks/explore/ExploreSkills.tsx
src/pages/colinks/explore/HighestRepScorePage.tsx
src/pages/colinks/explore/HoldingMostLinksPage.tsx
src/pages/colinks/explore/MostLinksPage.tsx
src/pages/colinks/explore/NewestMembersPage.tsx
src/pages/colinks/explore/PeopleWithSkill.tsx
yarn.lock

react-helmet-async and proper page titles

---

hasura/migrations/default/1703189566738_alter_table_public_replies_alter_column_reply/down.sql
hasura/migrations/default/1703189566738_alter_table_public_replies_alter_column_reply/up.sql

restrict reply length to 10k

---

src/features/colinks/BuyOrSellCoLinks.tsx
src/features/cosoul/CoSoulButton.tsx

Link to bridges page instead of Op bridge

---

api-lib/event_triggers/createNotificationPosts.ts
api-lib/event_triggers/createNotificationReplies.ts
api/hasura/event_triggers/eventManager.ts
hasura/metadata/databases/default/tables/public_contributions.yaml
src/pages/colinks/NotificationsPage.tsx

Post notifications

---

src/features/activities/ContributionRow.tsx
src/features/colinks/LinkHoldings.tsx
src/pages/colinks/LinkHoldingsPage.tsx
src/pages/colinks/NotificationsPage.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx

small tweaks and reverting overflow:scroll

---

src/features/colinks/api/updateHolders.ts

fix handling of last sell

---

src/features/colinks/LinkHoldings.tsx

fix the count on link holdings

---

src/ui/MarkdownPreview/MarkdownPreview.tsx

markdown table styles

---

src/features/colinks/wizard/WizardCoSoul.tsx

add minting fees value to colinks wizard

---

src/features/invites/RedeemInviteCode.tsx

trim and lowercase the invite code

---

src/pages/colinks/NotificationsPage.tsx

fixing reply notification

---

src/components/MarkdownGuide.tsx
src/features/activities/PostRow.tsx
src/features/activities/reactions/ReactionBar.tsx
src/features/activities/reactions/ReactionOptions.tsx
src/features/activities/replies/RepliesBox.tsx
src/features/activities/replies/ReplyForm.tsx
src/features/colinks/CoLinksNav.tsx
src/features/colinks/MentionsTextArea.tsx
src/features/nav/SideNav.tsx
src/pages/colinks/ActivityPage.tsx
src/ui/Text/Text.tsx
src/ui/layouts.tsx

also overflow bugfixes and breakpoint fixes

🐞 Mentions z-index

---

src/features/colinks/LinkHolders.tsx
src/features/colinks/LinkHoldings.tsx

fixing query caching issue

---

src/features/activities/PostRow.tsx
src/features/activities/reactions/ReactionCounts.tsx
src/features/colinks/BuyOrSellCoLinks.tsx
src/features/colinks/Poaps.tsx
src/features/colinks/SimilarProfiles.tsx
src/ui/MarkdownPreview/MarkdownPreview.tsx
src/ui/layouts.tsx

* layout should use variable for min width right column
* reactions should wrap
* icon fixes

Various small UI fixes

---

src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx

show profile details on mobile with toggle.  or if you are not connected at all, show it by default
while on mobile:
* In left screen, users are not connected at all and see no posts.  in that state, show the details by default
* In the right screen there is a connection, so show a toggle

show profile details on mobile

---

src/features/CoLinksWalletMenu.tsx

show magic wallet on colinks wizard in the wallet menu

show magic wallet on colinks wizard

---

src/features/CoLinksWalletMenu.tsx
src/features/auth/WalletAuthModal.tsx
src/features/colinks/BuyOrSellCoLinks.tsx
src/features/colinks/CoLinksLayout.tsx
src/features/colinks/wizard/WizardBuyOtherLinks.tsx
src/features/colinks/wizard/WizardInstructions.tsx
src/features/cosoul/CoSoulButton.tsx
src/features/cosoul/InitialRepDetail.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx
src/pages/colinks/explore/CoLinksMember.tsx
src/ui/Modal.tsx

* for some reason, useMobileDetect isn't working on Ash's phone with chrome, so I'm composing the profile details with media query.  Also fixing a bunch of other display bugs on mobile
* added a mini wallet menu for mobile

Mo mobile fixes

---

src/features/colinks/CoLinksNav.tsx

don't clip the profile nav

---

src/components/HelpButton.tsx
src/routes/paths.ts

add colinks docs link to help button

---

api-lib/openai.ts
api/hasura/actions/_handlers/getHeadlines.ts

remove reactions from ai input for highlights
increase limit size and duration

Remove reactions from highlights

---

api-lib/config.ts

Dont use public api keys

---

api-lib/config.ts
api/hasura/actions/_handlers/updateProfile.ts
hasura/metadata/actions.yaml

- Fix env var lookup
- cleanup names

fix alchemy

---

src/features/colinks/PostForm.tsx

Note: these are not tied to accounts so will persist across different accounts...

Store psots in local storage so they dont get lost

---

public/index.html
src/App.tsx

bifurcate the domains for plausible

---

src/features/auth/WalletAuthModal.tsx

replace Ethereum with colinks and coordinape

---

api/hasura/actions/_handlers/syncCoSoul.ts

reomove object.assign from syncCosoul

reomove object.assign from syncCosoul 

---

src/components/CopyCodeTextField.tsx
src/components/MarkdownGuide.tsx
src/ui/Tooltip/Tooltip.tsx

🐞 fix markdown helper flicker and layout

---

src/features/colinks/useCoLinks.ts
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx

hide no posts panel until connected with the user

hide no posts for unconnected users

---

api/email/unsubscribe/[unsubscribeToken].ts

fix colinks notifications unsubscribe

---

src/features/colinks/CoLinksNav.tsx

bugfix: sidescroll side nav

---

src/features/cosoul/art/CoSoulArtDisplay.js

fixing glview stop error

---

package.json
pnpm-lock.yaml

Package upgrades

---

api-lib/config.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/generateOneTimeUpload.ts
api/hasura/actions/actionManager.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/cron_triggers.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/features/colinks/PostForm.tsx
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

Implement image upload

---

api-lib/config.ts
api-lib/gql/__generated__/zeus/index.ts
api/hasura/actions/_handlers/uploadProfileAvatar.ts
api/hasura/actions/_handlers/uploadProfileBackground.ts
hasura/metadata/actions.graphql
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
scripts/serve.sh
src/common-lib/uuid.ts
src/components/AvatarUpload.tsx
src/features/colinks/PostForm.tsx
src/features/images/upload.ts
src/lib/gql/__generated__/zeus/index.ts
src/lib/gql/mutations.ts
src/pages/ProfilePage/ProfilePage.tsx

Migrate image upload to cloudflare for
avatars
circle logo
org. logo
backgrounds

Cloudflare avatar images

---

scripts/serve.sh
scripts/serve_dev.ts
vite.config.ts

fix hot reloading by making vite the proxy

---

_api/email/unsubscribe/[unsubscribeToken].ts

Fix try/catch so serverless func doesn't crash on errors

---

src/ui/MarkdownPreview/MarkdownPreview.tsx
src/ui/Modal.tsx

Hover state shows an eye icon on md images
images open in a pretty big view

Feed image sizes and lightbox

---

hasura/metadata/cron_triggers.yaml

Code deleted, but left the cron in hasura

Remove old cron

---

src/pages/ProfilePage/AuthDevice/AuthDeviceForm.tsx

Change text

---

src/ui/MarkdownPreview/LightboxImage.tsx
src/ui/MarkdownPreview/MarkdownPreview.tsx

bug: if there are more than one image in the markdown, the modal is NOT happy.
make it happy by lightboxing image in a component

Double image bug 

---

src/components/SkillComboBox/SkillComboBox.tsx
src/features/activities/ActivityRow.test.tsx
src/features/points/CoLinksGiveButton.tsx
src/features/points/getAvailablePoints.ts
src/features/points/getMyAvailablePoints.ts
src/pages/AccountPage/AccountPage.tsx
src/pages/AccountPage/SkillAndTopicPicker.tsx

Give skills

---

src/utils/domain.ts
src/utils/reporting.ts

Fix setnry environment reporting issues

Properly set environment in Sentry

---

_api/email/unsubscribe/[unsubscribeToken].ts
src/pages/UnsubscribeEmailPage/UnsubscribeEmailPage.tsx
vercel.json

Fix API handling of unsubscribe.

Fix Vercel Unsubscribe api

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/databases/default/tables/public_skills.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/components/SkillComboBox/SkillComboBox.tsx
src/features/activities/PostRow.tsx
src/features/points/CoLinksGiveButton.tsx
src/features/points/getAvailablePoints.ts
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

sort skills in the dropdown

---

src/features/colinks/CoLinksNav.tsx
src/features/colinks/EthDenverContestBanner.tsx

just moving it to a separate component

component eth denver banner

---

hasura/migrations/default/1708974294396_drop_index_unique_contribution_per_big_question/down.sql
hasura/migrations/default/1708974294396_drop_index_unique_contribution_per_big_question/up.sql
src/pages/colinks/explore/BigQuestionPage.tsx

allow multiple answers to BigQ

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/databases/default/tables/public_profiles_public.yaml
hasura/metadata/databases/default/tables/public_skills.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/features/colinks/LeaderboardMostGive.tsx
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/pages/colinks/ExplorePage.tsx
src/pages/colinks/explore/TabButton.tsx

Create MostGive received leaderboard
Sort by most give received

MostGive received leaderboard

---

src/features/points/CoLinksGiveButton.tsx

Give promo modal

---

src/features/points/GiveReceived.tsx

@crabsinger and I fixed this previously, but I get it got lost in the merging

🐞 Add missing key to map

---

src/features/colinks/CoLinksNav.tsx

don't show the give available menu thing if FF not enabled

🪲 feature flag mobile give menu

---

src/features/points/CoLinksGiveButton.tsx
src/stitches.config.ts
src/ui/Text/Text.tsx

fix nested button issue.  add hover color to give button

---

src/features/points/GiveAvailablePopover.tsx
src/features/points/usePoints.tsx

Show next give at in relative time

---

src/config/features.ts
src/features/activities/PostRow.tsx
src/features/colinks/CoLinksNav.tsx
src/features/colinks/CoLinksStats.tsx
src/features/points/CoLinksGiveButton.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ExplorePage.tsx
src/pages/colinks/NotificationsPage.tsx
src/pages/colinks/ViewProfilePage/CoLinksProfileHeader.tsx

remove GIVE feature flag

---

src/features/points/CoLinksGiveButton.tsx

add max width to skill picker

---

src/components/SkillComboBox/SkillComboBox.tsx
src/features/colinks/SkillTag.tsx
src/features/points/CoLinksGiveButton.tsx
src/features/points/GiveReceived.tsx
src/features/points/PostGives.tsx
src/pages/AccountPage/SkillAndTopicPicker.tsx
src/stitches.config.ts

🪲 Bugfix/skill tag overflow

---

src/components/SkillComboBox/SkillComboBox.tsx
src/features/points/CoLinksGiveButton.tsx
src/pages/AccountPage/SkillAndTopicPicker.tsx

We were improperly showing the profiles skills at top of list

Fix query issue with skill picker

---

src/features/points/CoLinksGiveButton.tsx

Fix skill srt to lowercase

---

cypress/support/commands.ts
src/features/auth/WalletAuthModal.test.tsx
src/features/auth/WalletAuthModal.tsx

instead of disable metamask, install metamask

---

src/features/activities/ActivityAvatar.tsx
src/features/activities/PostRow.tsx
src/features/activities/replies/RepliesBox.tsx

mobile avatar size and padding

---

src/features/activities/PostRow.tsx
src/features/activities/reactions/ReactionBar.tsx
src/features/colinks/PostForm.tsx
src/features/points/CoLinksGiveButton.tsx
src/pages/colinks/NotificationsPage.tsx

Hover styles for buttons on post rows
give notification style
UI bugfix (edit buttons should be flush right)

UI: Minor style updates

---

src/components/HelpButton.tsx
src/components/MainLayout/MainLayout.tsx
src/features/colinks/CoLinksLayout.tsx
src/features/colinks/CoLinksNav.tsx
src/features/nav/SideNav.tsx

hide help button in mobile, but show in hamburger menu

---

hardhat/test/01-cosoul/00-cosoul.ts

Cosoul: implement mintTo function, authorised by signer only

Cosoul: implement mintTo function

---

src/pages/colinks/NotificationsPage.tsx

Link to cast from notifications

---

_api/webhooks/neynar_mention.ts

No give to self; import receiver profile

---

.circleci/continue-config.yml
package.json
pnpm-lock.yaml

upgrade vite vercel plugin to v5

---

.circleci/continue-config.yml
package.json
pnpm-lock.yaml

Reverts coordinape/coordinape#2802

Revert "upgrade vite vercel plugin to v5"

---

.circleci/continue-config.yml
package.json
pnpm-lock.yaml

trying 5.0.3

---

hasura/migrations/default/1712020732772_alter_table_public_profiles_alter_column_invite_code_redeemed_at/down.sql
hasura/migrations/default/1712020732772_alter_table_public_profiles_alter_column_invite_code_redeemed_at/up.sql
src/features/colinks/wizard/CoLinksWizard.tsx
src/pages/colinks/LaunchPage.tsx

disable (perhaps temporarily) the need for invite codes

---

_api/frames/ErrorFrame.tsx
_api/frames/FrameMeta.tsx
_api/frames/personas/PersonaOneFrame.tsx
_api/frames/router.tsx

error message handling in the ErrorFrame component

---

_api/frames/FrontDoorFrame.tsx
_api/frames/router.tsx
_api/webhooks/neynar_mention.ts
api-lib/colinks/helperAccounts.ts

Help Frame
Front Door Frame
Error States in the bot

error states and help

---

_api/frames/router.tsx
_api/hasura/actions/_handlers/createCoLinksGive.ts
_api/webhooks/neynar_mention.ts

Remove AI responses

---

_api/frames/router.tsx
_api/webhooks/neynar_mention.ts
api-lib/frames/FrameMeta.tsx
api-lib/frames/routingUrls.ts

Refactor imports and routing helpers

---

api-lib/frames/HelpFrame.tsx

show skill example

---

_api/hasura/actions/_handlers/syncCoSoul.ts
api-lib/event_triggers/linkTxNotification.ts
api-lib/neynar/findOrCreateProfileByFid.ts
src/features/points/GiveAvailablePopover.tsx
src/features/points/PointsBar.tsx
src/features/points/getAvailablePoints.ts

For Farcaster folks, but really anyone, after you Mint CoSoul or Join CoLinks you get more give

Extra Give after CoSoul mint / CoLinks Buy

---

api-lib/frames/ErrorFrame.tsx
api-lib/frames/MintSuccessFrame.tsx
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/layoutFragments/FrameHeadline.tsx
api-lib/frames/personas/PersonaFourFrame.tsx
api-lib/frames/personas/PersonaOneFrame.tsx
api-lib/frames/personas/PersonaThreeFrame.tsx
api-lib/frames/personas/PersonaTwoFrame.tsx
api-lib/frames/personas/PersonaZeroFrame.tsx

Give frame artwork should be consistent based on give.id

Consistent GIVE frame art based on give.id

---

api-lib/frames/personas/PersonaFourFrame.tsx

show give stats on lvl 4 persona page

---

api-lib/frames/HelpFrame.tsx
api-lib/frames/personas/PersonaTwoFrame.tsx

comp0ose cta on help frame and level 4 frame

givebot compose url

---

api-lib/frames/personas/PersonaFourFrame.tsx
src/pages/colinks/ExplorePage.tsx
src/pages/colinks/explore/MostGivePage.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

🐞 give explore view all page was never made :(

---

api-lib/frames/layoutFragments/FrameWrapper.tsx

testing badge

---

_api/frames/router.tsx
api-lib/frames/layoutFragments/FrameBgImage.tsx

load background files from filesystem

---

_api/frames/router.tsx
api-lib/frames/routingUrls.ts

Enable caching

---

api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/databases/default/tables/public_profiles_public.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/features/colinks/LeaderboardMostGiveGiven.tsx
src/features/colinks/LeaderboardMostGiven.tsx
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/pages/colinks/ExplorePage.tsx
src/pages/colinks/explore/MostGivenPage.tsx
src/pages/colinks/explore/TabButton.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

Show most GIVE given on CoLinks explore

---

api-lib/frames/FrontDoorFrame.tsx
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/personas/PersonaOneFrame.tsx

Bot Metrics

---

api-lib/frames/MintWaitingFrame.tsx
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/neynar/findOrCreateProfileByFid.ts

Track clicker_relation

---

api-lib/frames/FrameMeta.tsx

redirect to colinks when clicking the frame

---

_api/frames/router.tsx
api-lib/frames/ErrorFrame.tsx
api-lib/frames/FrameMeta.tsx
api-lib/frames/HelpFrame.tsx
api-lib/frames/MintSuccessFrame.tsx
api-lib/frames/MintWaitingFrame.tsx
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/personas/PersonaOneFrame.tsx
api-lib/frames/personas/PersonaTwoFrame.tsx
api-lib/frames/personas/PersonaZeroFrame.tsx
api-lib/frames/routingUrls.ts

Frame tweaks

---

api-lib/frames/FrameMeta.tsx

link to give docs instead

---

_api/frames/router.tsx

No cacheing on localhost

---

api-lib/frames/layoutFragments/FramePersonaHeadline.tsx
api-lib/frames/personas/PersonaFourFrame.tsx
api-lib/frames/personas/PersonaOneFrame.tsx
api-lib/frames/personas/PersonaThreeFrame.tsx
api-lib/frames/personas/PersonaTwoFrame.tsx
api-lib/frames/personas/PersonaZeroFrame.tsx

show stats in persona headline

---

src/features/cosoul/CoSoulButton.tsx

replace deposit to mint text

---

api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/PartyHelpFrame.tsx
api-lib/frames/routingUrls.ts
src/pages/GiveParty.tsx
src/routes/paths.ts
src/ui/Tooltip/PartyDisplayText.tsx

splash page stylee

---

_api/og/tags.ts
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/onSendGIVEPost.tsx
cloudflare/workers/ogtags/src/index.ts

give.party meta tags/frame for splash page

---

_api/frames/router.tsx
_api/og/tags.ts
api-lib/frames/FrameMeta.tsx
api-lib/frames/giveparty/GivePartyHomeFrame.tsx
api-lib/frames/giveparty/GivePartyMintCoSoulFrame.tsx
api-lib/frames/giveparty/GivePartyMintWaitingFrame.tsx
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/PartyHelpFrame.tsx

fix aspect ratio and setup clicks

---

_api/og/tags.ts

Update giveparty tags

---

_api/og/tags.ts
api-lib/frames/giveparty/PartyHelpFrame.tsx
api-lib/frames/giveparty/PartyStartFrame.tsx

copy on help and inputText on give party frame

---

api-lib/frames/giveparty/PartyStartFrame.tsx

the -> your

---

api-lib/frames/giveparty/PartyHelpFrame.tsx
api-lib/frames/giveparty/PartyStartFrame.tsx

frame colors

---

_api/og/tags.ts

remove og tag comments

---

api-lib/frames/giveparty/JoinedPartyFrame.tsx

Bugfix level display

---

api-lib/frames/giveparty/onSendGIVEPost.tsx
src/pages/GiveParty.tsx

extend username max, special message for based

---

api-lib/frames/giveparty/GivePartyHomeFrame.tsx

special case based

---

src/pages/colinks/explore/NewestMembersPage.tsx

fix newest explore

---

api-lib/frames/giveparty/GivePartyHomeFrame.tsx
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/PartyHelpFrame.tsx
api-lib/frames/giveparty/PartyStartFrame.tsx

random gradient for party created frame

---

api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/give/getGive.tsx

add skill tag to give square frame

---

api-lib/frames/give/GiveHomeFrame.tsx

still too dark for me
but not very differnt:

skill pill bg

---

scripts/repl.ts
src/features/cosoul/api/pgive.ts

include colinks GIVE in pGIVE (finally)

---

api-lib/frames/layoutFragments/PartyText.tsx

Bugfix no wrap party text

---

_api/hasura/cron/cosoulMinter.ts
_api/hasura/cron/syncCoSouls.ts
src/pages/GiveLeaderboard.tsx

sync co links pgive

---

src/pages/GiveParty.tsx

style: party safari top bar

---

src/pages/GiveLeaderboard.tsx

mobile styles for giveboard

---

_api/hasura/cron/syncCoSouls.ts

sync cosouls that have unknown pgive or pgive=0

---

src/pages/GiveLeaderboard.tsx
src/pages/GiveParty.tsx
src/pages/GiveParty/PartyBody.tsx
src/pages/GiveParty/PartyHeader.tsx
src/pages/GiveSkillLeaderboard.tsx

UI Fixes
Layout fragments
simple nav via header

Giveboard bugfixes

---

_api/frames/router.tsx
api-lib/frames/getSkillLeaderboardFromParams.ts
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/LeaderboardFrame.tsx
api-lib/frames/giveparty/SkillLeaderboardFrame.tsx
api-lib/frames/layoutFragments/PartyText.tsx
src/pages/GiveLeaderboard.tsx
src/pages/GiveParty.tsx
src/pages/GiveParty/PartyBody.tsx
src/pages/GiveParty/PartyHeader.tsx
src/pages/GiveSkillLeaderboard.tsx

Scaffold leaderboard frame

---

api-lib/frames/giveparty/onSendGIVEPost.tsx
api-lib/neynar/findOrCreateProfileByFid.ts

convert the username to lowercase before fetching
use the returned username for mentioning

user farcast user name for mentions and lower username case

---

api-lib/frames/giveparty/GivePartyHomeFrame.tsx
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/SkillLeaderboardFrame.tsx

nav back to GIVE from leaderboard

---

api-lib/frames/giveparty/onSendGIVEPost.tsx
api-lib/neynar/findOrCreateProfileByFid.ts

Reverts coordinape/coordinape#2889

Revert "user farcast user name for mentions and lower username case"

---

api-lib/frames/giveparty/onSendGIVEPost.tsx
api-lib/neynar/findOrCreateProfileByFid.ts

Colinks use fc usernames and lowercase

---

src/features/activities/ContributionRow.tsx

remove replybox from contributions in activities and give side bar

remove replybox from contributions

---

_api/frames/router.tsx
_api/og/tags.ts
api-lib/frames/giveparty/ProfileFrame.tsx
api-lib/frames/giveparty/addressResourceIdentifier.ts

use regular frame impl in the cloudflare worker, add profile frame

---

_api/frames/router.tsx
api-lib/frames/ErrorFrame.tsx
api-lib/frames/FrameMeta.tsx
api-lib/frames/FrontDoorFrame.tsx
api-lib/frames/HelpFrame.tsx
api-lib/frames/MintSuccessFrame.tsx
api-lib/frames/MintWaitingFrame.tsx
api-lib/frames/_staticResourceIdentifier.ts
api-lib/frames/frames.ts
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/give/giveResourceIdentifier.ts
api-lib/frames/giveparty/GivePartyHomeFrame.tsx
api-lib/frames/giveparty/GivePartyMintCoSoulFrame.tsx
api-lib/frames/giveparty/GivePartyMintWaitingFrame.tsx
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/PartyHelpFrame.tsx
api-lib/frames/giveparty/PartyStartFrame.tsx
api-lib/frames/giveparty/ProfileFrame.tsx
api-lib/frames/giveparty/SkillLeaderboardFrame.tsx
api-lib/frames/giveparty/addressResourceIdentifier.ts
api-lib/frames/giveparty/skillResourceIdentifier.ts
api-lib/frames/layoutFragments/FrameBgImage.tsx
api-lib/frames/personas/PersonaFourFrame.tsx
api-lib/frames/personas/PersonaOneFrame.tsx
api-lib/frames/personas/PersonaThreeFrame.tsx
api-lib/frames/personas/PersonaTwoFrame.tsx
api-lib/frames/personas/PersonaZeroFrame.tsx
api-lib/frames/routingUrls.ts

remove dependencies on router

---

_api/og/tags.ts
api-lib/frames/FrameMeta.tsx

allow for rendering only meta tags of frames

---

_api/frames/router.tsx
_api/webhooks/neynar_mention.ts
api-lib/frames/frames.ts
api-lib/frames/giveparty/GivePartyHomeFrame.tsx
api-lib/frames/giveparty/JoinedSurprisePartyFrame.tsx
api-lib/frames/giveparty/SurprisePartyHelpFrame.tsx
api-lib/frames/giveparty/SurprisePartyHomeFrame.tsx
api-lib/frames/giveparty/SurprisePartyStartFrame.tsx
api-lib/frames/giveparty/checkAndInsertGive.ts
api-lib/frames/giveparty/getSurpriseContextFromParams.ts
api-lib/frames/giveparty/onSendGIVEPost.tsx
api-lib/frames/giveparty/onSendSurpriseGIVEPost.tsx
api-lib/frames/giveparty/usernameResourceIdentifier.ts
api-lib/frames/prefetchFrame.ts
api-lib/frames/routingUrls.ts
api-lib/insertCoLinksGive.ts
src/pages/GiveParty.tsx
src/pages/GiveParty/PartyHeader.tsx

Surprise party

---

api-lib/frames/giveparty/JoinedSurprisePartyFrame.tsx
api-lib/frames/giveparty/SurprisePartyStartFrame.tsx
src/pages/GiveParty.tsx

Bye bye surprise

---

api-lib/frames/giveparty/SurprisePartyHomeFrame.tsx

remove surprise word

---

src/pages/GiveParty/PartyProfile.tsx

update intent from
give.party/0x99999...
to
colinks.coordinape.com/giveparty/0x99999...

wc compose link update

---

api-lib/frames/frames.ts
api-lib/frames/giveparty/ProfileFrame.tsx

cast my profile, view my profile

---

api-lib/frames/giveparty/ProfileFrame.tsx

improve profile frame button and cast text

---

src/pages/GiveParty/PartyProfileGives.tsx
src/pages/GiveParty/PartyProfileHeader.tsx

Profile page UI bugfixin

---

src/pages/GiveParty/PartyGiveReceived.tsx

minor ui alignment bug

---

funding.json

This is a identifier that RPGF 4 requires for verification of our repo.

add OP verify code RPGF 4

---

src/features/cosoul/chains.ts

Up Base fees

---

_api/hasura/actions/_handlers/addFarcaster.ts
_api/hasura/actions/_handlers/getNetwork.ts
_api/hasura/actions/actionManager.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api-lib/neynar.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/cron_triggers.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

getNetwork action 

---

hasura/metadata/actions.yaml
hasura/schema/anon/schema.graphql
src/lib/anongql/__generated__/zeus/const.ts
src/lib/anongql/__generated__/zeus/index.ts

let anonClient use getNetwork

---

hasura/migrations/default/1718301717950_create_farcaster_schema/down.sql
hasura/migrations/default/1718301717950_create_farcaster_schema/up.sql

create farcaster schema

---

_api/hasura/event_triggers/eventManager.ts
api-lib/event_triggers/connectFarcaster.ts
api-lib/farcaster/autoConnectFarcasterAccount.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
hasura/metadata/actions.graphql
hasura/metadata/databases/default/tables/public_farcaster_accounts.yaml
hasura/metadata/databases/default/tables/public_profiles.yaml
hasura/migrations/default/1718302057778_alter_table_public_farcaster_accounts_add_column_bio_text/down.sql
hasura/migrations/default/1718302057778_alter_table_public_farcaster_accounts_add_column_bio_text/up.sql
hasura/schema/admin/schema.graphql
hasura/schema/anon/schema.graphql
hasura/schema/user/schema.graphql
package.json
src/features/colinks/wizard/WizardName.tsx
src/features/farcaster/useMyFarcaster.ts
src/lib/anongql/__generated__/zeus/const.ts
src/lib/anongql/__generated__/zeus/index.ts
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts

automatically connect farcaster for new users and add to wizard

---

_api/hasura/cron/giveOnchainSyncer.ts
api-lib/eas.ts

Tested on sepolia: https://base-sepolia.easscan.org/attestation/view/0x74b0adbc0e691ce4a2e06ce7c1a759a191c3d6ce2d651cd979da4fd1211de124

sync null skill give

---

_api/hasura/actions/_handlers/addFarcaster.ts
_api/hasura/cron/backfillFarcasterConnect.ts
_api/hasura/cron/backfillReputation.ts
_api/hasura/cron/checkNominee.ts
api-lib/config.ts
api-lib/event_triggers/connectFarcaster.ts
api-lib/farcaster/autoConnectFarcasterAccount.ts
api-lib/gql/__generated__/zeus/const.ts
api-lib/gql/__generated__/zeus/index.ts
api-lib/neynar.ts
hasura/metadata/cron_triggers.yaml
hasura/metadata/databases/default/tables/public_profile_flags.yaml
hasura/metadata/databases/default/tables/public_profiles.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1718391276373_create_table_public_profile_flags/down.sql
hasura/migrations/default/1718391276373_create_table_public_profile_flags/up.sql
hasura/schema/admin/schema.graphql
scripts/serve_dev.ts

auto connect farcaster accounts in a cron, add profile_flags table

---

_api/hasura/cron/backfillFarcasterConnect.ts

raise farcaster backfill batch size to 100

---

vercel.json

enable vercel routes

---

_api/give/index.ts
vercel.json

- **Remove vercel config**
- **Decrease limit of gives**

fix vercel

---

_api/hasura/cron/backfillFarcasterConnect.ts

stringify the farcaster_connect_error

---

_api/frames/router.tsx
_api/give/[skill].ts
_api/give/index.ts
package.json
pnpm-lock.yaml
src/pages/NetworkViz/GiveGraph.tsx
vercel.json

- **Try setting aribitrary header**
- **Try vercel.json caching**
- **use commas**
- **use commas and public header**
- **cleanup headers**

vercel cache fix

---

src/pages/NetworkViz/GiveGraph.tsx

Fix types without using any

---

_api/network/[address].ts
src/features/colinks/CoLinksNav.tsx
src/pages/GiveParty/NodesOnCircle.tsx
src/pages/GiveParty/ProfileNetwork.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

bullseye network

---

src/features/activities/SharePostModal.tsx
src/pages/GiveParty/PartyProfile.tsx
src/pages/GiveParty/PartyProfileContent.tsx
src/pages/GiveParty/PartyProfileGives.tsx
src/pages/GiveParty/PartyProfileHeader.tsx
src/pages/GiveSkillLeaderboard.tsx
src/pages/NetworkViz/GiveGraph.tsx

Graph profile drawer

---

hasura/migrations/default/1719956812499_create_index_farcaster_accounts_fid_idx/down.sql
hasura/migrations/default/1719956812499_create_index_farcaster_accounts_fid_idx/up.sql

Add idx to fc accts

---

package.json
pnpm-lock.yaml
src/pages/colinks/CastsPage.tsx

uses https://github.com/pugson/react-farcaster-embed

Use farcast-embed

---

_api/hasura/cron/syncCoSoulReputation.ts

match the checkpoint date

---

_api/hasura/cron/syncCoSoulReputation.ts

tolerate rep_synced_at being null

---

package.json
pnpm-lock.yaml

remove rainbow kit

---

src/features/points/GiveReceived.tsx

link to give leaderboard from colinks skill popover

---

src/features/SearchBox/PartySearchResults.tsx

maybe fix search

---

src/features/SearchBox/PartySearchResults.tsx

name->address in the link

---

package.json
pnpm-lock.yaml
src/pages/colinks/CastsPage.tsx

Reverts coordinape/coordinape#2993

Revert "Use farcast-embed"

---

src/components/ComboBox.tsx
src/features/SearchBox/PartySearchBox.tsx
src/features/SearchBox/PartySearchResults.tsx
src/features/SearchBox/SearchBox.tsx
src/features/SearchBox/fetchPartyProfileResults.ts
src/pages/GiveParty/PartyNav.tsx

search UI improvements

---

hasura/metadata/databases/default/tables/public_activities.yaml

fix cast permissions

---

src/features/farcaster/casts/CastRow.tsx
src/stitches.config.ts
src/ui/MarkdownPreview/LightboxImage.tsx
src/ui/Text/Text.tsx

Style casts

---

src/config/features.ts

enable casts

---

src/features/activities/PostRow.tsx
src/features/activities/PostStats.tsx

CoLinks post tag

---

src/pages/colinks/ActivityPage.tsx
src/pages/colinks/ViewProfilePage/ViewProfilePageContents.tsx
src/ui/Button/Button.tsx

filter casts out

---

src/features/colinks/CoLinksLayout.tsx
src/features/rainbowkit/SiweProvider.tsx
src/hooks/useReloadCookieAuth.ts

Fix bug where refresh page doesnt read auth from cookie

Move logic into hook, and use hook

---

_api/hasura/actions/_handlers/allocationCsv.ts
_api/hasura/actions/_handlers/createVault.ts
_api/hasura/actions/_handlers/createVaultTx.ts
_api/hasura/actions/_handlers/markClaimed.ts
_api/hasura/actions/actionManager.ts
_api/hasura/cron/recoverTransactions.ts
_api/hasura/remote/vaults.ts
_api/login.ts
api-test/login.test.ts
hasura/metadata/cron_triggers.yaml
hasura/metadata/databases/default/tables/public_vaults.yaml
hasura/metadata/remote_schemas.yaml
scripts/serve_dev.ts
src/lib/vaults/circleId.ts
src/lib/vaults/contracts.ts
src/lib/vaults/distributor.ts
src/lib/vaults/index.ts
src/lib/vaults/tokens.ts

Reverts coordinape/coordinape#3036

Revert "Remove vaults: backend"

---

src/App.tsx
src/config/features.ts
src/features/debug/DebugOverlay.tsx

debug overlay with Cmd+U

---

src/pages/MembersPage/MembersTable.tsx

fixed update member form submitting
fixed table headers and indices
there were errors preventing member form data to be submittet
removed fixed payment validation because the field is removed
updated the table indices
added await to updateUser 
before
after

fix update member form submitting and members table headers

---

src/features/colinks/CoLinksNav.tsx
src/features/points/PointsBar.tsx
src/features/points/PointsBarInfo.tsx
src/pages/colinks/ActivityPage.tsx

Give bar in nav

---

src/features/cosoul/CoLinksSplashNav.tsx

Minor UI: need full width for alignment

---

_api/hasura/cron/syncCoSouls.ts
api-lib/viem/contracts.ts
src/utils/domain.ts
src/utils/viem/contracts.ts
src/utils/viem/publicClient.ts

Resolves another alchemy FE token used on BE error

Fix bug where FE token is used on BE

---

_api/hasura/cron/syncCoSouls.ts
api-lib/viem/contracts.ts
src/utils/domain.ts
src/utils/viem/contracts.ts
src/utils/viem/publicClient.ts

Reverts coordinape/coordinape#3063

Revert "Fix bug where FE token is used on BE"

---

src/pages/colinks/CoLinksProfilePage/ProfilePageGiveContents.tsx

automatic give graph width on profile

---

src/features/colinks/BuyOrSellCoLinks.tsx
src/features/colinks/Poaps.tsx
src/pages/AccountPage/AccountPage.tsx
src/pages/colinks/CoLinksProfilePage/ProfileCards.tsx
src/pages/colinks/CoLinksProfilePage/ProfileHeader.tsx
src/stitches.config.ts

Fix wrapping issue with profile header
Fix dark mode card colors

card colors.  fix overflow issue with profile heazder linkds

---

src/pages/colinks/CoLinksProfilePage/ProfileCards.tsx

Profile tablet breakpoint styling

---

src/pages/GiveSkillLeaderboard.tsx
src/pages/NetworkViz/AutosizedGiveGraph.tsx
src/pages/colinks/CoLinksProfilePage/ProfilePageGiveContents.tsx

auto size give graph

---

src/features/colinks/Poaps.tsx
src/features/points/GiveReceived.tsx
src/pages/colinks/CoLinksProfilePage/ProfileCards.tsx

_eq: address ➡ _ilike: address

change address queries to be ilike

---

src/features/colinks/CoLinksLayout.tsx
src/pages/GiveSkillLeaderboard.tsx
src/pages/NetworkViz/GiveGraph.tsx
src/pages/colinks/CoLinksProfilePage/SkillGiveMap.tsx
src/pages/colinks/CoLinksProfilePage/ViewProfilePageGiveMap.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

Full screen give map skills

---

src/pages/NetworkViz/GiveGraph.tsx
src/pages/NetworkViz/LinksGraph.tsx

fix the avatars for people w/ colinks avis

---

src/features/activities/replies/RepliesBox.tsx

handle reply fetching better

---

_api/hasura/actions/_handlers/syncCoSoul.ts
api-lib/viem/contracts.ts
src/features/cosoul/MintOrBurnButton.tsx
src/features/cosoul/api/cosoul.ts

First attempt at fixing: https://app.datadoghq.com/logs?query=%40proxy.path%3A%22%2Fapi%2Fhasura%2Factions%2FactionManager%3Faction_name%3DsyncCoSoul%22%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1725578147329&to_ts=1725581747329&live=true
Seeing some errors still persist though

Fix bug in BE calling getTokenId with FE alchemy api key

---

src/features/DecentSwap/SwapComponent.tsx
src/features/DecentSwap/executeTransaction.ts
src/features/colinks/BuyOrSellCoLinks.tsx
src/features/cosoul/CoSoulButton.tsx
src/features/wagmi/config.ts
src/utils/viem/publicClient.ts

used  sendTransaction and  waitForTransactionReceipt from wagmi core
@crabsinger  I have update publicClient.ts with the rest of chains but I am not using it right now

use wagmi for decent transactions

---

src/pages/colinks/CoLinksProfilePage/ProfilePagePostsContents.tsx

🐞 Is Colinks filter wasn't showing up

---

src/pages/colinks/CoLinksProfilePage/ProfileCards.tsx

change farcaster most recent cast fetch to use anon client

---

src/features/colinks/LinkTxProgress.tsx
src/pages/colinks/CoLinksProfilePage/LinkUpCard.tsx

🐞 add container for link tx message

---

src/pages/colinks/CoLinksProfilePage/ProfilePagePostsContents.tsx

No-posts message on profile

---

src/features/auth/useLogout.ts
src/features/nav/getNavData.ts
src/features/notifications/useNotificationCount.tsx

logout when useNotificationCount or getNavData gets Auth Hook errors

---

src/features/colinks/wizard/WizardRep.tsx
src/features/github/ConnectGitHubButton.tsx
src/features/linkedin/ConnectLinkedInButton.tsx
src/features/twitter/ConnectTwitterButton.tsx
src/pages/ProfilePage/EmailSettings/EmailCTA.tsx

UI bugfix social link width

---

src/config/features.ts
src/features/colinks/CoLinksNav.tsx

remove feature flag for give zone

---

src/components/MainLayout/CreateUserNameForm.tsx
src/features/colinks/CoLinksNavProfile.tsx

Prompt for Name

---

_api/login.ts

use FC data for default name and avatar

---

src/pages/GiveSkillLeaderboard.tsx

improve querykey for give skill

---

src/pages/GiveLeaderboard.tsx
src/pages/GiveSkillLeaderboard.tsx
src/pages/GiveSkillPage.tsx
src/pages/colinks/give/GivePage.tsx

put them at the bottom on mobile.  trying this for a while

Learn about give cards mobile order

---

api-lib/neynar/findOrCreate.ts
src/features/cloudflare/uploadURLToCloudflare.ts

when creating a new user from farcaster, upload their url to cloudflare

---

api-lib/colinks/hostname.ts
src/config/webAppURL.ts
src/features/colinks/useIsCoLinksSite.ts
src/hooks/index.ts
src/hooks/useIsGiftCircleSite.ts
src/pages/colinks/LaunchPage.tsx
src/pages/colinks/NotificationsPage.tsx
src/routes/paths.ts
src/routes/routes.tsx

Set this up in /etc/hosts to support co.local
127.0.0.1       colinks.co.local app.co.local co.local	localhost

Switch to coordinape.com as root

---

src/features/colinks/CoLinksNav.tsx

improve the nav a bit to include gift circle

---

_api/og/tags.ts
index.html

improve ogtags

---

src/features/activities/ActivityRow.test.tsx
src/features/activities/reactions/ReactionBar.tsx
src/features/activities/replies/ReplyForm.tsx
src/features/colinks/CoLinksNav.tsx

handle react/reply when logged out, Gift Circle -> Circles App

---

src/features/colinks/CoLinksNav.tsx
src/features/github/ConnectGitHubButton.tsx
src/ui/Button/Button.tsx

Gift circle nav cta

---

src/features/colinks/wizard/WizardCoSoul.tsx
src/features/colinks/wizard/WizardCoSoulSteps.tsx
src/features/colinks/wizard/WizardName.tsx
src/features/colinks/wizard/WizardProgress.ts
src/features/cosoul/CoLinksMintPage.tsx
src/features/cosoul/CoSoulArtContainer.tsx
src/features/cosoul/CoSoulCompositionRep.tsx
src/features/cosoul/CoSoulPromo.tsx
src/features/cosoul/MintingModal.tsx
src/features/cosoul/glitch.css
src/features/cosoul/useCoSoulToken.ts
src/features/farcaster/ConnectFarcasterButton.tsx
src/pages/GiveSkillLeaderboard.tsx
src/pages/colinks/CoLinksProfilePage/ProfilePageReputationContents.tsx
src/pages/colinks/cosoul/CoSoulPage.tsx
src/pages/colinks/cosoul/CoSoulWizard.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

Mint cosoul cta on profile rep page

---

README.md
api-lib/frames/give/GiveHomeFrame.tsx

Fix undefined in Give Party Home Frame

---

_api/farcaster/actions/give/[skill].ts
scripts/serve_dev.ts
vercel.json

action for GIVE in warpcaster

---

_api/farcaster/actions/give/[skill].ts

fix toast msg

---

_api/farcaster/actions/give/[skill].ts

fix target user

---

src/pages/GiveLeaderboard.tsx
src/pages/GiveSkillLeaderboard.tsx

improve give sorting to use db query instead of in memory

---

api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/neynar/findOrCreate.ts
scripts/repl.ts
src/features/cloudflare/uploadURLToCloudflare.ts

- **Fix cloudflare variants**
- **Fix variant handling**

fix cloudflare avatars

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
_api/hasura/actions/_handlers/skillCsv.ts
_api/hasura/actions/actionManager.ts
api-lib/gql/__generated__/zeus/const.ts
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/schema/admin/schema.graphql
hasura/schema/user/schema.graphql
src/lib/gql/__generated__/zeus/const.ts
src/lib/gql/__generated__/zeus/index.ts
src/pages/GiveLeaderboard.tsx
src/pages/GiveSkillLeaderboard.tsx
src/pages/GiveSkillPage.tsx

csv for skill

---

src/features/points/GiveReceived.tsx
src/pages/colinks/CoLinksProfilePage/ProfilePageGiveContents.tsx

ui bugfix: skill overflow fix

---

hasura/metadata/databases/default/tables/public_colinks_gives.yaml
src/features/colinks/RecentGives.tsx
src/pages/GiveSkillPage.tsx

Recent gives art

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
api-lib/insertCoLinksGive.ts

Move event emission to helper

---

_api/farcaster/casts/recentlikes.ts

- **change to 2 days**
- **Cache query to 300 seconds**

fix less time

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
api-lib/event_triggers/connectFarcaster.ts
api-lib/farcaster/autoConnectFarcasterAccount.ts
api-lib/neynar/findOrCreate.ts
docker-compose.yml
hasura/migrations/default/1731020271110_refactor_enriched_casts/down.sql
hasura/migrations/default/1731020271110_refactor_enriched_casts/up.sql
src/features/colinks/RecentGives.tsx

Working: copies casts into enriched_casts

enrich casts

---

src/components/HelpButton.tsx
src/features/colinks/CoLinksNav.tsx
src/features/colinks/CoLinksNavProfile.tsx
src/features/nav/NavItem.tsx

about page links

---

_api/give/index.ts
_api/give/trending.ts
scripts/serve_dev.ts
src/features/HomeCards/TopGiveSkills.tsx
src/features/colinks/RecentGives.tsx
src/pages/Home2.tsx

Create an API to get the top skills.
- All gives should be of same 'skill'.
- Question: All gives should have casts? or just all gives? (current is all gives)

Create api to get top/trending give skills and component

---

_api/hasura/cron/giveOnchainSyncer.ts
api-lib/eas.ts
src/config/env.ts

Post all worked-with give to Icebreaker webhook

---

src/pages/colinks/CoLinksProfilePage/ProfileNav.tsx
src/ui/ContentHeader/ContentHeader.tsx

🐛 zindex nav give popover

---

src/components/SkillComboBox/SkillComboBox.tsx
src/features/points/CoLinksGiveButton.tsx

In ColinksGive combobox, fetch give with most uses over last 30 days, and use that list for the combobox.

Fix give skill ordering

---

_api/give/trending.ts

Fetch total give skills not give skills per user.

Fix trending give skills query

---

src/pages/GiveSkillPage.tsx
src/pages/Home2.tsx
src/pages/colinks/ActivityPage.tsx
src/pages/colinks/CastsPage.tsx
src/pages/colinks/CoLinksProfilePage/ProfileAvatarAndName.tsx
src/pages/colinks/CoLinksProfilePage/ProfileHeader.tsx
src/pages/colinks/ExplorePage.tsx
src/pages/colinks/HighlightsPage.tsx
src/pages/colinks/LinkHistoryPage.tsx
src/pages/colinks/LinkHoldersPage.tsx
src/pages/colinks/LinkHoldingsPage.tsx
src/pages/colinks/NotificationsPage.tsx
src/pages/colinks/TradesPage/index.tsx
src/pages/colinks/explore/BigQuestionPage.tsx
src/pages/colinks/explore/BigQuestionsPage.tsx
src/pages/colinks/explore/HighestRepScorePage.tsx
src/pages/colinks/explore/HoldingMostLinksPage.tsx
src/pages/colinks/explore/MostGivePage.tsx
src/pages/colinks/explore/MostGivenPage.tsx
src/pages/colinks/explore/MostLinksPage.tsx
src/pages/colinks/explore/NewestMembersPage.tsx
src/pages/colinks/explore/PeopleWithSkill.tsx
src/pages/colinks/give/GivePage.tsx
src/pages/colinks/give/GivePagesLayout.tsx
src/pages/giveSkillLeaderboardPage.tsx

Remove "Colinks" from page title and replace with "Coordinape"

Update Colinks to Coordinape in helmet

---

api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/frames/give/GiveHomeFrame.tsx
scripts/repl.ts
src/features/ai/replicate.ts

Generate images for all give

---

src/features/colinks/RecentGives.tsx
src/pages/GiveFeed.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

Create feed of all recent give

---

src/features/colinks/RecentGives.tsx
src/pages/GiveSkillNav.tsx
src/pages/GiveSkillPage.tsx
src/pages/giveSkillLeaderboardPage.tsx

🐜 max width recent give

---

_api/frames/router.tsx

fix HEAD handling for frame meta

---

api-lib/frames/FrameMeta.tsx
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/giveparty/GivePartyHomeFrame.tsx
api-lib/frames/giveparty/GivePartyMintCoSoulFrame.tsx
api-lib/frames/giveparty/GivePartyMintWaitingFrame.tsx
api-lib/frames/giveparty/JoinedPartyFrame.tsx
api-lib/frames/giveparty/JoinedSurprisePartyFrame.tsx
api-lib/frames/giveparty/PartyHelpFrame.tsx
api-lib/frames/giveparty/PartyStartFrame.tsx
api-lib/frames/giveparty/SurprisePartyHelpFrame.tsx
api-lib/frames/giveparty/SurprisePartyHomeFrame.tsx
api-lib/frames/giveparty/SurprisePartyStartFrame.tsx

change the default link from docs to /give for all frames

---

api-lib/farcaster/autoConnectFarcasterAccount.ts
api-lib/neynar/findOrCreate.ts

Improve fc user creation

---

src/features/HomeCards/OtherGiveSkills.tsx
src/features/HomeCards/TopReceivers.tsx
src/features/HomeCards/TopSenders.tsx
src/pages/GiveHome.tsx
src/pages/GiveSendersLeaderboard.tsx

Give home data bugs

---

src/features/colinks/RecentGives.tsx
src/pages/GiveLeaderboardNav.tsx
src/pages/colinks/give/GiveLeaderboardPage.tsx
src/pages/colinks/give/GivePage.tsx
src/pages/colinks/give/GiveSendersPage.tsx
src/routes/coLinksRoutes.tsx
src/routes/paths.ts

Give stream give page

---

api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/openai.ts
scripts/repl.ts
src/features/ai/replicate.ts
src/features/cloudflare/uploadURLToCloudflare.ts

- **Setup flux schnell gen**
- **use llm to gen image prompt**

update image gen

---

api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/openai.ts

Mention give sender

---

api-lib/frames/give/GiveHomeFrame.tsx

restrict input text length to 25

---

src/features/colinks/RecentGives.tsx
src/stitches.config.ts

Give flaps bye

---

src/pages/GiveHome.tsx
src/pages/colinks/give/GiveLeaderboardPage.tsx
src/pages/colinks/give/GivePage.tsx
src/pages/colinks/give/GiveReceiversPage.tsx
src/pages/colinks/give/GiveSendersPage.tsx
src/pages/giveSkillLeaderboardPage.tsx

... and some strange padding on smaller breakpoints

🐛 fix overflow bug on mobile

---

src/features/nav/NavLogo.tsx

change nav link to be root instead of explore

---

vercel.json

deny iframes in vercel.json

---

api-test/hasura/actions/_handlers/createEpoch.test.ts
api-test/hasura/actions/_handlers/updateEpoch.test.ts

skip failing tests

---

_api/hasura/cron/dailyUpdate.ts
api-lib/sendSocialMessage.test.ts

These are failing, disable them.

Disable erroring discord social notification

---

src/features/colinks/RecentGives.tsx
src/pages/GiveHome.tsx
src/pages/GiveSkillPage.tsx

show `give.skill` on recent GIVE page

---

api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/openai.ts
src/features/ai/replicate.ts
src/features/colinks/RecentGives.tsx

Replicatey

---

api-lib/openai.ts
src/features/ai/replicate.ts

more clothes in replicate art

---

api-lib/frames/give/GiveHomeFrame.tsx
api-lib/frames/layoutFragments/FrameHeadline.tsx
src/features/ai/replicate.ts
src/features/colinks/RecentGives.tsx

Fix frame content height to match image height

Frame height

---

src/features/HomeCards/TopGiveSkills.tsx
src/features/colinks/RecentGives.tsx
src/pages/GiveLeaderboardNav.tsx
src/pages/colinks/CoLinksProfilePage/ProfileNav.tsx
src/pages/colinks/CoLinksProfilePage/ProfilePageGiveContents.tsx

GIVES on Profile

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
api-lib/openai.ts

- **Add Helicone-Property-App**
- **Add helicone fucntion tracking**

helicone tracking

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
api-lib/openai.ts

add unlimited give for furry and fix typo

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
api-lib/openai.ts

Reverts coordinape/coordinape#3220

Revert "add unlimited give for furry and fix typo"

---

src/pages/colinks/CoLinksProfilePage/ProfileHeader.tsx

refactor profile header query to separate skills and anon social links

Show social links in profile logged out profile header

---

_api/hasura/actions/_handlers/createCoLinksGive.ts

Added new profile ID 4064836 to UNLIMITED_GIVE_PROFILES array in createCoLinksGive.ts

Add profile ID 4064836 to unlimited give profiles

---

src/pages/colinks/CoLinksProfilePage/ProfilePageGiveContents.tsx

...even if GIVE data is incomplete. if there is sent data, we should show sent content (even if there's nothing yet received)

🐞 profile panels should show

---

.goosehints
api-lib/sendSocialMessage.ts

- **Disable Discord message functionality in sendSocialMessage due to 503 errors**
- **fix**

fix social message error

---

_api/hasura/actions/_handlers/createCoLinksGive.ts

add co-creator to unlimited  give

---

package.json
src/lib/anongql/.gitignore
src/lib/anongql/.npmignore
src/lib/anongql/README.md
src/lib/anongql/anonClient.ts
src/lib/anongql/index.ts
src/lib/anongql/package.json
src/lib/anongql/tsconfig.json

add workspace

---

_api/hasura/actions/_handlers/createCoLinksGive.ts
_api/hasura/cron/giveOnchainSyncer.ts
api-lib/eas.ts
api-lib/frames/give/GiveHomeFrame.tsx
api-lib/give.ts

refactor give weight to a function, add give weight to EAS

---

api-lib/give.ts
hasura/metadata/databases/default/tables/public_farcaster_accounts.yaml
hasura/metadata/databases/default/tables/public_profiles.yaml

allow more profiles to be returned to api, allow farcaster_account in api

---

hasura/metadata/databases/default/tables/public_users.yaml

fix limit on users table

---

src/features/ai/replicate.ts

Special give art style for `#create` GIVE

---

api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/farcaster/backfillCastActivity.ts
api-lib/neynar.ts
api-lib/neynar/findOrCreate.ts
api-lib/openai/getBestCast.ts
api-lib/openai/getChannelInsights.ts
package.json
pnpm-lock.yaml
src/pages/GiveParty/useFarcasterUser.ts

upgrade neynar api to v2

---

api-lib/neynarSignature.ts

Add neynar req logging

---

api-lib/neynarSignature.ts

Reverts coordinape/coordinape#3247

Revert "Add neynar req logging"

---

_api/farcaster/user/[address].ts
_api/webhooks/neynar_mention.ts
api-lib/event_triggers/createColinksGiveEvent.ts
api-lib/frames/FrameMeta.tsx
api-lib/neynar.ts

fix neynar reply nesting

---

src/features/cosoul/chains.ts

dobule gas limits for base

---

src/features/cosoul/chains.ts

set higher gas limits

---

_api/hasura/cron/giveOnchainSyncer.ts
api-lib/eas.ts

More logging

---

api-lib/eas.ts

Reverts coordinape/coordinape#3254

Revert "Gasgasgas"

---

_api/hasura/cron/giveOnchainSyncer.ts
api-lib/eas.ts

lots of eas debugging

---

api-lib/eas.ts

hardcode the nonce

---

_api/token_balances/refresh.ts
scripts/serve_dev.ts
vercel.json

Create token balance refresh function
